// Code generated by alef — DO NOT EDIT.
// alef:hash:905cbea36a73450b9871b6a3e634f52588f46b933cb60073def43ae82bffc938
package literllm

// RequireNativeSetup_1_18_0 is a version-skew sentinel referenced by the
// machine-local cgo link shim that `cmd/setup` writes into consumer packages. If this
// module is upgraded without re-running `cmd/setup`, the previously written shim (built
// against the old version) references an identifier that no longer exists here, turning
// silent native-library skew into a compile-time error instead of a runtime crash.
const RequireNativeSetup_1_18_0 = "1.18.0"
