// Code generated by alef — DO NOT EDIT.
// alef:hash:94c9b357f2590d12f6b8bcd3bec250a847ec1de876e4be817facd6ce9a98e7eb
package literllm

// RequireNativeSetup_1_18_0 is a version-skew sentinel referenced by the
// machine-local cgo link shim that `cmd/setup` writes into consumer packages. If this
// module is upgraded without re-running `cmd/setup`, the previously written shim (built
// against the old version) references an identifier that no longer exists here, turning
// silent native-library skew into a compile-time error instead of a runtime crash.
const RequireNativeSetup_1_18_0 = "1.18.0"
