// Code generated by alef — DO NOT EDIT.
// alef:hash:04f494b067a440ad948899da27aedb8a1c6afeb6ec7c757953bdf716655562e8
package literllm

// RequireNativeSetup_2_0_3 is a version-skew sentinel referenced by the
// machine-local cgo link shim that `cmd/setup` writes into consumer packages. If this
// module is upgraded without re-running `cmd/setup`, the previously written shim (built
// against the old version) references an identifier that no longer exists here, turning
// silent native-library skew into a compile-time error instead of a runtime crash.
const RequireNativeSetup_2_0_3 = "2.0.3"
