// Generated by alef. Do not edit by hand.
// alef:hash:4ae4de5d90041731d4a21581960edb664b6d4fd842c14958be41304f52c6a28e

pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}

plugins {
    id("org.gradle.toolchains.foojay-resolver-convention") version "1.0.0"
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.name = "liter-llm-android-e2e"
