# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:c249c70b7640c53f754d8c96cd8e49cec28afa7f81e8f316163a5ff7df9c9773
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
# E2e tests for category: custom_provider
defmodule E2e.CustomProviderTest do
  use ExUnit.Case, async: true

  describe "provider_auth" do
    test "Tests custom provider with custom auth header" do
      {:ok, result} = LiterLlm.chat_async(nil)
    end
  end

  describe "register_provider" do
    test "Tests that a custom provider can be registered and routes requests" do
      {:ok, result} = LiterLlm.chat_async(nil)
    end
  end
end
