# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:4494f62e0eb5e65d68c4273e0cb53a3f972a08589a6139baeb904617b1a22190
# To regenerate: alef generate
# To verify freshness: alef verify
# E2e tests for category: transcribe
defmodule E2e.TranscribeTest do
  use ExUnit.Case, async: false

  describe "edge_transcribe_empty_audio" do
    test "edge_transcribe_empty_audio" do
      {:ok, client} =
        LiterLlm.create_client("test-key", base_url: (System.get_env("MOCK_SERVER_URL") || "") <> "/fixtures/edge_transcribe_empty_audio")

      {:ok, result} = LiterLlm.defaultclient_transcribe_async(client, "{\"file\":\"silence.mp3\",\"model\":\"whisper-1\"}")
      refute is_nil(result)
      assert String.contains?(to_string(result.text), "")
    end
  end

  describe "edge_transcribe_with_timestamps" do
    test "edge_transcribe_with_timestamps" do
      {:ok, client} =
        LiterLlm.create_client("test-key",
          base_url: (System.get_env("MOCK_SERVER_URL") || "") <> "/fixtures/edge_transcribe_with_timestamps"
        )

      {:ok, result} =
        LiterLlm.defaultclient_transcribe_async(
          client,
          "{\"file\":\"audio.mp3\",\"model\":\"whisper-1\",\"response_format\":\"verbose_json\"}"
        )

      refute is_nil(result)
      assert result.text not in [nil, "", [], %{}]
      assert length(result.segments) == 3
      assert Enum.at(result.segments, 0).id == 0
    end
  end

  describe "error_transcribe_auth_401" do
    test "error_transcribe_auth_401" do
      {:ok, client} =
        LiterLlm.create_client("test-key", base_url: (System.get_env("MOCK_SERVER_URL") || "") <> "/fixtures/error_transcribe_auth_401")

      assert {:error, __reason} = LiterLlm.defaultclient_transcribe_async(client, "{\"file\":\"audio.mp3\",\"model\":\"whisper-1\"}")
      assert String.contains?(inspect(__reason), "Authentication")
    end
  end

  # skipped: assertion type 'equals' has no accessor for error field error.status_code in this backend

  describe "error_transcribe_bad_format" do
    test "error_transcribe_bad_format" do
      {:ok, client} =
        LiterLlm.create_client("test-key", base_url: (System.get_env("MOCK_SERVER_URL") || "") <> "/fixtures/error_transcribe_bad_format")

      assert {:error, __reason} = LiterLlm.defaultclient_transcribe_async(client, "{\"file\":\"audio.xyz\",\"model\":\"whisper-1\"}")
      assert String.contains?(inspect(__reason), "BadRequest")
    end
  end

  # skipped: assertion type 'equals' has no accessor for error field error.status_code in this backend

  describe "smoke_transcribe_basic" do
    test "smoke_transcribe_basic" do
      {:ok, client} =
        LiterLlm.create_client("test-key", base_url: (System.get_env("MOCK_SERVER_URL") || "") <> "/fixtures/smoke_transcribe_basic")

      {:ok, result} = LiterLlm.defaultclient_transcribe_async(client, "{\"file\":\"audio.mp3\",\"model\":\"whisper-1\"}")
      refute is_nil(result)
      assert String.contains?(to_string(result.text), "Hello, this is a test transcription.")
    end
  end

  describe "smoke_transcribe_with_language" do
    test "smoke_transcribe_with_language" do
      {:ok, client} =
        LiterLlm.create_client("test-key",
          base_url: (System.get_env("MOCK_SERVER_URL") || "") <> "/fixtures/smoke_transcribe_with_language"
        )

      {:ok, result} =
        LiterLlm.defaultclient_transcribe_async(client, "{\"file\":\"audio_de.mp3\",\"language\":\"de\",\"model\":\"whisper-1\"}")

      refute is_nil(result)
      assert String.contains?(to_string(result.text), "Hallo, dies ist ein Testtranskription.")
    end
  end
end
