# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:af7468ada2cd9571058cc95cc9883fc5ba83e0daaefa883551b310ba55f8dd2b
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# frozen_string_literal: true

require 'spec_helper'
require 'liter_llm'
require 'json'

RSpec.describe 'parity' do
  it 'api_surface_parity: Canonical API surface definition for cross-binding parity verification' do
    client = LiterLlm.create_client('test-key', ENV.fetch('MOCK_SERVER_URL') + '/fixtures/api_surface_parity')
    result = client.chat_async(LiterLlm::ChatCompletionRequest.new(messages: [{ 'content' => 'Hello', 'role' => 'user' }], model: 'gpt-4o'))

    expect(result).not_to be_nil
  end
end
