// Generated by alef. Do not edit by hand.
// alef:hash:0783aee6e908204eb13673a006c17ad2888b62c72010e3674bb2df300f001862
@file:Suppress(
    "ktlint:standard:trailing-comma-on-call-site",
    "ktlint:standard:trailing-comma-on-declaration-site",
    "ktlint:standard:spacing-between-declarations-with-comments",
    "ktlint:standard:spacing-between-declarations-with-annotations",
    "ktlint:standard:when-entry-bracing",
    "ktlint:standard:blank-line-between-when-conditions",
    "ktlint:standard:blank-line-before-declaration",
    "ktlint:standard:chain-method-continuation",
    "ktlint:standard:annotation",
    "ktlint:standard:max-line-length",
    "ktlint:standard:no-semi",
    "ktlint:standard:statement-wrapping",
    "MaxLineLength",
    "TooManyFunctions",
    "FunctionParameterNaming",
    "LongParameterList",
    "CyclomaticComplexMethod",
    "LongMethod",
    "MagicNumber",
    "NestedBlockDepth",
    "ReturnCount",
    "UnusedParameter",
)

package io.xberg.literllm.android

/**
 * Audio content part for speech-capable models.
 *
 * No `deny_unknown_fields`: shared with the response side (see
 * `AssistantPart.OutputAudio`), same rationale as `ImageUrl` (#51).
 */
@com.fasterxml.jackson.annotation.JsonIgnoreProperties(ignoreUnknown = true)
data class AudioContent(
    /** Base64-encoded audio data. */
    val data: String = "",
    /** Audio format (e.g., "wav", "mp3", "ogg"). */
    val format: String = "",
)
