// Generated by alef. Do not edit by hand.
// alef:hash:330a26c849c8847e74cbb4f9eff80d8ac8aee8cf7aa7f0eace05a370fe3ad0de
@file:Suppress(
    "ktlint:standard:trailing-comma-on-call-site",
    "ktlint:standard:trailing-comma-on-declaration-site",
    "ktlint:standard:spacing-between-declarations-with-comments",
    "ktlint:standard:spacing-between-declarations-with-annotations",
    "ktlint:standard:when-entry-bracing",
    "ktlint:standard:blank-line-between-when-conditions",
    "ktlint:standard:blank-line-before-declaration",
    "ktlint:standard:chain-method-continuation",
    "ktlint:standard:annotation",
    "ktlint:standard:max-line-length",
    "ktlint:standard:no-semi",
    "ktlint:standard:statement-wrapping",
    "MaxLineLength",
    "TooManyFunctions",
    "FunctionParameterNaming",
    "LongParameterList",
    "CyclomaticComplexMethod",
    "LongMethod",
    "MagicNumber",
    "NestedBlockDepth",
    "ReturnCount",
    "UnusedParameter",
)

package io.xberg.literllm.android

/** Request to upload a file. */
data class CreateFileRequest(
    /** Base64-encoded file data. */
    val file: String = "",
    /** Purpose for the file. */
    val purpose: FilePurpose = FilePurpose.ASSISTANTS,
    /** Optional filename to associate with the upload. */
    val filename: String? = null,
)
