// Generated by alef. Do not edit by hand.
// alef:hash:cf12a91b71f7e7e78174f6741902a20de61b1e89a6a7b79a92a43f7c017e8379
@file:Suppress(
    "ktlint:standard:trailing-comma-on-call-site",
    "ktlint:standard:trailing-comma-on-declaration-site",
    "ktlint:standard:spacing-between-declarations-with-comments",
    "ktlint:standard:spacing-between-declarations-with-annotations",
    "ktlint:standard:when-entry-bracing",
    "ktlint:standard:blank-line-between-when-conditions",
    "ktlint:standard:blank-line-before-declaration",
    "ktlint:standard:chain-method-continuation",
    "ktlint:standard:annotation",
    "ktlint:standard:max-line-length",
    "ktlint:standard:no-semi",
    "ktlint:standard:statement-wrapping",
    "MaxLineLength",
    "TooManyFunctions",
    "FunctionParameterNaming",
    "LongParameterList",
    "CyclomaticComplexMethod",
    "LongMethod",
    "MagicNumber",
    "NestedBlockDepth",
    "ReturnCount",
    "UnusedParameter",
)

package io.xberg.literllm.android

/** Configuration for registering a custom LLM provider at runtime. */
data class CustomProviderConfig(
    /** Unique name for this provider (e.g., "my-provider"). */
    val name: String,
    /** Base URL for the provider's API (e.g., `<https://api.my-provider.com/v1>`). */
    val baseUrl: String,
    /** Authentication header format. */
    val authHeader: AuthHeaderFormat,
    /** Model name prefixes that route to this provider (e.g., `["my-"]`). */
    val modelPrefixes: List<String> = emptyList(),
)
