// Generated by alef. Do not edit by hand.
// alef:hash:938b8ffd93c3e30d74875f875188c728addee9d4b80a97a7ac22716b3154c7c5
@file:Suppress(
    "ktlint:standard:trailing-comma-on-call-site",
    "ktlint:standard:trailing-comma-on-declaration-site",
    "ktlint:standard:spacing-between-declarations-with-comments",
    "ktlint:standard:spacing-between-declarations-with-annotations",
    "ktlint:standard:when-entry-bracing",
    "ktlint:standard:blank-line-between-when-conditions",
    "ktlint:standard:blank-line-before-declaration",
    "ktlint:standard:chain-method-continuation",
    "ktlint:standard:annotation",
    "ktlint:standard:max-line-length",
    "ktlint:standard:no-semi",
    "ktlint:standard:statement-wrapping",
    "MaxLineLength",
    "TooManyFunctions",
    "FunctionParameterNaming",
    "LongParameterList",
    "CyclomaticComplexMethod",
    "LongMethod",
    "MagicNumber",
    "NestedBlockDepth",
    "ReturnCount",
    "UnusedParameter",
)

package io.xberg.literllm.android

/** Embedding response. */
data class EmbeddingResponse(
    /**
     * Always `"list"` from OpenAI-compatible APIs.  Stored as a plain
     * `String` so non-standard provider values do not break deserialization.
     */
    val `object`: String,
    /** List of embeddings. */
    val data: List<EmbeddingObject> = emptyList(),
    /** Model used to generate embeddings. */
    val model: String,
    /** Token usage (input tokens only; embeddings have zero output tokens). */
    val usage: Usage? = null,
)
