// Generated by alef. Do not edit by hand.
// alef:hash:d37ea66d954ad374b69c65cfd4aa370951e0c0c095fdc72c3a3f39389871d474
@file:Suppress(
    "ktlint:standard:trailing-comma-on-call-site",
    "ktlint:standard:trailing-comma-on-declaration-site",
    "ktlint:standard:spacing-between-declarations-with-comments",
    "ktlint:standard:spacing-between-declarations-with-annotations",
    "ktlint:standard:when-entry-bracing",
    "ktlint:standard:blank-line-between-when-conditions",
    "ktlint:standard:blank-line-before-declaration",
    "ktlint:standard:chain-method-continuation",
    "ktlint:standard:annotation",
    "ktlint:standard:max-line-length",
    "ktlint:standard:no-semi",
    "ktlint:standard:statement-wrapping",
    "MaxLineLength",
    "TooManyFunctions",
    "FunctionParameterNaming",
    "LongParameterList",
    "CyclomaticComplexMethod",
    "LongMethod",
    "MagicNumber",
    "NestedBlockDepth",
    "ReturnCount",
    "UnusedParameter",
)

package io.xberg.literllm.android

/** The result of a single health probe. */
enum class HealthStatus {
    /** The probe succeeded; the upstream is reachable. */
    @com.fasterxml.jackson.annotation.JsonProperty("Healthy") HEALTHY,
    /** The probe failed; the upstream may be down. */
    @com.fasterxml.jackson.annotation.JsonProperty("Unhealthy") UNHEALTHY;

    @com.fasterxml.jackson.annotation.JsonValue
    fun toWire(): String =
        when (this) {
            HEALTHY -> "Healthy"
            UNHEALTHY -> "Unhealthy"
        }

    companion object {
        @com.fasterxml.jackson.annotation.JsonCreator
        @JvmStatic
        fun fromWire(value: String): HealthStatus =
            when (value) {
                "Healthy",
                "healthy" -> HEALTHY
                "Unhealthy",
                "unhealthy" -> UNHEALTHY
                else -> throw IllegalArgumentException("Unknown HealthStatus value: $value")
            }
    }
}
