// Generated by alef. Do not edit by hand.
// alef:hash:16c1ff7f65e94f48b8349150c4a96e0202740621f73d2103360cfa0cbbabab1c
@file:Suppress(
    "ktlint:standard:trailing-comma-on-call-site",
    "ktlint:standard:trailing-comma-on-declaration-site",
    "ktlint:standard:spacing-between-declarations-with-comments",
    "ktlint:standard:spacing-between-declarations-with-annotations",
    "ktlint:standard:when-entry-bracing",
    "ktlint:standard:blank-line-between-when-conditions",
    "ktlint:standard:blank-line-before-declaration",
    "ktlint:standard:chain-method-continuation",
    "ktlint:standard:annotation",
    "ktlint:standard:max-line-length",
    "ktlint:standard:no-semi",
    "ktlint:standard:statement-wrapping",
    "MaxLineLength",
    "TooManyFunctions",
    "FunctionParameterNaming",
    "LongParameterList",
    "CyclomaticComplexMethod",
    "LongMethod",
    "MagicNumber",
    "NestedBlockDepth",
    "ReturnCount",
    "UnusedParameter",
)

package io.xberg.literllm.android

/**
 * An image URL reference with optional detail level for processing.
 *
 * No `deny_unknown_fields`: this type is shared with the response side
 * (see `AssistantPart.OutputImage`) where it is deserialized from
 * provider output, not just constructed as request input (see #51). A
 * provider adding a new field to its image-output object must not hard-fail
 * the whole response.
 */
data class ImageUrl(
    /** URL of the image (data URI or HTTP/HTTPS URL). */
    val url: String = "",
    /** Detail level: low (512x512), high (2x2 tiles), or auto (model-selected). */
    val detail: ImageDetail? = null,
)
