// Generated by alef. Do not edit by hand.
// alef:hash:c6ba1b45539f434159b186410a022d3ba3c8a55bd896d1c79cf067b0bc7b14bc
@file:Suppress(
    "ktlint:standard:trailing-comma-on-call-site",
    "ktlint:standard:trailing-comma-on-declaration-site",
    "ktlint:standard:spacing-between-declarations-with-comments",
    "ktlint:standard:spacing-between-declarations-with-annotations",
    "ktlint:standard:when-entry-bracing",
    "ktlint:standard:blank-line-between-when-conditions",
    "ktlint:standard:blank-line-before-declaration",
    "ktlint:standard:chain-method-continuation",
    "ktlint:standard:annotation",
    "ktlint:standard:max-line-length",
    "ktlint:standard:no-semi",
    "ktlint:standard:statement-wrapping",
    "MaxLineLength",
    "TooManyFunctions",
    "FunctionParameterNaming",
    "LongParameterList",
    "CyclomaticComplexMethod",
    "LongMethod",
    "MagicNumber",
    "NestedBlockDepth",
    "ReturnCount",
    "UnusedParameter",
)

package io.xberg.literllm.android

/** An intent prototype: `(intent_name, prototype_embedding, target_model_id)`. */
data class IntentPrototype(
    /** Human-readable name for the intent (used in logs/metrics). */
    val name: String,
    /** Pre-computed embedding vector for this intent. */
    val embedding: List<Double> = emptyList(),
    /** Model to route to when this intent is detected. */
    val model: String,
)
