// Generated by alef. Do not edit by hand.
// alef:hash:8e6e2e1ccfcf78ca6f406eca26303b92800b2fb07e178f58fc59ba5d65c51cc7

package io.xberg.literllm.android

class LiterLlmBridgeException(message: String?, cause: Throwable?) : RuntimeException(message, cause) {
    constructor(message: String?) : this(message, null)
}
