// Generated by alef. Do not edit by hand.
// alef:hash:cf12a91b71f7e7e78174f6741902a20de61b1e89a6a7b79a92a43f7c017e8379

package io.xberg.literllm.android

class LiterLlmBridgeException(message: String?, cause: Throwable?) : RuntimeException(message, cause) {
    constructor(message: String?) : this(message, null)
}
