// Generated by alef. Do not edit by hand.
// alef:hash:69ad76ca87d13b7db10dd64f78297968958fa58fe886d8d54ada5a967892b41d
@file:Suppress(
    "ktlint:standard:trailing-comma-on-call-site",
    "ktlint:standard:trailing-comma-on-declaration-site",
    "ktlint:standard:spacing-between-declarations-with-comments",
    "ktlint:standard:spacing-between-declarations-with-annotations",
    "ktlint:standard:when-entry-bracing",
    "ktlint:standard:blank-line-between-when-conditions",
    "ktlint:standard:blank-line-before-declaration",
    "ktlint:standard:chain-method-continuation",
    "ktlint:standard:annotation",
    "ktlint:standard:max-line-length",
    "ktlint:standard:no-semi",
    "ktlint:standard:statement-wrapping",
    "MaxLineLength",
    "TooManyFunctions",
    "FunctionParameterNaming",
    "LongParameterList",
    "CyclomaticComplexMethod",
    "LongMethod",
    "MagicNumber",
    "NestedBlockDepth",
    "ReturnCount",
    "UnusedParameter",
)

package io.xberg.literllm.android

/** Request to classify content for policy violations. */
data class ModerationRequest(
    /** Text or texts to check. */
    @field:com.fasterxml.jackson.databind.annotation.JsonSerialize(`as` = ModerationInput::class)
    val input: ModerationInput,
    /** Model ID (e.g., `"text-moderation-latest"`). Optional; API uses default if unset. */
    val model: String? = null,
)
