// Generated by alef. Do not edit by hand.
// alef:hash:c05bf78df4f55b00ba5849887087a9f620d53bad1968c7456ee4879a7527bbea
@file:Suppress(
    "ktlint:standard:trailing-comma-on-call-site",
    "ktlint:standard:trailing-comma-on-declaration-site",
    "ktlint:standard:spacing-between-declarations-with-comments",
    "ktlint:standard:spacing-between-declarations-with-annotations",
    "ktlint:standard:when-entry-bracing",
    "ktlint:standard:blank-line-between-when-conditions",
    "ktlint:standard:blank-line-before-declaration",
    "ktlint:standard:chain-method-continuation",
    "ktlint:standard:annotation",
    "ktlint:standard:max-line-length",
    "ktlint:standard:no-semi",
    "ktlint:standard:statement-wrapping",
    "MaxLineLength",
    "TooManyFunctions",
    "FunctionParameterNaming",
    "LongParameterList",
    "CyclomaticComplexMethod",
    "LongMethod",
    "MagicNumber",
    "NestedBlockDepth",
    "ReturnCount",
    "UnusedParameter",
)

package io.xberg.literllm.android

/** Document input for OCR — either a URL or inline base64 data. */
@com.fasterxml.jackson.annotation.JsonTypeInfo(use = com.fasterxml.jackson.annotation.JsonTypeInfo.Id.NAME, property = "type", visible = false)
@com.fasterxml.jackson.annotation.JsonSubTypes(
    com.fasterxml.jackson.annotation.JsonSubTypes.Type(value = OcrDocument.Url::class, name = "document_url"),
    com.fasterxml.jackson.annotation.JsonSubTypes.Type(value = OcrDocument.Base64::class, name = "base64")
)
@com.fasterxml.jackson.annotation.JsonIgnoreProperties(ignoreUnknown = true)
sealed class OcrDocument {
    /** A publicly accessible document URL. */
    data class Url(val url: String) : OcrDocument()
    /** Inline base64-encoded document data. */
    data class Base64(val data: String, val mediaType: String) : OcrDocument()
}
