// Generated by alef. Do not edit by hand.
// alef:hash:21ff119e3ef4c35fc331b35b91c94a71c0787d3e50a6e8724070b0e8717cc142
@file:Suppress(
    "ktlint:standard:trailing-comma-on-call-site",
    "ktlint:standard:trailing-comma-on-declaration-site",
    "ktlint:standard:spacing-between-declarations-with-comments",
    "ktlint:standard:spacing-between-declarations-with-annotations",
    "ktlint:standard:when-entry-bracing",
    "ktlint:standard:blank-line-between-when-conditions",
    "ktlint:standard:blank-line-before-declaration",
    "ktlint:standard:chain-method-continuation",
    "ktlint:standard:annotation",
    "ktlint:standard:max-line-length",
    "ktlint:standard:no-semi",
    "ktlint:standard:statement-wrapping",
    "MaxLineLength",
    "TooManyFunctions",
    "FunctionParameterNaming",
    "LongParameterList",
    "CyclomaticComplexMethod",
    "LongMethod",
    "MagicNumber",
    "NestedBlockDepth",
    "ReturnCount",
    "UnusedParameter",
)

package io.xberg.literllm.android

/** Token usage for a response. */
data class ResponseUsage(
    /** Input tokens used. */
    val inputTokens: Long = 0L,
    /** Output tokens used. */
    val outputTokens: Long = 0L,
    /** Total tokens used. */
    val totalTokens: Long = 0L,
)
