// Generated by alef. Do not edit by hand.
// alef:hash:938b8ffd93c3e30d74875f875188c728addee9d4b80a97a7ac22716b3154c7c5
@file:Suppress(
    "ktlint:standard:trailing-comma-on-call-site",
    "ktlint:standard:trailing-comma-on-declaration-site",
    "ktlint:standard:spacing-between-declarations-with-comments",
    "ktlint:standard:spacing-between-declarations-with-annotations",
    "ktlint:standard:when-entry-bracing",
    "ktlint:standard:blank-line-between-when-conditions",
    "ktlint:standard:blank-line-before-declaration",
    "ktlint:standard:chain-method-continuation",
    "ktlint:standard:annotation",
    "ktlint:standard:max-line-length",
    "ktlint:standard:no-semi",
    "ktlint:standard:statement-wrapping",
    "MaxLineLength",
    "TooManyFunctions",
    "FunctionParameterNaming",
    "LongParameterList",
    "CyclomaticComplexMethod",
    "LongMethod",
    "MagicNumber",
    "NestedBlockDepth",
    "ReturnCount",
    "UnusedParameter",
)

package io.xberg.literllm.android

/** Tool execution result returned to the model. */
data class ToolMessage(
    /**
     * Result of the tool execution as plain text or an array of content parts
     * (text, images, documents, audio), mirroring `UserMessage.content`.
     *
     * `#[serde(untagged)]` on `UserContent` means a bare JSON string still
     * deserialises into `Text`, so tool results persisted before this field
     * carried structured content continue to round-trip.
     */
    @field:com.fasterxml.jackson.databind.annotation.JsonSerialize(`as` = UserContent::class)
    val content: UserContent,
    /** ID of the tool call this result responds to. */
    val toolCallId: String = "",
    /** Optional tool/function name. */
    val name: String? = null,
)
