// Generated by alef. Do not edit by hand.
// alef:hash:c9998b654c9ad625bc9fcc73e0553687b18acd71b87ae29abab75cb13e11ebb8
@file:Suppress(
    "ktlint:standard:trailing-comma-on-call-site",
    "ktlint:standard:trailing-comma-on-declaration-site",
    "ktlint:standard:spacing-between-declarations-with-comments",
    "ktlint:standard:spacing-between-declarations-with-annotations",
    "ktlint:standard:when-entry-bracing",
    "ktlint:standard:blank-line-between-when-conditions",
    "ktlint:standard:blank-line-before-declaration",
    "ktlint:standard:chain-method-continuation",
    "ktlint:standard:annotation",
    "ktlint:standard:max-line-length",
    "ktlint:standard:no-semi",
    "ktlint:standard:statement-wrapping",
    "MaxLineLength",
    "TooManyFunctions",
    "FunctionParameterNaming",
    "LongParameterList",
    "CyclomaticComplexMethod",
    "LongMethod",
    "MagicNumber",
    "NestedBlockDepth",
    "ReturnCount",
    "UnusedParameter",
)

package io.xberg.literllm.android

/** Response from a transcription request. */
@com.fasterxml.jackson.annotation.JsonIgnoreProperties(ignoreUnknown = true)
data class TranscriptionResponse(
    /** The transcribed text. */
    val text: String = "",
    /** Detected language (ISO-639-1 code). */
    val language: String? = null,
    /** Total audio duration in seconds. */
    val duration: Double? = null,
    /** Detailed segment-level transcription (if response_format is "verbose_json"). */
    val segments: List<TranscriptionSegment>? = null,
)
