<?php
// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:b8db5933805d34add57c2602cc79567cfbf8a5ff8293800ddb6cf9fce694af24
// To regenerate: alef generate
// To verify freshness: alef verify


declare(strict_types=1);

namespace Liter\Llm\E2e;

use PHPUnit\Framework\TestCase;
use Liter\Llm\LiterLlm;
use Liter\Llm\ChatCompletionRequest;

/** E2e tests for category: custom_provider. */
final class CustomProviderTest extends TestCase
{


    /** Tests custom provider with custom auth header */
    public function test_provider_auth(): void
    {
        $client = \Liter\Llm\LiterLlm::createClient('test-key', getenv('MOCK_SERVER_URL') . '/fixtures/provider_auth');
        $request = \Liter\Llm\ChatCompletionRequest::from_json(json_encode(["messages" => [["content" => "Hello", "role" => "user"]], "model" => "my-auth-model-v1"]));
        $result = $client->chat($request);

        $this->assertNotNull($result);


    }


    /** Tests that a custom provider can be registered and routes requests */
    public function test_register_provider(): void
    {
        $client = \Liter\Llm\LiterLlm::createClient('test-key', getenv('MOCK_SERVER_URL') . '/fixtures/register_provider');
        $request = \Liter\Llm\ChatCompletionRequest::from_json(json_encode(["messages" => [["content" => "Hello", "role" => "user"]], "model" => "my-model-v1"]));
        $result = $client->chat($request);

        $this->assertNotNull($result);


    }

}
