// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:c249c70b7640c53f754d8c96cd8e49cec28afa7f81e8f316163a5ff7df9c9773
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
//! E2e tests for category: parity

use liter_llm::chat;
mod mock_server;
use mock_server::{MockRoute, MockServer};

#[tokio::test]
async fn test_api_surface_parity() {
    // Canonical API surface definition for cross-binding parity verification
    let mock_route = MockRoute {
        path: "/v1/chat/completions",
        method: "POST",
        status: 200,
        body: r#"{}"#.to_string(),
        stream_chunks: vec![],
    };
    let mock_server = MockServer::start(vec![mock_route]).await;
    let request_json = serde_json::json!(null);
    let request = serde_json::from_value(request_json).unwrap();
    let _ = chat(&request).await;
}

