// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:d7a93cb2cc2cde7c8d213a0b6d73a86d219c7a1bd8ac8f7957765aca1526e747
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
//! E2e tests for category: parity

use liter_llm::chat;
mod mock_server;
use mock_server::{MockRoute, MockServer};

#[tokio::test]
async fn test_api_surface_parity() {
    // Canonical API surface definition for cross-binding parity verification
    let mock_route = MockRoute {
        path: "/v1/chat/completions",
        method: "POST",
        status: 200,
        body: r#"{}"#.to_string(),
        stream_chunks: vec![],
    };
    let mock_server = MockServer::start(vec![mock_route]).await;
    let request_json = serde_json::json!(null);
    let request = serde_json::from_value(request_json).unwrap();
    let _ = chat(&request).await;
}
