<?php
// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:88ed56d1791ef2f707cf66e4101c56ef4bce59e4a2fadb272431a5eac99f78db
// To regenerate: alef generate
// To verify freshness: alef verify


declare(strict_types=1);

namespace Liter\Llm\E2e;

use PHPUnit\Framework\TestCase;
use Liter\Llm\LiterLlm;
use Liter\Llm\SearchRequest;

/** E2e tests for category: search. */
final class SearchTest extends TestCase
{

    /** Basic web search request with a simple query */
    public function test_search_basic(): void
    {
        $client = \Liter\Llm\LiterLlm::createClient('test-key', getenv('MOCK_SERVER_URL') . '/fixtures/search_basic');
        $request = \Liter\Llm\SearchRequest::from_json(json_encode(["model" => "brave/web-search", "query" => "What is Rust programming language?"]));
        $result = $client->search($request);

        $this->assertNotNull($result);


    }


    /** Web search with a query that returns no results */
    public function test_search_empty_results(): void
    {
        $client = \Liter\Llm\LiterLlm::createClient('test-key', getenv('MOCK_SERVER_URL') . '/fixtures/search_empty_results');
        $request = \Liter\Llm\SearchRequest::from_json(json_encode(["model" => "brave/web-search", "query" => "xyznonexistent12345xyz"]));
        $result = $client->search($request);

        $this->assertNotNull($result);


    }


    /** 400 Bad Request error when search query is empty */
    public function test_search_error_400(): void
    {
        $client = \Liter\Llm\LiterLlm::createClient('test-key', getenv('MOCK_SERVER_URL') . '/fixtures/search_error_400');
        try {
            $request = \Liter\Llm\SearchRequest::from_json(json_encode(["model" => "brave/web-search", "query" => ""]));
            $client->search($request);
            $this->fail('Expected an exception to be thrown');
        } catch (\Exception $e) {
            $this->assertTrue(preg_match('/BadRequest/', $e->getMessage()) === 1 || preg_match('/BadRequest/', get_class($e)) === 1, 'expected exception message or class name to match BadRequest');
        }
        // skipped: assertion type 'equals' has no accessor for error field error.status_code in this backend
    }


    /** 401 Unauthorized error on web search due to invalid API credentials */
    public function test_search_error_401(): void
    {
        $client = \Liter\Llm\LiterLlm::createClient('test-key', getenv('MOCK_SERVER_URL') . '/fixtures/search_error_401');
        try {
            $request = \Liter\Llm\SearchRequest::from_json(json_encode(["model" => "brave/web-search", "query" => "test"]));
            $client->search($request);
            $this->fail('Expected an exception to be thrown');
        } catch (\Exception $e) {
            $this->assertTrue(preg_match('/Authentication/', $e->getMessage()) === 1 || preg_match('/Authentication/', get_class($e)) === 1, 'expected exception message or class name to match Authentication');
        }
        // skipped: assertion type 'equals' has no accessor for error field error.status_code in this backend
    }


    /** Search request with max_results parameter limiting response count */
    public function test_search_with_max_results(): void
    {
        $client = \Liter\Llm\LiterLlm::createClient('test-key', getenv('MOCK_SERVER_URL') . '/fixtures/search_with_max_results');
        $request = \Liter\Llm\SearchRequest::from_json(json_encode(["maxResults" => 2, "model" => "brave/web-search", "query" => "Rust programming"]));
        $result = $client->search($request);

            $this->assertCount(2, $result->getResults());


    }

}
