// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:872f238d87e53196bf0612a2399cce53ed37b69e19c0bf1e94b4e196c7fbd128
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// swift-format-ignore-file

import XCTest
import Foundation
#if canImport(FoundationNetworking)
import FoundationNetworking
#endif
import LiterLlm
import RustBridge

/// E2e tests for category: custom_provider.
final class CustomProviderTests: XCTestCase {
    override class func setUp() {
        super.setUp()
    }

    func testProviderAuth() async throws {
        // Tests custom provider with custom auth header
        let _request = try LiterLlm.chatCompletionRequestFromJson("{\"messages\":[{\"content\":\"Hello\",\"role\":\"user\"}],\"model\":\"my-auth-model-v1\"}")
        let _client = try createClient(apiKey: "test-key", baseUrl: AlefE2EMockServer.baseURL + "/fixtures/provider_auth")
        let result = try await _client.chat(_request)
    }

    func testRegisterProvider() async throws {
        // Tests that a custom provider can be registered and routes requests
        let _request = try LiterLlm.chatCompletionRequestFromJson("{\"messages\":[{\"content\":\"Hello\",\"role\":\"user\"}],\"model\":\"my-model-v1\"}")
        let _client = try createClient(apiKey: "test-key", baseUrl: AlefE2EMockServer.baseURL + "/fixtures/register_provider")
        let result = try await _client.chat(_request)
    }

}
