// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:6bc5f75166c48706d7e1ec4752c514e262bbb408cf87d2d7a35a7212226e014e
// To regenerate: alef generate
// To verify freshness: alef verify
// swift-format-ignore-file

import XCTest
import Foundation
#if canImport(FoundationNetworking)
import FoundationNetworking
#endif
import LiterLlm
import RustBridge

/// E2e tests for category: ocr.
final class OcrTests: XCTestCase {
    override class func setUp() {
        super.setUp()
    }

    func testOcrError400() async throws {
        // 400 Bad Request error when OCR input has an invalid image format
        do {
            let _request = try LiterLlm.ocrRequestFromJson("{\"document\":{\"type\":\"document_url\",\"url\":\"invalid://url\"},\"model\":\"mistral/mistral-ocr-latest\"}")
            let _client = try createClient(apiKey: "test-key", baseUrl: AlefE2EMockServer.baseURL + "/fixtures/ocr_error_400")
            _ = try await _client.ocr(_request)
            XCTFail("expected to throw")
        } catch {
            let _errorMessage = String(describing: error)
            let _errorType = String(describing: type(of: error))
            XCTAssertTrue(_errorMessage.contains("BadRequest") || _errorType.contains("BadRequest"), "expected error to mention \"BadRequest\", got message: \(_errorMessage), type: \(_errorType)")
        }
        // skipped: assertion type 'equals' has no accessor for error field error.status_code in this backend
    }

    func testOcrError401() async throws {
        // 401 Unauthorized error on OCR request due to invalid API credentials
        do {
            let _request = try LiterLlm.ocrRequestFromJson("{\"document\":{\"type\":\"document_url\",\"url\":\"https://example.com/doc.pdf\"},\"model\":\"mistral/mistral-ocr-latest\"}")
            let _client = try createClient(apiKey: "test-key", baseUrl: AlefE2EMockServer.baseURL + "/fixtures/ocr_error_401")
            _ = try await _client.ocr(_request)
            XCTFail("expected to throw")
        } catch {
            let _errorMessage = String(describing: error)
            let _errorType = String(describing: type(of: error))
            XCTAssertTrue(_errorMessage.contains("Authentication") || _errorType.contains("Authentication"), "expected error to mention \"Authentication\", got message: \(_errorMessage), type: \(_errorType)")
        }
        // skipped: assertion type 'equals' has no accessor for error field error.status_code in this backend
    }

    func testOcrMultiPage() async throws {
        // OCR request returning multiple pages of document content
        let _request = try LiterLlm.ocrRequestFromJson("{\"document\":{\"type\":\"document_url\",\"url\":\"https://example.com/multipage.pdf\"},\"model\":\"mistral/mistral-ocr-latest\"}")
        let _client = try createClient(apiKey: "test-key", baseUrl: AlefE2EMockServer.baseURL + "/fixtures/ocr_multi_page")
        let result = try await _client.ocr(_request)
        XCTAssertNotNil(result)
        XCTAssertEqual(result.pages.count, 2)
        XCTAssertEqual(result.pages[0].index, 0)
        XCTAssertEqual(result.pages[1].index, 1)
    }

    func testOcrUrlDocument() async throws {
        // OCR request with a document URL input
        let _request = try LiterLlm.ocrRequestFromJson("{\"document\":{\"type\":\"document_url\",\"url\":\"https://example.com/doc.pdf\"},\"model\":\"mistral/mistral-ocr-latest\"}")
        let _client = try createClient(apiKey: "test-key", baseUrl: AlefE2EMockServer.baseURL + "/fixtures/ocr_url_document")
        let result = try await _client.ocr(_request)
        XCTAssertNotNil(result)
    }

}
