// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:f60c4001987b49ec4105e90cd2b5912e987cdaf063f072048d207ac4912fde05
fn main() {
    let crate_dir = std::env::var("CARGO_MANIFEST_DIR").unwrap();
    cbindgen::generate(crate_dir)
        .expect("Unable to generate C bindings")
        .write_to_file("include/liter_llm.h");
}
