# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:59cac5c166131b797b3063f3b19ba8b8f8a0d1a100f0b2a219f1455f5ab63f85
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# frozen_string_literal: true

module LiterLlm
  ## The version string for this package.
  VERSION = "1.12.1"
end
