# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:411a53e0a6391e6c985b9a64835e74befd11f23866286b6af7b4a52465879ed0
# To regenerate: alef generate
# To verify freshness: alef verify
# frozen_string_literal: true

module LiterLlm
  ## The version string for this package.
  VERSION = "1.18.0"
end
