# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:255ad57888389e715408840023ca11140a5ae7727059c28a47c9d9f68b90bdf4
# To regenerate: alef generate
# To verify freshness: alef verify
# frozen_string_literal: true

module LiterLlm
  ## The version string for this package.
  VERSION = "2.1.0"
end
