# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:c1cde3c6942e25641d13e37f1cd8821ef81209c83553014c9a2faf131ce5f4ab
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
# frozen_string_literal: true

module Liter_llm
  VERSION = '1.4.0.pre.rc.10'
end
