# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:4f558201459e040308000efd8e068f1d399acf4286831535c70faad41bc2d06c
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
# E2e tests for category: types

test_that("all_message_types: Request with all message role types (system, user, assistant, tool) to verify round-trip serialization", {
  result <- chat()
  expect_equal(length(result$choices), 1)
  expect_equal(trimws(result$choices[["0"]]$finish_reason), "stop")
})

test_that("multimodal_content: User message with mixed text and image_url content parts to verify multimodal serialization", {
  result <- chat()
  expect_equal(length(result$choices), 1)
  expect_equal(trimws(result$choices[["0"]]$finish_reason), "stop")
})
