// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:a1989c3dfb77377970d88272370ba76653a7c87963705fabadca288653ab7055
#nullable enable

using System;

namespace LiterLlm;

/// <summary>
/// `status` preserves the exact HTTP status code received (401 or 403).
/// </summary>
public class AuthenticationException : LiterLlmErrorException
{
    public AuthenticationException(string message) : base(message) { }

    public AuthenticationException(string message, Exception innerException) : base(message, innerException) { }
}
