// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:7bacb53ba62128cddbad2af9594a8f7a0d67daee3cb1a21a2569382109274fca
#nullable enable

using System;

namespace LiterLlm;

/// <summary>
/// `status` preserves the exact HTTP status code received (401 or 403).
/// </summary>
public class AuthenticationException : LiterLlmErrorException
{
    public AuthenticationException(string message) : base(message) { }

    public AuthenticationException(string message, Exception innerException) : base(message, innerException) { }
}
