// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:9ca6714382d5977ba89edd2f09addf092370c00e33d03fa288491e783ed5cc74
#nullable enable

using System;

namespace LiterLlm;

/// <summary>
/// `status` preserves the exact HTTP status code received (400, 405, 413, 422, …).
/// </summary>
public class BadRequestException : LiterLlmErrorException
{
    public BadRequestException(string message) : base(message) { }

    public BadRequestException(string message, Exception innerException) : base(message, innerException) { }
}
