// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:08c41f5c62ca562289e71f634aceb51e35245585ce7b878b7bc1fe3a75443f48
#nullable enable

using System;

namespace LiterLlm;

/// <summary>
/// `status` preserves the exact HTTP status code received (400, 405, 413, 422, …).
/// </summary>
public class BadRequestException : LiterLlmErrorException
{
    public BadRequestException(string message) : base(message) { }

    public BadRequestException(string message, Exception innerException) : base(message, innerException) { }
}
