// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:b713cdc932d78474deb27590f90844c3f463beda3e2e590d8bc6c93bf009eea8
#nullable enable

using System;

namespace LiterLlm;

public class BudgetExceededException : LiterLlmErrorException
{
    public BudgetExceededException(string message) : base(message) { }

    public BudgetExceededException(string message, Exception innerException) : base(message, innerException) { }
}
