// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:af2e930dd5f1ea8082e6923b4b4ab7a696d5f10cdcd211245d63f0a9ba75aa39
#nullable enable

using System;

namespace LiterLlm;

public class BudgetExceededException : LiterLlmErrorException
{
    public BudgetExceededException(string message) : base(message) { }

    public BudgetExceededException(string message, Exception innerException) : base(message, innerException) { }
}
