// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:41ce3ae7aa4d7cab7cd4ef51a250d4d5fbadc2b002978d65e0abe0ec9c43bf50
#nullable enable

using System;

namespace LiterLlm;

/// <summary>
/// A cache file **read** failed on an otherwise-fresh cache file. Cache
/// **write** failures are best-effort and never surface as this error
/// (see `refresh_catalog`).
/// </summary>
public class CacheException : CatalogRefreshErrorException
{
    public CacheException(string message) : base(message) { }

    public CacheException(string message, Exception innerException) : base(message, innerException) { }
}
