// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:872f238d87e53196bf0612a2399cce53ed37b69e19c0bf1e94b4e196c7fbd128
#nullable enable

using System;

namespace LiterLlm;

/// <summary>
/// A cache file **read** failed on an otherwise-fresh cache file. Cache
/// **write** failures are best-effort and never surface as this error
/// (see `refresh_catalog`).
/// </summary>
public class CacheException : CatalogRefreshErrorException
{
    public CacheException(string message) : base(message) { }

    public CacheException(string message, Exception innerException) : base(message, innerException) { }
}
