// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:d0f34698145baf2dba9374fabdcc0f24c47c986f56b7355836fec81af538910f
#nullable enable

using System;

namespace LiterLlm;

/// <summary>
/// A cache file **read** failed on an otherwise-fresh cache file. Cache
/// **write** failures are best-effort and never surface as this error
/// (see `refresh_catalog`).
/// </summary>
public class CacheException : CatalogRefreshErrorException
{
    public CacheException(string message) : base(message) { }

    public CacheException(string message, Exception innerException) : base(message, innerException) { }
}
