// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:645d8ff0f3a0ef7684f9b9ea4ce1ae251a78a2a3481ecdeabf7643c53d644bb0
#nullable enable

using System;

namespace LiterLlm;

/// <summary>
/// Errors from `refresh_catalog` and `install_catalog_overlay_from_str`.
///
/// On every variant, the overlay registry is left untouched: a previously
/// installed overlay (or the embedded catalog, if none was ever installed)
/// remains active. This is the air-gap-safety contract — a failed refresh
/// never degrades pricing/model-info availability.
/// </summary>
public class CatalogRefreshErrorException : LiterLlmException
{
    public CatalogRefreshErrorException(string message) : base(message) { }

    public CatalogRefreshErrorException(string message, Exception innerException) : base(message, innerException) { }
}
