// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:7bacb53ba62128cddbad2af9594a8f7a0d67daee3cb1a21a2569382109274fca
#nullable enable

using System;

namespace LiterLlm;

/// <summary>
/// Errors from `refresh_catalog` and `install_catalog_overlay_from_str`.
///
/// On every variant, the overlay registry is left untouched: a previously
/// installed overlay (or the embedded catalog, if none was ever installed)
/// remains active. This is the air-gap-safety contract — a failed refresh
/// never degrades pricing/model-info availability.
/// </summary>
public class CatalogRefreshErrorException : LiterLlmException
{
    public CatalogRefreshErrorException(string message) : base(message) { }

    public CatalogRefreshErrorException(string message, Exception innerException) : base(message, innerException) { }
}
