// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:fc3f2c28b71bc4ef4fc08e9298500509a8c157dd3600b5ca2652ed7019fe685c
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace LiterLlm;

public sealed class ChatCompletionTool
{
    [JsonPropertyName("tool_type")]
    public ToolType ToolType { get; set; } = default!;

    [JsonPropertyName("function")]
    public FunctionDefinition Function { get; set; } = default!;

}
