// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:e6f55e06d29921d1307f0e64f2cfacef9ca2245960b6a20c95559040f4024eb2
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace LiterLlm;

public sealed class ChatCompletionTool
{
    [JsonPropertyName("tool_type")]
    public ToolType ToolType { get; set; } = default!;

    [JsonPropertyName("function")]
    public FunctionDefinition Function { get; set; } = default!;

}
