// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:476a49d2fb526fa01d37ade6eb9f5696922fa128ada3903e9bdc40ff7739c819
using System;

namespace LiterLlm;

public class ContentPolicyException : LiterLlmErrorException
{
    public ContentPolicyException(string message) : base(message) { }

    public ContentPolicyException(string message, Exception innerException) : base(message, innerException) { }
}
