// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:110770591e9122ab1265eb1e141100b834af1b2c3ec0f143897f612e1943b511
#nullable enable

using System;

namespace LiterLlm;

public class ContextWindowExceededException : LiterLlmErrorException
{
    public ContextWindowExceededException(string message) : base(message) { }

    public ContextWindowExceededException(string message, Exception innerException) : base(message, innerException) { }
}
