// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:17b46ae14d0c3f2460feccb93a7f75b8ae873b5ef996d1d4cc8fd9d58a0d979e
#nullable enable

using System;

namespace LiterLlm;

public class ContextWindowExceededException : LiterLlmErrorException
{
    public ContextWindowExceededException(string message) : base(message) { }

    public ContextWindowExceededException(string message, Exception innerException) : base(message, innerException) { }
}
