// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:7499d97bdecec9ba068f9bf13fdaad6528c82e061c3755d3ae2763715948c3dd
#nullable enable

using System;

namespace LiterLlm;

public class ContentPolicyException : LiterLlmErrorException
{
    public ContentPolicyException(string message) : base(message) { }

    public ContentPolicyException(string message, Exception innerException) : base(message, innerException) { }
}
