// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:3788251e46d2cdc0b8f2a6ae60b7727956f49ad15a860178a9b1d31a1594466f
#nullable enable

using System;

namespace LiterLlm;

public class ContentPolicyException : LiterLlmErrorException
{
    public ContentPolicyException(string message) : base(message) { }

    public ContentPolicyException(string message, Exception innerException) : base(message, innerException) { }
}
