// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:c249c70b7640c53f754d8c96cd8e49cec28afa7f81e8f316163a5ff7df9c9773
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace LiterLlm;

/// <summary>
/// Request to transcribe audio into text.
/// </summary>
public sealed class CreateTranscriptionRequest
{
    [JsonPropertyName("model")]
    public string Model { get; set; } = "";

    /// <summary>
    /// Base64-encoded audio file data.
    /// </summary>
    [JsonPropertyName("file")]
    public string File { get; set; } = "";

    [JsonPropertyName("language")]
    public string? Language { get; set; } = null;

    [JsonPropertyName("prompt")]
    public string? Prompt { get; set; } = null;

    [JsonPropertyName("response_format")]
    public string? ResponseFormat { get; set; } = null;

    [JsonPropertyName("temperature")]
    public double? Temperature { get; set; } = null;

}
