// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:bd145e742a21772db2e5529557175c042badee2c5a5fe35cdc0eada4bb515531
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace LiterLlm;

/// <summary>
/// Request to transcribe audio into text.
/// </summary>
public sealed class CreateTranscriptionRequest
{
    [JsonPropertyName("model")]
    public string Model { get; set; } = "";

    /// <summary>
    /// Base64-encoded audio file data.
    /// </summary>
    [JsonPropertyName("file")]
    public string File { get; set; } = "";

    [JsonPropertyName("language")]
    public string? Language { get; set; } = null;

    [JsonPropertyName("prompt")]
    public string? Prompt { get; set; } = null;

    [JsonPropertyName("response_format")]
    public string? ResponseFormat { get; set; } = null;

    [JsonPropertyName("temperature")]
    public double? Temperature { get; set; } = null;

}
