// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:f37544be62f6c843a6f8231ad5dfef44b211cd75016ee0f4176a2779f16824f7
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace LiterLlm;

/// <summary>
/// Request to generate speech audio from text.
/// </summary>
public sealed class CreateSpeechRequest
{
    [JsonPropertyName("model")]
    public string Model { get; set; } = "";

    [JsonPropertyName("input")]
    public string Input { get; set; } = "";

    [JsonPropertyName("voice")]
    public string Voice { get; set; } = "";

    [JsonPropertyName("response_format")]
    public string? ResponseFormat { get; set; } = null;

    [JsonPropertyName("speed")]
    public double? Speed { get; set; } = null;

}
