// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:73516780160260b48f0f858446476f02c4d37d19c77500de1a053109f5d49a60
#nullable enable

using System;

namespace LiterLlm;

/// <summary>
/// Runtime catalog refresh was not enabled. `refresh_catalog` itself
/// never returns this — it returns `Ok(``RefreshOutcome.Disabled``)`
/// instead — but the variant is part of the public error surface for
/// callers that want to treat "disabled" as a hard error.
/// </summary>
public class DisabledException : CatalogRefreshErrorException
{
    public DisabledException(string message) : base(message) { }

    public DisabledException(string message, Exception innerException) : base(message, innerException) { }
}
