// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:8cff9f496d6e774719e0a5c19bdaa5d2ec14091a4e5f47099da9e43341590040
#nullable enable

using System;

namespace LiterLlm;

/// <summary>
/// Runtime catalog refresh was not enabled. `refresh_catalog` itself
/// never returns this — it returns `Ok(``RefreshOutcome.Disabled``)`
/// instead — but the variant is part of the public error surface for
/// callers that want to treat "disabled" as a hard error.
/// </summary>
public class DisabledException : CatalogRefreshErrorException
{
    public DisabledException(string message) : base(message) { }

    public DisabledException(string message, Exception innerException) : base(message, innerException) { }
}
