// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:cf12a91b71f7e7e78174f6741902a20de61b1e89a6a7b79a92a43f7c017e8379
#nullable enable

using System;

namespace LiterLlm;

/// <summary>
/// Runtime catalog refresh was not enabled. `refresh_catalog` itself
/// never returns this — it returns `Ok(``RefreshOutcome.Disabled``)`
/// instead — but the variant is part of the public error surface for
/// callers that want to treat "disabled" as a hard error.
/// </summary>
public class DisabledException : CatalogRefreshErrorException
{
    public DisabledException(string message) : base(message) { }

    public DisabledException(string message, Exception innerException) : base(message, innerException) { }
}
