// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:dd71c6438681799da6c7e06d0648fefb995f72c5d12d093f9af5bb1d7a22a970
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace LiterLlm;

public sealed class EmbeddingObject
{
    /// <summary>
    /// Always `"embedding"` from OpenAI-compatible APIs.  Stored as a plain
    /// `String` so non-standard provider values do not break deserialization.
    /// </summary>
    [JsonPropertyName("object")]
    public string Object { get; set; } = "";

    [JsonPropertyName("embedding")]
    public List<double> Embedding { get; set; } = [];

    [JsonPropertyName("index")]
    public uint Index { get; set; } = 0;

}
