// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:8a76ecb12af603c2b4cb697132a0608945ccfb89191235db3f9f5df616892858
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace LiterLlm;

public sealed class EmbeddingResponse
{
    /// <summary>
    /// Always `"list"` from OpenAI-compatible APIs.  Stored as a plain
    /// `String` so non-standard provider values do not break deserialization.
    /// </summary>
    [JsonPropertyName("object")]
    public string Object { get; set; } = "";

    [JsonPropertyName("data")]
    public List<EmbeddingObject> Data { get; set; } = [];

    [JsonPropertyName("model")]
    public string Model { get; set; } = "";

    [JsonPropertyName("usage")]
    public Usage? Usage { get; set; } = null;

}
