// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:262494263f9a4918c2de7843fa328387411babc1707d783eba0b02b9bc2d5955
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace LiterLlm;

public sealed class EmbeddingObject
{
    /// <summary>
    /// Always `"embedding"` from OpenAI-compatible APIs.  Stored as a plain
    /// `String` so non-standard provider values do not break deserialization.
    /// </summary>
    [JsonPropertyName("object")]
    public string Object { get; set; } = "";

    [JsonPropertyName("embedding")]
    public List<double> Embedding { get; set; } = [];

    [JsonPropertyName("index")]
    public uint Index { get; set; } = 0;

}
