// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:67f341f87f3a8bf3600621d332b546b896f669d36bce493bfa82cda37d6f1f46
#nullable enable

using System;

namespace LiterLlm;

public class EndpointNotSupportedException : LiterLlmErrorException
{
    public EndpointNotSupportedException(string message) : base(message) { }

    public EndpointNotSupportedException(string message, Exception innerException) : base(message, innerException) { }
}
