// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:051d699f7e4f0a31e27b09b4e6f6e2f794da4486f0c7aae35dc4f3a2489f02dc
#nullable enable

using System;

namespace LiterLlm;

/// <summary>
/// The network fetch failed, timed out, or returned a non-success
/// status.
/// </summary>
public class FetchException : CatalogRefreshErrorException
{
    public FetchException(string message) : base(message) { }

    public FetchException(string message, Exception innerException) : base(message, innerException) { }
}
