// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:872f238d87e53196bf0612a2399cce53ed37b69e19c0bf1e94b4e196c7fbd128
#nullable enable

using System;

namespace LiterLlm;

/// <summary>
/// The network fetch failed, timed out, or returned a non-success
/// status.
/// </summary>
public class FetchException : CatalogRefreshErrorException
{
    public FetchException(string message) : base(message) { }

    public FetchException(string message, Exception innerException) : base(message, innerException) { }
}
