// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:f2e892bb58aa4fb9ab33315fa7270cfc1daa7ab2b354c09932e2a57d656e7fba
#nullable enable

using System;

namespace LiterLlm;

/// <summary>
/// The network fetch failed, timed out, or returned a non-success
/// status.
/// </summary>
public class FetchException : CatalogRefreshErrorException
{
    public FetchException(string message) : base(message) { }

    public FetchException(string message, Exception innerException) : base(message, innerException) { }
}
