// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:938b8ffd93c3e30d74875f875188c728addee9d4b80a97a7ac22716b3154c7c5
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace LiterLlm;

/// <summary>
/// Function definition exposed to the model.
/// </summary>
public sealed record FunctionDefinition
{
    /// <summary>
    /// Name of the function. Required and must be alphanumeric + underscores.
    /// </summary>
    [JsonPropertyName("name")]
    public required string Name { get; init; }

    /// <summary>
    /// Human-readable description explaining what the function does.
    /// </summary>
    [JsonPropertyName("description")]
    public string? Description { get; init; } = null;

    /// <summary>
    /// JSON Schema defining the function's parameters.
    /// </summary>
    [JsonPropertyName("parameters")]
    public JsonElement? Parameters { get; init; } = null;

    /// <summary>
    /// If true, enforce strict JSON schema validation for arguments.
    /// </summary>
    [JsonPropertyName("strict")]
    public bool? Strict { get; init; } = null;


    /// <summary>
    /// Parse a <see cref="FunctionDefinition"/> from a JSON string.
    /// </summary>
    /// <exception cref="LiterLlmException">When the JSON cannot be deserialised.</exception>
    public static FunctionDefinition FromJson(string json)
    {
        try
        {
            return JsonSerializer.Deserialize<FunctionDefinition>(json, JsonOptions)
                ?? throw new LiterLlmException($"Failed to parse FunctionDefinition from JSON: deserializer returned null");
        }
        catch (LiterLlmException)
        {
            throw;
        }
        catch (Exception e)
        {
            throw new LiterLlmException($"Failed to parse FunctionDefinition from JSON: {e.Message}", e);
        }
    }

    private static readonly JsonSerializerOptions JsonOptions = new()
    {
        DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingDefault,
        Converters = { new JsonStringEnumConverter(JsonNamingPolicy.SnakeCaseLower), new ByteArrayJsonConverter() },
    };

    /// <summary>Options for serializing config/input objects to FFI. Strips nulls
    /// (nullable C# fields default to null and would override required Rust fields with
    /// non-deserialisable nulls) but preserves explicit false/0 so caller intent is kept.</summary>
    private static readonly JsonSerializerOptions JsonSerializationOptions = new()
    {
        DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull,
        Converters = { new JsonStringEnumConverter(JsonNamingPolicy.SnakeCaseLower), new ByteArrayJsonConverter() },
    };
}
