// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:885837a284c9902247332d91e0b8f05bedc6baa5d05563369a14aa3765157966
#nullable enable

using System;

namespace LiterLlm;

public class HookRejectedException : LiterLlmErrorException
{
    public HookRejectedException(string message) : base(message) { }

    public HookRejectedException(string message, Exception innerException) : base(message, innerException) { }
}
