// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:645d8ff0f3a0ef7684f9b9ea4ce1ae251a78a2a3481ecdeabf7643c53d644bb0
#nullable enable

using System;

namespace LiterLlm;

/// <summary>
/// The same `Idempotency-Key` is already in-flight (another request with the
/// same key is currently being processed).
///
/// The caller should wait briefly and retry.  The response is not yet
/// available, and this request has been short-circuited to avoid running
/// the operation twice.
///
/// HTTP equivalent: 409 Conflict (retryable after a brief delay).
/// </summary>
public class IdempotencyInFlightException : LiterLlmErrorException
{
    public IdempotencyInFlightException(string message) : base(message) { }

    public IdempotencyInFlightException(string message, Exception innerException) : base(message, innerException) { }
}
