// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:1f145372d78e119eb635fddc12f518375d8f9211040ba103dad64a428a688336
#nullable enable

using System;

namespace LiterLlm;

/// <summary>
/// An internal logic error (e.g. unexpected Tower response variant).
///
/// This should never surface in normal operation — if it does, it
/// indicates a bug in the library.
/// </summary>
public class InternalErrorException : LiterLlmErrorException
{
    public InternalErrorException(string message) : base(message) { }

    public InternalErrorException(string message, Exception innerException) : base(message, innerException) { }
}
