// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:59cac5c166131b797b3063f3b19ba8b8f8a0d1a100f0b2a219f1455f5ab63f85
#nullable enable

using System;

namespace LiterLlm;

/// <summary>
/// An internal logic error (e.g. unexpected Tower response variant).
///
/// This should never surface in normal operation — if it does, it
/// indicates a bug in the library.
/// </summary>
public class InternalErrorException : LiterLlmErrorException
{
    public InternalErrorException(string message) : base(message) { }

    public InternalErrorException(string message, Exception innerException) : base(message, innerException) { }
}
