// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:7e97a72dac447e465d4569f3e7c5e7776480d15cf0b9cddf07fbb43b822d5976
#nullable enable

using System;

namespace LiterLlm;

/// <summary>
/// An internal logic error (e.g. unexpected Tower response variant).
///
/// This should never surface in normal operation — if it does, it
/// indicates a bug in the library.
/// </summary>
public class InternalErrorException : LiterLlmErrorException
{
    public InternalErrorException(string message) : base(message) { }

    public InternalErrorException(string message, Exception innerException) : base(message, innerException) { }
}
