// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:26f6a450b040e4e7f511f9807cc0efc0d0a35b6c7f1fd52e92c8eded49efd34e
#nullable enable

using System;

namespace LiterLlm;

public class InvalidHeaderException : LiterLlmErrorException
{
    public InvalidHeaderException(string message) : base(message) { }

    public InvalidHeaderException(string message, Exception innerException) : base(message, innerException) { }
}
