// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:9c479751c0805b45ce76a17491cc7b1b4c87a95d35e5ac93b5d5d0ac4b974284
#nullable enable

using System;

namespace LiterLlm;

public class InvalidHeaderException : LiterLlmErrorException
{
    public InvalidHeaderException(string message) : base(message) { }

    public InvalidHeaderException(string message, Exception innerException) : base(message, innerException) { }
}
