// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:ae60e8ebfe80b1a675089672792d3ecd6f38b50b92571b91c7aa7d93255ea389
#nullable enable

using System;

namespace LiterLlm;

public class InvalidHeaderException : LiterLlmErrorException
{
    public InvalidHeaderException(string message) : base(message) { }

    public InvalidHeaderException(string message, Exception innerException) : base(message, innerException) { }
}
