// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:08c41f5c62ca562289e71f634aceb51e35245585ce7b878b7bc1fe3a75443f48
#nullable enable

using System;

namespace LiterLlm;

public class LiterLlmException : Exception
{
    public int Code { get; }

    public LiterLlmException(int code, string message) : base(message)
    {
        Code = code;
    }

    public LiterLlmException(string message) : base(message)
    {
        Code = 0;
    }

    public LiterLlmException(string message, Exception innerException) : base(message, innerException)
    {
        Code = 0;
    }
}
