// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:9ca6714382d5977ba89edd2f09addf092370c00e33d03fa288491e783ed5cc74
#nullable enable

using System;

namespace LiterLlm;

public class LiterLlmException : Exception
{
    public int Code { get; }

    public LiterLlmException(int code, string message) : base(message)
    {
        Code = code;
    }

    public LiterLlmException(string message) : base(message)
    {
        Code = 0;
    }

    public LiterLlmException(string message, Exception innerException) : base(message, innerException)
    {
        Code = 0;
    }
}
