// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:938b8ffd93c3e30d74875f875188c728addee9d4b80a97a7ac22716b3154c7c5
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace LiterLlm;

/// <summary>
/// Response cache configuration.
/// </summary>
public sealed record LlmCacheConfig
{
    /// <summary>
    /// Maximum number of cached entries.
    /// </summary>
    [JsonPropertyName("max_entries")]
    public ulong? MaxEntries { get; init; } = null;

    /// <summary>
    /// Cache entry time-to-live, in seconds.
    /// </summary>
    [JsonPropertyName("ttl_seconds")]
    public ulong? TtlSeconds { get; init; } = null;

    /// <summary>
    /// Cache backend name (e.g. `"memory"`, or an `opendal` scheme).
    /// </summary>
    [JsonPropertyName("backend")]
    public string? Backend { get; init; } = null;

    /// <summary>
    /// Backend-specific configuration key/value pairs.
    /// </summary>
    [JsonPropertyName("backend_config")]
    public Dictionary<string, string>? BackendConfig { get; init; } = null;


    /// <summary>
    /// Parse a <see cref="LlmCacheConfig"/> from a JSON string.
    /// </summary>
    /// <exception cref="LiterLlmException">When the JSON cannot be deserialised.</exception>
    public static LlmCacheConfig FromJson(string json)
    {
        try
        {
            return JsonSerializer.Deserialize<LlmCacheConfig>(json, JsonOptions)
                ?? throw new LiterLlmException($"Failed to parse LlmCacheConfig from JSON: deserializer returned null");
        }
        catch (LiterLlmException)
        {
            throw;
        }
        catch (Exception e)
        {
            throw new LiterLlmException($"Failed to parse LlmCacheConfig from JSON: {e.Message}", e);
        }
    }

    private static readonly JsonSerializerOptions JsonOptions = new()
    {
        DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingDefault,
        Converters = { new JsonStringEnumConverter(JsonNamingPolicy.SnakeCaseLower), new ByteArrayJsonConverter() },
    };

    /// <summary>Options for serializing config/input objects to FFI. Strips nulls
    /// (nullable C# fields default to null and would override required Rust fields with
    /// non-deserialisable nulls) but preserves explicit false/0 so caller intent is kept.</summary>
    private static readonly JsonSerializerOptions JsonSerializationOptions = new()
    {
        DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull,
        Converters = { new JsonStringEnumConverter(JsonNamingPolicy.SnakeCaseLower), new ByteArrayJsonConverter() },
    };
}
