// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:eb15bcc3b373618f5522a196e3cfb78732574f9e735c0d946c79d9516685c358
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace LiterLlm;

public sealed class ModelsListResponse
{
    /// <summary>
    /// Always `"list"` from OpenAI-compatible APIs.  Stored as a plain
    /// `String` so non-standard provider values do not break deserialization.
    /// </summary>
    [JsonPropertyName("object")]
    public string Object { get; set; } = "";

    [JsonPropertyName("data")]
    public List<ModelObject> Data { get; set; } = [];

}
