// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:60df726a605a971acc9910c7bd13389a2102178322d3211294a50d9609b83de8
#nullable enable

using System;

namespace LiterLlm;

public class NotFoundException : LiterLlmErrorException
{
    public NotFoundException(string message) : base(message) { }

    public NotFoundException(string message, Exception innerException) : base(message, innerException) { }
}
