// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:c6e5f72020619891b8f88bbab9903a69943e472fdf7af981fc45430e44dbee1d
#nullable enable

using System;

namespace LiterLlm;

public class NotFoundException : LiterLlmErrorException
{
    public NotFoundException(string message) : base(message) { }

    public NotFoundException(string message, Exception innerException) : base(message, innerException) { }
}
