// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:b9605808b18426bceca67f4229a0e3761ba1f1d8b2cac196ff49853eb10d3343
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace LiterLlm;

/// <summary>
/// An image extracted from an OCR page.
/// </summary>
public sealed class OcrImage
{
    /// <summary>
    /// Unique image identifier.
    /// </summary>
    [JsonPropertyName("id")]
    public string Id { get; set; } = "";

    /// <summary>
    /// Base64-encoded image data.
    /// </summary>
    [JsonPropertyName("image_base64")]
    public string? ImageBase64 { get; set; } = null;

}
