// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:872f238d87e53196bf0612a2399cce53ed37b69e19c0bf1e94b4e196c7fbd128
#nullable enable

using System;

namespace LiterLlm;

/// <summary>
/// An outbound request was blocked by the active `OutboundPolicy`.
///
/// Returned when `register_custom_provider` is called with a `base_url` that
/// violates the policy (e.g. a private-range IP under `DenyPrivate`), or when
/// the per-connection DNS resolver detects a forbidden address at connect time.
/// </summary>
public class OutboundForbiddenException : LiterLlmErrorException
{
    public OutboundForbiddenException(string message) : base(message) { }

    public OutboundForbiddenException(string message, Exception innerException) : base(message, innerException) { }
}
