// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:8e9f34c6a462d306504c8e5ec980d04d7140e848d2f6a4fafd5df83d147df330
#nullable enable

using System;

namespace LiterLlm;

/// <summary>
/// An outbound request was blocked by the active `OutboundPolicy`.
///
/// Returned when `register_custom_provider` is called with a `base_url` that
/// violates the policy (e.g. a private-range IP under `DenyPrivate`), or when
/// the per-connection DNS resolver detects a forbidden address at connect time.
/// </summary>
public class OutboundForbiddenException : LiterLlmErrorException
{
    public OutboundForbiddenException(string message) : base(message) { }

    public OutboundForbiddenException(string message, Exception innerException) : base(message, innerException) { }
}
