// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:b713cdc932d78474deb27590f90844c3f463beda3e2e590d8bc6c93bf009eea8
#nullable enable

using System;

namespace LiterLlm;

/// <summary>
/// An outbound request was blocked by the active `OutboundPolicy`.
///
/// Returned when `register_custom_provider` is called with a `base_url` that
/// violates the policy (e.g. a private-range IP under `DenyPrivate`), or when
/// the per-connection DNS resolver detects a forbidden address at connect time.
/// </summary>
public class OutboundForbiddenException : LiterLlmErrorException
{
    public OutboundForbiddenException(string message) : base(message) { }

    public OutboundForbiddenException(string message, Exception innerException) : base(message, innerException) { }
}
