// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:9c479751c0805b45ce76a17491cc7b1b4c87a95d35e5ac93b5d5d0ac4b974284
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace LiterLlm;

/// <summary>
/// Page dimensions in pixels.
/// </summary>
public sealed record PageDimensions
{
    /// <summary>
    /// Width in pixels.
    /// </summary>
    [JsonPropertyName("width")]
    public uint Width { get; init; } = 0;

    /// <summary>
    /// Height in pixels.
    /// </summary>
    [JsonPropertyName("height")]
    public uint Height { get; init; } = 0;


    /// <summary>
    /// Parse a <see cref="PageDimensions"/> from a JSON string.
    /// </summary>
    /// <exception cref="LiterLlmException">When the JSON cannot be deserialised.</exception>
    public static PageDimensions FromJson(string json)
    {
        try
        {
            return JsonSerializer.Deserialize<PageDimensions>(json, JsonOptions)
                ?? throw new LiterLlmException($"Failed to parse PageDimensions from JSON: deserializer returned null");
        }
        catch (LiterLlmException)
        {
            throw;
        }
        catch (Exception e)
        {
            throw new LiterLlmException($"Failed to parse PageDimensions from JSON: {e.Message}", e);
        }
    }

    private static readonly JsonSerializerOptions JsonOptions = new()
    {
        DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingDefault,
        Converters = { new JsonStringEnumConverter(JsonNamingPolicy.SnakeCaseLower), new ByteArrayJsonConverter() },
    };

    /// <summary>Options for serializing config/input objects to FFI. Strips nulls
    /// (nullable C# fields default to null and would override required Rust fields with
    /// non-deserialisable nulls) but preserves explicit false/0 so caller intent is kept.</summary>
    private static readonly JsonSerializerOptions JsonSerializationOptions = new()
    {
        DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull,
        Converters = { new JsonStringEnumConverter(JsonNamingPolicy.SnakeCaseLower), new ByteArrayJsonConverter() },
    };
}
