// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:834c14768421283eb05294f12a2897bef15ffcd2a6abe13d962fae5d428f3608
#nullable enable

using System;

namespace LiterLlm;

/// <summary>
/// The fetched or cached catalog JSON failed to parse.
/// </summary>
public class ParseException : CatalogRefreshErrorException
{
    public ParseException(string message) : base(message) { }

    public ParseException(string message, Exception innerException) : base(message, innerException) { }
}
