// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:3d2f3fb25af36f4eff046c940c7a4b54a22cf7d008868055e62ae05932df703f
#nullable enable

using System;

namespace LiterLlm;

/// <summary>
/// The fetched or cached catalog JSON failed to parse.
/// </summary>
public class ParseException : CatalogRefreshErrorException
{
    public ParseException(string message) : base(message) { }

    public ParseException(string message, Exception innerException) : base(message, innerException) { }
}
