// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:73516780160260b48f0f858446476f02c4d37d19c77500de1a053109f5d49a60
#nullable enable

using System;

namespace LiterLlm;

/// <summary>
/// The fetched or cached catalog JSON failed to parse.
/// </summary>
public class ParseException : CatalogRefreshErrorException
{
    public ParseException(string message) : base(message) { }

    public ParseException(string message, Exception innerException) : base(message, innerException) { }
}
