// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:1f788778ebf153f725b0eabff5c40f48a1d1995fe8e15c4138e9f45f679474e1
#nullable enable

using System;

namespace LiterLlm;

public class RateLimitedException : LiterLlmErrorException
{
    public RateLimitedException(string message) : base(message) { }

    public RateLimitedException(string message, Exception innerException) : base(message, innerException) { }
}
