// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:a3a4f8b843f1b1b4345b77b16ce0a84eb70c092f94c822d8d0ddbf2c18bb5653
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace LiterLlm;

/// <summary>
/// Controls how much reasoning effort the model should use.
/// </summary>
public enum ReasoningEffort
{
    [JsonPropertyName("low")]
    Low,
    [JsonPropertyName("medium")]
    Medium,
    [JsonPropertyName("high")]
    High,
}
