// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:985d33c22488c5c427e5fac74932e96cb709867748da4672cb5db41f5cdf9af0
#nullable enable

using System;

namespace LiterLlm;

public class SerializationException : LiterLlmErrorException
{
    public SerializationException(string message) : base(message) { }

    public SerializationException(string message, Exception innerException) : base(message, innerException) { }
}
