// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:7f093d3c5ea97974dac2cae635a02dd55aa0e30b5c7c298b297a76df29f7bef0
#nullable enable

using System;

namespace LiterLlm;

public class SerializationException : LiterLlmErrorException
{
    public SerializationException(string message) : base(message) { }

    public SerializationException(string message, Exception innerException) : base(message, innerException) { }
}
