// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:59cac5c166131b797b3063f3b19ba8b8f8a0d1a100f0b2a219f1455f5ab63f85
#nullable enable

using System;

namespace LiterLlm;

/// <summary>
/// `status` preserves the exact HTTP status code received (502, 503, or 504).
/// </summary>
public class ServiceUnavailableException : LiterLlmErrorException
{
    public ServiceUnavailableException(string message) : base(message) { }

    public ServiceUnavailableException(string message, Exception innerException) : base(message, innerException) { }
}
