// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:8399ecc51bf56a2987c0956fdd3b27e9aa8466b723d196c7a1e329b8ad9ab64a
#nullable enable

using System;

namespace LiterLlm;

/// <summary>
/// `status` preserves the exact HTTP status code received (502, 503, or 504).
/// </summary>
public class ServiceUnavailableException : LiterLlmErrorException
{
    public ServiceUnavailableException(string message) : base(message) { }

    public ServiceUnavailableException(string message, Exception innerException) : base(message, innerException) { }
}
