// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:af7468ada2cd9571058cc95cc9883fc5ba83e0daaefa883551b310ba55f8dd2b
#nullable enable

using System;

namespace LiterLlm;

/// <summary>
/// `status` preserves the exact HTTP status code received (500, or other 5xx not covered
/// by `ServiceUnavailable`).
/// </summary>
public class ServerErrorException : LiterLlmErrorException
{
    public ServerErrorException(string message) : base(message) { }

    public ServerErrorException(string message, Exception innerException) : base(message, innerException) { }
}
