// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:00329a365cfaafc12afcd7f96db6f1542f28899a4c905a654857c2eede77dd43
#nullable enable

using System;

namespace LiterLlm;

/// <summary>
/// `status` preserves the exact HTTP status code received (502, 503, or 504).
/// </summary>
public class ServiceUnavailableException : LiterLlmErrorException
{
    public ServiceUnavailableException(string message) : base(message) { }

    public ServiceUnavailableException(string message, Exception innerException) : base(message, innerException) { }
}
