// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:73516780160260b48f0f858446476f02c4d37d19c77500de1a053109f5d49a60
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace LiterLlm;

/// <summary>
/// Directive to call a specific tool.
/// </summary>
public sealed record SpecificToolChoice
{
    /// <summary>
    /// Tool type (always "function").
    /// </summary>
    [JsonConverter(typeof(ToolTypeJsonConverter))]
    [JsonPropertyName("type")]
    public ToolType? ChoiceType { get; init; } = null;

    /// <summary>
    /// The specific function to invoke.
    /// </summary>
    [JsonPropertyName("function")]
    public SpecificFunction Function { get; init; } = default!;


    /// <summary>
    /// Parse a <see cref="SpecificToolChoice"/> from a JSON string.
    /// </summary>
    /// <exception cref="LiterLlmException">When the JSON cannot be deserialised.</exception>
    public static SpecificToolChoice FromJson(string json)
    {
        try
        {
            return JsonSerializer.Deserialize<SpecificToolChoice>(json, JsonOptions)
                ?? throw new LiterLlmException($"Failed to parse SpecificToolChoice from JSON: deserializer returned null");
        }
        catch (LiterLlmException)
        {
            throw;
        }
        catch (Exception e)
        {
            throw new LiterLlmException($"Failed to parse SpecificToolChoice from JSON: {e.Message}", e);
        }
    }

    private static readonly JsonSerializerOptions JsonOptions = new()
    {
        DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingDefault,
        Converters = { new JsonStringEnumConverter(JsonNamingPolicy.SnakeCaseLower), new ByteArrayJsonConverter() },
    };

    /// <summary>Options for serializing config/input objects to FFI. Strips nulls
    /// (nullable C# fields default to null and would override required Rust fields with
    /// non-deserialisable nulls) but preserves explicit false/0 so caller intent is kept.</summary>
    private static readonly JsonSerializerOptions JsonSerializationOptions = new()
    {
        DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull,
        Converters = { new JsonStringEnumConverter(JsonNamingPolicy.SnakeCaseLower), new ByteArrayJsonConverter() },
    };
}
