// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:b017c73272330dca1434bccf9b9d592f41e12b9563193b68c0d8c825e28e80cf
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace LiterLlm;

public sealed class SpecificFunction
{
    [JsonPropertyName("name")]
    public string Name { get; set; } = "";

}
