// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:f2bb02f64c72ee7f009f1c1e598ccc01ca2f773c723b43e6f5eee60c815e81f1
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace LiterLlm;

public sealed class SpecificFunction
{
    [JsonPropertyName("name")]
    public string Name { get; set; } = "";

}
