// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:af2ade45b24a79dc77f438cf232130828a1fcc63057a78952e1f02748a4788e1
#nullable enable

using System;

namespace LiterLlm;

public class TimeoutException : LiterLlmErrorException
{
    public TimeoutException(string message) : base(message) { }

    public TimeoutException(string message, Exception innerException) : base(message, innerException) { }
}
