// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:6ff387a09b3a40cd3f44d0f5d401b3af18910fa7f0195a707024fffbb55cb352
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace LiterLlm;

public enum ToolChoice
{
    [JsonPropertyName("mode")]
    Mode,
    [JsonPropertyName("specific")]
    Specific,
}
