// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:2f4810bbcbb834252900f4b3e12a1e43292f4880b36cfef2e1c9ed3f50f7a9c0
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System.Text.Json.Serialization;

using System;
using System.Text.Json;

namespace LiterLlm;

/// <summary>
/// The type discriminator for tool/tool-call objects.
///
/// Per the OpenAI spec this is always `"function"`. Using an enum enforces
/// that constraint at the type level and rejects any other value on
/// deserialization.
/// </summary>
public enum ToolType
{
    [JsonPropertyName("function")]
    Function,
}
