// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:d3049a2295f9549e181a927737953537db89d71f1eaf3b7bc0f0af409c749526
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace LiterLlm;

/// <summary>
/// The type discriminator for tool/tool-call objects.
///
/// Per the OpenAI spec this is always `"function"`. Using an enum enforces
/// that constraint at the type level and rejects any other value on
/// deserialization.
/// </summary>
public enum ToolType
{
    [JsonPropertyName("function")]
    Function,
}
