// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:9b344c22686b2f6ed524fa27b2b3744c33a646d11dfc96366ef575831c3589a0
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace LiterLlm;

public sealed class Usage
{
    /// <summary>
    /// Prompt tokens used. Defaults to 0 when absent (some providers omit this).
    /// </summary>
    [JsonPropertyName("prompt_tokens")]
    public ulong PromptTokens { get; set; } = 0;

    /// <summary>
    /// Completion tokens used. Defaults to 0 when absent (e.g. embedding responses).
    /// </summary>
    [JsonPropertyName("completion_tokens")]
    public ulong CompletionTokens { get; set; } = 0;

    /// <summary>
    /// Total tokens used. Defaults to 0 when absent (some providers omit this).
    /// </summary>
    [JsonPropertyName("total_tokens")]
    public ulong TotalTokens { get; set; } = 0;

}
