// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:7141ef573c065059f78cc04dbe723a463e9600b80de3fad6ebeeef2c0504f54d
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System.Text.Json.Serialization;

using System;
using System.Text.Json;

namespace LiterLlm;

public enum UserContent
{
    [JsonPropertyName("text")]
    Text,
    [JsonPropertyName("parts")]
    Parts,
}
