// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:225854012e02ced512480b0e9d88db6cffa109d7d3afa6756f640d0ec42b2f25
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
const std = @import("std");
const testing = std.testing;
const liter_llm = @import("liter_llm");

// E2e tests for category: types

test "all_message_types" {
    // Request with all message role types (system, user, assistant, tool) to verify round-trip serialization
    var gpa = std.heap.GeneralPurposeAllocator(.{}){}
    defer _ = gpa.deinit();
    const allocator = gpa.allocator();

    const result = liter_llm.chat(null);
    try testing.expectEqual(1, result.choices.len);
    try testing.expectEqual("stop", result.choices.get("0").finish_reason);
}

test "multimodal_content" {
    // User message with mixed text and image_url content parts to verify multimodal serialization
    var gpa = std.heap.GeneralPurposeAllocator(.{}){}
    defer _ = gpa.deinit();
    const allocator = gpa.allocator();

    const result = liter_llm.chat(null);
    try testing.expectEqual(1, result.choices.len);
    try testing.expectEqual("stop", result.choices.get("0").finish_reason);
}

