// Generated by alef — intentionally empty.
// alef:hash:af7468ada2cd9571058cc95cc9883fc5ba83e0daaefa883551b310ba55f8dd2b
// Streaming-adapter owner handles are declared canonically (once) in the
// Rust extern blocks, so swift-bridge synthesizes their class triple and
// `$_free` destructor directly; no hand-rolled class hierarchy is needed.

import Foundation
import RustBridgeC
