// Generated by alef — intentionally empty.
// alef:hash:f7883672aaee862773a0e106a675a216939c8a442664e7ba867a846dc825d306
// Streaming-adapter owner handles are declared canonically (once) in the
// Rust extern blocks, so swift-bridge synthesizes their class triple and
// `$_free` destructor directly; no hand-rolled class hierarchy is needed.

import Foundation
import RustBridgeC
