// Generated by alef — intentionally empty.
// alef:hash:d37ea66d954ad374b69c65cfd4aa370951e0c0c095fdc72c3a3f39389871d474
// Streaming-adapter owner handles are declared canonically (once) in the
// Rust extern blocks, so swift-bridge synthesizes their class triple and
// `$_free` destructor directly; no hand-rolled class hierarchy is needed.

import Foundation
import RustBridgeC
