# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:34d70e683205062dfb3f1a320dc8fd208b6f90d9c49aa9d254e495915ee82e40
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
"""E2e tests for category: types."""

import pytest
from liter_llm import chat


@pytest.mark.asyncio
async def test_all_message_types() -> None:
    """Request with all message role types (system, user, assistant, tool) to verify round-trip serialization."""
    request = None
    result = await chat(request=request)
    assert len(result.choices) == 1  # noqa: S101
    assert result.choices.get("0").finish_reason.strip() == "stop"  # noqa: S101


@pytest.mark.asyncio
async def test_multimodal_content() -> None:
    """User message with mixed text and image_url content parts to verify multimodal serialization."""
    request = None
    result = await chat(request=request)
    assert len(result.choices) == 1  # noqa: S101
    assert result.choices.get("0").finish_reason.strip() == "stop"  # noqa: S101
