# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:cea66e61d5cb34a4ca6c606f41dab4e78d4937b29a777dd9dc74924a345c3525
# To regenerate: alef generate
# To verify freshness: alef verify

"""E2e tests for category: transcribe."""

import os
import pytest  # noqa: F401
from liter_llm import create_client
from liter_llm._internal_bindings import CreateTranscriptionRequest


@pytest.mark.asyncio

async def test_edge_transcribe_empty_audio() -> None:
    """Transcription of a silent or empty audio file returns empty text."""
    client = create_client(api_key="test-key", base_url=os.environ["MOCK_SERVER_URL"] + "/fixtures/edge_transcribe_empty_audio")
    request = CreateTranscriptionRequest.from_json("{\"file\":\"silence.mp3\",\"model\":\"whisper-1\"}")

    result = await client.transcribe(request)
    assert "" in result.text  # noqa: S101


@pytest.mark.asyncio

async def test_edge_transcribe_with_timestamps() -> None:
    """Transcription with verbose JSON response format including timestamp segments."""
    client = create_client(api_key="test-key", base_url=os.environ["MOCK_SERVER_URL"] + "/fixtures/edge_transcribe_with_timestamps")
    request = CreateTranscriptionRequest.from_json("{\"file\":\"audio.mp3\",\"model\":\"whisper-1\",\"response_format\":\"verbose_json\"}")

    result = await client.transcribe(request)
    assert result.text is not None and (not hasattr(result.text, "__len__") or len(result.text) > 0)  # noqa: S101
    assert len(result.segments) == 3  # noqa: S101
    assert result.segments[0].id == 0  # noqa: S101


@pytest.mark.asyncio

async def test_error_transcribe_auth_401() -> None:
    """401 Unauthorized for transcription with invalid API key."""
    # skipped: assertion type 'equals' has no accessor for error field error.status_code in this backend
    with pytest.raises(Exception) as exc_info:  # noqa: B017
        client = create_client(api_key="test-key", base_url=os.environ["MOCK_SERVER_URL"] + "/fixtures/error_transcribe_auth_401")
        request = CreateTranscriptionRequest.from_json("{\"file\":\"audio.mp3\",\"model\":\"whisper-1\"}")
        await client.transcribe(request)
    assert "Authentication" in str(exc_info.value) or "Authentication" in type(exc_info.value).__name__  # noqa: S101


@pytest.mark.asyncio

async def test_error_transcribe_bad_format() -> None:
    """400 Bad Request when audio format is unsupported."""
    # skipped: assertion type 'equals' has no accessor for error field error.status_code in this backend
    with pytest.raises(Exception) as exc_info:  # noqa: B017
        client = create_client(api_key="test-key", base_url=os.environ["MOCK_SERVER_URL"] + "/fixtures/error_transcribe_bad_format")
        request = CreateTranscriptionRequest.from_json("{\"file\":\"audio.xyz\",\"model\":\"whisper-1\"}")
        await client.transcribe(request)
    assert "BadRequest" in str(exc_info.value) or "BadRequest" in type(exc_info.value).__name__  # noqa: S101


@pytest.mark.asyncio

async def test_smoke_transcribe_basic() -> None:
    """Basic audio transcription."""
    client = create_client(api_key="test-key", base_url=os.environ["MOCK_SERVER_URL"] + "/fixtures/smoke_transcribe_basic")
    request = CreateTranscriptionRequest.from_json("{\"file\":\"audio.mp3\",\"model\":\"whisper-1\"}")

    result = await client.transcribe(request)
    assert "Hello, this is a test transcription." in result.text  # noqa: S101


@pytest.mark.asyncio

async def test_smoke_transcribe_with_language() -> None:
    """Audio transcription with explicit language hint."""
    client = create_client(api_key="test-key", base_url=os.environ["MOCK_SERVER_URL"] + "/fixtures/smoke_transcribe_with_language")
    request = CreateTranscriptionRequest.from_json("{\"file\":\"audio_de.mp3\",\"language\":\"de\",\"model\":\"whisper-1\"}")

    result = await client.transcribe(request)
    assert "Hallo, dies ist ein Testtranskription." in result.text  # noqa: S101
