# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:c249c70b7640c53f754d8c96cd8e49cec28afa7f81e8f316163a5ff7df9c9773
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
"""E2e tests for category: custom_provider."""
import pytest
from liter_llm import chat


@pytest.mark.asyncio
async def test_provider_auth() -> None:
    """Tests custom provider with custom auth header."""
    request = None
    _ = await chat(request=request)

@pytest.mark.asyncio
async def test_register_provider() -> None:
    """Tests that a custom provider can be registered and routes requests."""
    request = None
    _ = await chat(request=request)

