# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:bc6d7a66c0e66c634f3ba0a18dd694e472ab3ce90d56b301dfbdda7bd37ebf4f
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
"""E2e tests for category: custom_provider."""
import pytest
from liter_llm import chat


@pytest.mark.asyncio
async def test_provider_auth() -> None:
    """Tests custom provider with custom auth header."""
    request = None
    _ = await chat(request=request)

@pytest.mark.asyncio
async def test_register_provider() -> None:
    """Tests that a custom provider can be registered and routes requests."""
    request = None
    _ = await chat(request=request)

