# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:0c4e67e829018b52d5b93eca51df656967ed1abe6c6b2ce58208a115cf2e982c
# To regenerate: alef generate
# To verify freshness: alef verify

"""E2e tests for category: search."""

import os
import pytest  # noqa: F401
from liter_llm import create_client
from liter_llm._internal_bindings import SearchRequest


@pytest.mark.asyncio

async def test_search_basic() -> None:
    """Basic web search request with a simple query."""
    client = create_client(api_key="test-key", base_url=os.environ["MOCK_SERVER_URL"] + "/fixtures/search_basic")
    request = SearchRequest.from_json("{\"model\":\"brave/web-search\",\"query\":\"What is Rust programming language?\"}")

    result = await client.search(request)
    assert result is not None  # noqa: S101


@pytest.mark.asyncio

async def test_search_empty_results() -> None:
    """Web search with a query that returns no results."""
    client = create_client(api_key="test-key", base_url=os.environ["MOCK_SERVER_URL"] + "/fixtures/search_empty_results")
    request = SearchRequest.from_json("{\"model\":\"brave/web-search\",\"query\":\"xyznonexistent12345xyz\"}")

    result = await client.search(request)
    assert result is not None  # noqa: S101


@pytest.mark.asyncio

async def test_search_error_400() -> None:
    """400 Bad Request error when search query is empty."""
    # skipped: assertion type 'equals' has no accessor for error field error.status_code in this backend
    with pytest.raises(Exception) as exc_info:  # noqa: B017
        client = create_client(api_key="test-key", base_url=os.environ["MOCK_SERVER_URL"] + "/fixtures/search_error_400")
        request = SearchRequest.from_json("{\"model\":\"brave/web-search\",\"query\":\"\"}")
        await client.search(request)
    assert "BadRequest" in str(exc_info.value) or "BadRequest" in type(exc_info.value).__name__  # noqa: S101


@pytest.mark.asyncio

async def test_search_error_401() -> None:
    """401 Unauthorized error on web search due to invalid API credentials."""
    # skipped: assertion type 'equals' has no accessor for error field error.status_code in this backend
    with pytest.raises(Exception) as exc_info:  # noqa: B017
        client = create_client(api_key="test-key", base_url=os.environ["MOCK_SERVER_URL"] + "/fixtures/search_error_401")
        request = SearchRequest.from_json("{\"model\":\"brave/web-search\",\"query\":\"test\"}")
        await client.search(request)
    assert "Authentication" in str(exc_info.value) or "Authentication" in type(exc_info.value).__name__  # noqa: S101


@pytest.mark.asyncio

async def test_search_with_max_results() -> None:
    """Search request with max_results parameter limiting response count."""
    client = create_client(api_key="test-key", base_url=os.environ["MOCK_SERVER_URL"] + "/fixtures/search_with_max_results")
    request = SearchRequest.from_json("{\"max_results\":2,\"model\":\"brave/web-search\",\"query\":\"Rust programming\"}")

    result = await client.search(request)
    assert len(result.results) == 2  # noqa: S101
