// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:78c27f20dbebf74093084ca4668c6ac99b39552e5bd056021d1efc707fe7cb5e
// To regenerate: alef generate
// To verify freshness: alef verify
// swift-format-ignore-file

import XCTest
import Foundation
#if canImport(FoundationNetworking)
import FoundationNetworking
#endif
import LiterLlm
import RustBridge

/// E2e tests for category: error-handling.
final class ErrorHandlingTests: XCTestCase {
    override class func setUp() {
        super.setUp()
    }

    func testAnthropicErrorAuth() async throws {
        // 401 Authentication error returned by the Anthropic API when the API key is invalid
        do {
            let _request = try LiterLlm.chatCompletionRequestFromJson("{\"messages\":[{\"content\":\"Hello\",\"role\":\"user\"}],\"model\":\"anthropic/claude-3-5-sonnet-20241022\"}")
            let _client = try createClient(apiKey: "test-key", baseUrl: AlefE2EMockServer.baseURL + "/fixtures/anthropic_error_auth")
            _ = try await _client.chat(_request)
            XCTFail("expected to throw")
        } catch {
            let _errorMessage = String(describing: error)
            let _errorType = String(describing: type(of: error))
            XCTAssertTrue(_errorMessage.contains("Authentication") || _errorType.contains("Authentication"), "expected error to mention \"Authentication\", got message: \(_errorMessage), type: \(_errorType)")
        }
        // skipped: assertion type 'equals' has no accessor for error field error.status_code in this backend
    }

    func testAuth401() async throws {
        // 401 Unauthorized error when API key is invalid or missing
        do {
            let _request = try LiterLlm.chatCompletionRequestFromJson("{\"messages\":[{\"content\":\"Hello\",\"role\":\"user\"}],\"model\":\"gpt-4\"}")
            let _client = try createClient(apiKey: "test-key", baseUrl: AlefE2EMockServer.baseURL + "/fixtures/auth_401")
            _ = try await _client.chat(_request)
            XCTFail("expected to throw")
        } catch {
            let _errorMessage = String(describing: error)
            let _errorType = String(describing: type(of: error))
            XCTAssertTrue(_errorMessage.contains("Authentication") || _errorType.contains("Authentication"), "expected error to mention \"Authentication\", got message: \(_errorMessage), type: \(_errorType)")
        }
        // skipped: assertion type 'equals' has no accessor for error field error.status_code in this backend
    }

    func testAzureErrorAuth() async throws {
        // Azure OpenAI returns a 401 Unauthorized error when the API key is missing or invalid — uses Azure's error envelope shape with code AccessDenied
        do {
            let _request = try LiterLlm.chatCompletionRequestFromJson("{\"messages\":[{\"content\":\"Hello\",\"role\":\"user\"}],\"model\":\"azure/gpt-4\"}")
            let _client = try createClient(apiKey: "test-key", baseUrl: AlefE2EMockServer.baseURL + "/fixtures/azure_error_auth")
            _ = try await _client.chat(_request)
            XCTFail("expected to throw")
        } catch {
            let _errorMessage = String(describing: error)
            let _errorType = String(describing: type(of: error))
            XCTAssertTrue(_errorMessage.contains("Authentication") || _errorType.contains("Authentication"), "expected error to mention \"Authentication\", got message: \(_errorMessage), type: \(_errorType)")
        }
        // skipped: assertion type 'equals' has no accessor for error field error.status_code in this backend
    }

    func testBadRequest400() async throws {
        // 400 Bad Request error when a parameter value is invalid
        do {
            let _request = try LiterLlm.chatCompletionRequestFromJson("{\"messages\":[{\"content\":\"Hello\",\"role\":\"user\"}],\"model\":\"gpt-4\",\"temperature\":5.0}")
            let _client = try createClient(apiKey: "test-key", baseUrl: AlefE2EMockServer.baseURL + "/fixtures/bad_request_400")
            _ = try await _client.chat(_request)
            XCTFail("expected to throw")
        } catch {
            let _errorMessage = String(describing: error)
            let _errorType = String(describing: type(of: error))
            XCTAssertTrue(_errorMessage.contains("BadRequest") || _errorType.contains("BadRequest"), "expected error to mention \"BadRequest\", got message: \(_errorMessage), type: \(_errorType)")
        }
        // skipped: assertion type 'equals' has no accessor for error field error.status_code in this backend
    }

    func testBedrockErrorAuth() async throws {
        // AWS Bedrock returns 403 Forbidden (not 401) when credentials are missing, expired, or the IAM role lacks bedrock:InvokeModel permission — verifies the error is mapped to Authentication
        do {
            let _request = try LiterLlm.chatCompletionRequestFromJson("{\"messages\":[{\"content\":\"Hello\",\"role\":\"user\"}],\"model\":\"bedrock/anthropic.claude-3-sonnet-20240229-v1:0\"}")
            let _client = try createClient(apiKey: "test-key", baseUrl: AlefE2EMockServer.baseURL + "/fixtures/bedrock_error_auth")
            _ = try await _client.chat(_request)
            XCTFail("expected to throw")
        } catch {
            let _errorMessage = String(describing: error)
            let _errorType = String(describing: type(of: error))
            XCTAssertTrue(_errorMessage.contains("Authentication") || _errorType.contains("Authentication"), "expected error to mention \"Authentication\", got message: \(_errorMessage), type: \(_errorType)")
        }
        // skipped: assertion type 'equals' has no accessor for error field error.status_code in this backend
    }

    func testContentPolicyViolation() async throws {
        // 400 error when a request is rejected due to content policy
        do {
            let _request = try LiterLlm.chatCompletionRequestFromJson("{\"messages\":[{\"content\":\"Generate harmful content\",\"role\":\"user\"}],\"model\":\"gpt-4\"}")
            let _client = try createClient(apiKey: "test-key", baseUrl: AlefE2EMockServer.baseURL + "/fixtures/content_policy_violation")
            _ = try await _client.chat(_request)
            XCTFail("expected to throw")
        } catch {
            let _errorMessage = String(describing: error)
            let _errorType = String(describing: type(of: error))
            XCTAssertTrue(_errorMessage.contains("ContentPolicy") || _errorType.contains("ContentPolicy"), "expected error to mention \"ContentPolicy\", got message: \(_errorMessage), type: \(_errorType)")
        }
        // skipped: assertion type 'equals' has no accessor for error field error.status_code in this backend
    }

    func testContextWindowExceeded() async throws {
        // 400 error when the prompt exceeds the model's maximum context length
        do {
            let _request = try LiterLlm.chatCompletionRequestFromJson("{\"messages\":[{\"content\":\"Very long prompt that exceeds the context window...\",\"role\":\"user\"}],\"model\":\"gpt-4\"}")
            let _client = try createClient(apiKey: "test-key", baseUrl: AlefE2EMockServer.baseURL + "/fixtures/context_window_exceeded")
            _ = try await _client.chat(_request)
            XCTFail("expected to throw")
        } catch {
            let _errorMessage = String(describing: error)
            let _errorType = String(describing: type(of: error))
            XCTAssertTrue(_errorMessage.contains("ContextWindowExceeded") || _errorType.contains("ContextWindowExceeded"), "expected error to mention \"ContextWindowExceeded\", got message: \(_errorMessage), type: \(_errorType)")
        }
        // skipped: assertion type 'equals' has no accessor for error field error.status_code in this backend
    }

    func testEmptyResponseBody() async throws {
        // 200 OK response with an empty JSON object body, missing required fields
        do {
            let _request = try LiterLlm.chatCompletionRequestFromJson("{\"messages\":[{\"content\":\"Hello\",\"role\":\"user\"}],\"model\":\"gpt-4\"}")
            let _client = try createClient(apiKey: "test-key", baseUrl: AlefE2EMockServer.baseURL + "/fixtures/empty_response_body")
            _ = try await _client.chat(_request)
            XCTFail("expected to throw")
        } catch {
            // success
        }
    }

    func testForbidden403() async throws {
        // 403 Forbidden error when the API key does not have access to the requested resource
        do {
            let _request = try LiterLlm.chatCompletionRequestFromJson("{\"messages\":[{\"content\":\"Hello\",\"role\":\"user\"}],\"model\":\"gpt-4\"}")
            let _client = try createClient(apiKey: "test-key", baseUrl: AlefE2EMockServer.baseURL + "/fixtures/forbidden_403")
            _ = try await _client.chat(_request)
            XCTFail("expected to throw")
        } catch {
            let _errorMessage = String(describing: error)
            let _errorType = String(describing: type(of: error))
            XCTAssertTrue(_errorMessage.contains("Authentication") || _errorType.contains("Authentication"), "expected error to mention \"Authentication\", got message: \(_errorMessage), type: \(_errorType)")
        }
        // skipped: assertion type 'equals' has no accessor for error field error.status_code in this backend
    }

    func testGatewayTimeout504() async throws {
        // 504 Gateway Timeout error when the upstream service times out
        do {
            let _request = try LiterLlm.chatCompletionRequestFromJson("{\"messages\":[{\"content\":\"Hello\",\"role\":\"user\"}],\"model\":\"gpt-4\"}")
            let _client = try createClient(apiKey: "test-key", baseUrl: AlefE2EMockServer.baseURL + "/fixtures/gateway_timeout_504")
            _ = try await _client.chat(_request)
            XCTFail("expected to throw")
        } catch {
            let _errorMessage = String(describing: error)
            let _errorType = String(describing: type(of: error))
            XCTAssertTrue(_errorMessage.contains("ServiceUnavailable") || _errorType.contains("ServiceUnavailable"), "expected error to mention \"ServiceUnavailable\", got message: \(_errorMessage), type: \(_errorType)")
        }
        // skipped: assertion type 'equals' has no accessor for error field error.status_code in this backend
    }

    func testGithubCopilotErrorAuth() async throws {
        // 401 Authentication error returned by the GitHub Copilot API when the token is invalid or expired
        do {
            let _request = try LiterLlm.chatCompletionRequestFromJson("{\"messages\":[{\"content\":\"Hello\",\"role\":\"user\"}],\"model\":\"github_copilot/gpt-4o\"}")
            let _client = try createClient(apiKey: "test-key", baseUrl: AlefE2EMockServer.baseURL + "/fixtures/github_copilot_error_auth")
            _ = try await _client.chat(_request)
            XCTFail("expected to throw")
        } catch {
            let _errorMessage = String(describing: error)
            let _errorType = String(describing: type(of: error))
            XCTAssertTrue(_errorMessage.contains("Authentication") || _errorType.contains("Authentication"), "expected error to mention \"Authentication\", got message: \(_errorMessage), type: \(_errorType)")
        }
        // skipped: assertion type 'equals' has no accessor for error field error.status_code in this backend
    }

    func testNotFound404() async throws {
        // 404 Not Found error when requesting a model that does not exist
        do {
            let _request = try LiterLlm.chatCompletionRequestFromJson("{\"messages\":[{\"content\":\"Hello\",\"role\":\"user\"}],\"model\":\"gpt-99\"}")
            let _client = try createClient(apiKey: "test-key", baseUrl: AlefE2EMockServer.baseURL + "/fixtures/not_found_404")
            _ = try await _client.chat(_request)
            XCTFail("expected to throw")
        } catch {
            let _errorMessage = String(describing: error)
            let _errorType = String(describing: type(of: error))
            XCTAssertTrue(_errorMessage.contains("NotFound") || _errorType.contains("NotFound"), "expected error to mention \"NotFound\", got message: \(_errorMessage), type: \(_errorType)")
        }
        // skipped: assertion type 'equals' has no accessor for error field error.status_code in this backend
    }

    func testRateLimit429() async throws {
        // 429 Too Many Requests error when the rate limit is exceeded
        do {
            let _request = try LiterLlm.chatCompletionRequestFromJson("{\"messages\":[{\"content\":\"Hello\",\"role\":\"user\"}],\"model\":\"gpt-4\"}")
            let _client = try createClient(apiKey: "test-key", baseUrl: AlefE2EMockServer.baseURL + "/fixtures/rate_limit_429")
            _ = try await _client.chat(_request)
            XCTFail("expected to throw")
        } catch {
            let _errorMessage = String(describing: error)
            let _errorType = String(describing: type(of: error))
            XCTAssertTrue(_errorMessage.contains("RateLimited") || _errorType.contains("RateLimited"), "expected error to mention \"RateLimited\", got message: \(_errorMessage), type: \(_errorType)")
        }
        // skipped: assertion type 'equals' has no accessor for error field error.status_code in this backend
    }

    func testServerError500() async throws {
        // 500 Internal Server Error from the upstream API
        do {
            let _request = try LiterLlm.chatCompletionRequestFromJson("{\"messages\":[{\"content\":\"Hello\",\"role\":\"user\"}],\"model\":\"gpt-4\"}")
            let _client = try createClient(apiKey: "test-key", baseUrl: AlefE2EMockServer.baseURL + "/fixtures/server_error_500")
            _ = try await _client.chat(_request)
            XCTFail("expected to throw")
        } catch {
            let _errorMessage = String(describing: error)
            let _errorType = String(describing: type(of: error))
            XCTAssertTrue(_errorMessage.contains("ServerError") || _errorType.contains("ServerError"), "expected error to mention \"ServerError\", got message: \(_errorMessage), type: \(_errorType)")
        }
        // skipped: assertion type 'equals' has no accessor for error field error.status_code in this backend
    }

    func testServiceUnavailable502() async throws {
        // 502 Bad Gateway error when the upstream service is unavailable
        do {
            let _request = try LiterLlm.chatCompletionRequestFromJson("{\"messages\":[{\"content\":\"Hello\",\"role\":\"user\"}],\"model\":\"gpt-4\"}")
            let _client = try createClient(apiKey: "test-key", baseUrl: AlefE2EMockServer.baseURL + "/fixtures/service_unavailable_502")
            _ = try await _client.chat(_request)
            XCTFail("expected to throw")
        } catch {
            let _errorMessage = String(describing: error)
            let _errorType = String(describing: type(of: error))
            XCTAssertTrue(_errorMessage.contains("ServiceUnavailable") || _errorType.contains("ServiceUnavailable"), "expected error to mention \"ServiceUnavailable\", got message: \(_errorMessage), type: \(_errorType)")
        }
        // skipped: assertion type 'equals' has no accessor for error field error.status_code in this backend
    }

    func testTimeoutError() async throws {
        // 408 Request Timeout error when the API request takes too long to complete
        do {
            let _request = try LiterLlm.chatCompletionRequestFromJson("{\"messages\":[{\"content\":\"Hello\",\"role\":\"user\"}],\"model\":\"gpt-4\"}")
            let _client = try createClient(apiKey: "test-key", baseUrl: AlefE2EMockServer.baseURL + "/fixtures/timeout_error")
            _ = try await _client.chat(_request)
            XCTFail("expected to throw")
        } catch {
            let _errorMessage = String(describing: error)
            let _errorType = String(describing: type(of: error))
            XCTAssertTrue(_errorMessage.contains("Timeout") || _errorType.contains("Timeout"), "expected error to mention \"Timeout\", got message: \(_errorMessage), type: \(_errorType)")
        }
        // skipped: assertion type 'equals' has no accessor for error field error.status_code in this backend
    }

    func testVertexErrorAuth() async throws {
        // Google Vertex AI returns 401 Unauthorized when the OAuth2 token is missing, expired, or the service account lacks aiplatform.endpoints.predict permission — verifies the error is mapped to Authentication
        do {
            let _request = try LiterLlm.chatCompletionRequestFromJson("{\"messages\":[{\"content\":\"Hello\",\"role\":\"user\"}],\"model\":\"vertex_ai/gemini-2.0-flash\"}")
            let _client = try createClient(apiKey: "test-key", baseUrl: AlefE2EMockServer.baseURL + "/fixtures/vertex_error_auth")
            _ = try await _client.chat(_request)
            XCTFail("expected to throw")
        } catch {
            let _errorMessage = String(describing: error)
            let _errorType = String(describing: type(of: error))
            XCTAssertTrue(_errorMessage.contains("Authentication") || _errorType.contains("Authentication"), "expected error to mention \"Authentication\", got message: \(_errorMessage), type: \(_errorType)")
        }
        // skipped: assertion type 'equals' has no accessor for error field error.status_code in this backend
    }

}
