// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:8577872c86e2225de080e95be466e329c05080fb3e19cc70b61285fec4ee894d
// To regenerate: alef generate
// To verify freshness: alef verify
// swift-format-ignore-file

import XCTest
import Foundation
#if canImport(FoundationNetworking)
import FoundationNetworking
#endif
import LiterLlm
import RustBridge

/// E2e tests for category: transcribe.
final class TranscribeTests: XCTestCase {
    override class func setUp() {
        super.setUp()
    }

    func testEdgeTranscribeEmptyAudio() async throws {
        // Transcription of a silent or empty audio file returns empty text
        let _request = try LiterLlm.createTranscriptionRequestFromJson("{\"file\":\"silence.mp3\",\"model\":\"whisper-1\"}")
        let _client = try createClient(apiKey: "test-key", baseUrl: AlefE2EMockServer.baseURL + "/fixtures/edge_transcribe_empty_audio")
        let result = try await _client.transcribe(_request)
        XCTAssertNotNil(result)
        XCTAssertTrue("".isEmpty || result.text.contains(""), "expected to contain: \("")")
    }

    func testEdgeTranscribeWithTimestamps() async throws {
        // Transcription with verbose JSON response format including timestamp segments
        let _request = try LiterLlm.createTranscriptionRequestFromJson("{\"file\":\"audio.mp3\",\"model\":\"whisper-1\",\"response_format\":\"verbose_json\"}")
        let _client = try createClient(apiKey: "test-key", baseUrl: AlefE2EMockServer.baseURL + "/fixtures/edge_transcribe_with_timestamps")
        let result = try await _client.transcribe(_request)
        XCTAssertNotNil(result)
        XCTAssertGreaterThan(result.text.count, 0, "expected non-empty value")
        XCTAssertEqual((result.segments?.count ?? 0), 3)
        XCTAssertEqual(result.segments?[0].id, 0)
    }

    func testErrorTranscribeAuth401() async throws {
        // 401 Unauthorized for transcription with invalid API key
        do {
            let _request = try LiterLlm.createTranscriptionRequestFromJson("{\"file\":\"audio.mp3\",\"model\":\"whisper-1\"}")
            let _client = try createClient(apiKey: "test-key", baseUrl: AlefE2EMockServer.baseURL + "/fixtures/error_transcribe_auth_401")
            _ = try await _client.transcribe(_request)
            XCTFail("expected to throw")
        } catch {
            let _errorMessage = String(describing: error)
            let _errorType = String(describing: type(of: error))
            XCTAssertTrue(_errorMessage.contains("Authentication") || _errorType.contains("Authentication"), "expected error to mention \"Authentication\", got message: \(_errorMessage), type: \(_errorType)")
        }
        // skipped: assertion type 'equals' has no accessor for error field error.status_code in this backend
    }

    func testErrorTranscribeBadFormat() async throws {
        // 400 Bad Request when audio format is unsupported
        do {
            let _request = try LiterLlm.createTranscriptionRequestFromJson("{\"file\":\"audio.xyz\",\"model\":\"whisper-1\"}")
            let _client = try createClient(apiKey: "test-key", baseUrl: AlefE2EMockServer.baseURL + "/fixtures/error_transcribe_bad_format")
            _ = try await _client.transcribe(_request)
            XCTFail("expected to throw")
        } catch {
            let _errorMessage = String(describing: error)
            let _errorType = String(describing: type(of: error))
            XCTAssertTrue(_errorMessage.contains("BadRequest") || _errorType.contains("BadRequest"), "expected error to mention \"BadRequest\", got message: \(_errorMessage), type: \(_errorType)")
        }
        // skipped: assertion type 'equals' has no accessor for error field error.status_code in this backend
    }

    func testSmokeTranscribeBasic() async throws {
        // Basic audio transcription
        let _request = try LiterLlm.createTranscriptionRequestFromJson("{\"file\":\"audio.mp3\",\"model\":\"whisper-1\"}")
        let _client = try createClient(apiKey: "test-key", baseUrl: AlefE2EMockServer.baseURL + "/fixtures/smoke_transcribe_basic")
        let result = try await _client.transcribe(_request)
        XCTAssertNotNil(result)
        XCTAssertTrue("Hello, this is a test transcription.".isEmpty || result.text.contains("Hello, this is a test transcription."), "expected to contain: \("Hello, this is a test transcription.")")
    }

    func testSmokeTranscribeWithLanguage() async throws {
        // Audio transcription with explicit language hint
        let _request = try LiterLlm.createTranscriptionRequestFromJson("{\"file\":\"audio_de.mp3\",\"language\":\"de\",\"model\":\"whisper-1\"}")
        let _client = try createClient(apiKey: "test-key", baseUrl: AlefE2EMockServer.baseURL + "/fixtures/smoke_transcribe_with_language")
        let result = try await _client.transcribe(_request)
        XCTAssertNotNil(result)
        XCTAssertTrue("Hallo, dies ist ein Testtranskription.".isEmpty || result.text.contains("Hallo, dies ist ein Testtranskription."), "expected to contain: \("Hallo, dies ist ein Testtranskription.")")
    }

}
