# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:05c16bb9f7f09bf5db46911b41ff2ce2fd84a444489e0c8c2bca52a3f6ff2a05
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule LiterLlm.AssistantContent do
  @moduledoc """
  Content shape for assistant messages.

  `#[serde(untagged)]` means providers returning a plain scalar string for the
  `content` field still deserialise correctly into `AssistantContent::Text(_)`.
  Providers returning an array of typed parts (e.g. after an image-generation
  or audio-synthesis request) deserialise into `AssistantContent::Parts(_)`.
  """

  @typedoc "Content shape for assistant messages."
  @type t :: term()

  @typedoc "Plain text response (the common case for text-only models)."
  @type text :: %{type: :text, value: String.t()}
  @typedoc "Structured parts — text, refusals, output images, output audio."
  @type parts :: %{type: :parts, value: [map()]}
end
