# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:b713cdc932d78474deb27590f90844c3f463beda3e2e590d8bc6c93bf009eea8
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule LiterLlm.AssistantMessage do
  @moduledoc "Assistant's response to a user message."

  @typedoc "Assistant's response to a user message."
  @type t :: %__MODULE__{
          content: String.t() | nil | nil,
          name: String.t() | nil,
          tool_calls: [LiterLlm.ToolCall.t()] | nil,
          refusal: String.t() | nil,
          function_call: LiterLlm.FunctionCall.t() | nil,
          reasoning_content: String.t() | nil
        }

  defstruct content: nil,
            name: nil,
            tool_calls: nil,
            refusal: nil,
            function_call: nil,
            reasoning_content: nil

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
