# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:5f08b2094eaec949328795602be53b5f3532bfd48cd130fdeea4e5cb82d41ae0
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule LiterLlm.AuthHeaderFormat do
  @moduledoc "How the API key is sent in the HTTP request."

  @type t :: term()

  @type bearer :: :bearer
  @type api_key :: %{type: :api_key, value_0: term()}
  @type none_variant :: :none
end
