# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:cf12a91b71f7e7e78174f6741902a20de61b1e89a6a7b79a92a43f7c017e8379
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule LiterLlm.AuthConfig do
  @moduledoc "Auth configuration block."

  @typedoc "Auth configuration block."
  @type t :: %__MODULE__{
          auth_type: String.t() | nil,
          env_var: String.t() | nil
        }

  defstruct auth_type: :bearer,
            env_var: nil
end
