# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:9cd847387d336a6aeac9f43b66fecf03af7294cd4315ef3afb1d10ec82819af9
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule LiterLlm.AuthConfig do
  @moduledoc "Auth configuration block."

  @typedoc "Auth configuration block."
  @type t :: %__MODULE__{
          auth_type: LiterLlm.AuthType.t(),
          env_var: String.t() | nil
        }

  defstruct auth_type: :bearer,
            env_var: nil
end
