# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:73516780160260b48f0f858446476f02c4d37d19c77500de1a053109f5d49a60
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule LiterLlm.AuthType do
  @moduledoc "Auth scheme used by a provider."

  @typedoc "Auth scheme used by a provider."
  @type t :: :bearer | :api_key | :none | :unknown

  @bearer :bearer
  @api_key :api_key
  @none :none
  @unknown :unknown

  @doc "Standard `Authorization: Bearer <key>` header."
  @spec bearer() :: t()
  def bearer, do: @bearer
  @doc "`x-api-key: <key>` header (also handles `\"header\"` and `\"x-api-key\"` aliases)."
  @spec api_key() :: t()
  def api_key, do: @api_key
  @doc "No authentication header required."
  @spec none() :: t()
  def none, do: @none
  @doc "Unrecognised auth scheme — falls back to bearer."
  @spec unknown() :: t()
  def unknown, do: @unknown
end
