# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:938b8ffd93c3e30d74875f875188c728addee9d4b80a97a7ac22716b3154c7c5
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule LiterLlm.AuthHeaderFormat do
  @moduledoc "How the API key is sent in the HTTP request."

  @typedoc "How the API key is sent in the HTTP request."
  @type t :: term()

  @typedoc "Bearer token: `Authorization: Bearer <key>`"
  @type bearer :: :bearer
  @typedoc "Custom header: e.g., `X-Api-Key: <key>`"
  @type api_key :: %{type: :api_key, value: String.t()}
  @typedoc "No authentication required."
  @type none_variant :: :none
end
