# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:955f1db0d5a7287c669e71d725bdfe0217692c9ede28cb23000392b9c6c79646
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule LiterLlm.AuthHeaderFormat do
  @moduledoc "How the API key is sent in the HTTP request."

  @typedoc "How the API key is sent in the HTTP request."
  @type t :: term()

  @typedoc "Bearer token: `Authorization: Bearer <key>`"
  @type bearer :: :bearer
  @typedoc "Custom header: e.g., `X-Api-Key: <key>`"
  @type api_key :: %{type: :api_key, value: String.t()}
  @typedoc "No authentication required."
  @type none_variant :: :none

  @doc "Returns the serde wire value this variant carries on the JSON boundary (see `wire_variant_value` in alef's naming module) -- distinct from the atom's Elixir spelling."
  @spec wire_value(t()) :: String.t()
  def wire_value(:bearer), do: "Bearer"
  def wire_value(:api_key), do: "ApiKey"
  def wire_value(:none), do: "None"
  def wire_value(value) when is_tuple(value), do: wire_value(elem(value, 0))
  def wire_value(value) when is_map(value), do: Map.fetch!(value, :type)

  defimpl String.Chars, for: LiterLlm.AuthHeaderFormat do
    @doc false
    def to_string(value), do: LiterLlm.AuthHeaderFormat.wire_value(value)
  end
end
