# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:8cc9037a770ff9c91df91ed4850d849469167bc16d16a03f76291e9b27f5ec1b
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule LiterLlm.BatchRequestCounts do
  @moduledoc "Request processing counts for a batch."

  @typedoc "Request processing counts for a batch."
  @type t :: %__MODULE__{
          total: non_neg_integer(),
          completed: non_neg_integer(),
          failed: non_neg_integer()
        }

  defstruct total: 0,
            completed: 0,
            failed: 0

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
