# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:7bbd735a441751bbdd61a599eaa5273954860d8d16e6cafb8dc02691c7aee51e
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule LiterLlm.BatchListQuery do
  @moduledoc "Query parameters for listing batches."

  @typedoc "Query parameters for listing batches."
  @type t :: %__MODULE__{
          limit: non_neg_integer() | nil,
          after: String.t() | nil
        }

  defstruct limit: nil,
            after: nil

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
