# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:08c41f5c62ca562289e71f634aceb51e35245585ce7b878b7bc1fe3a75443f48
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule LiterLlm.BatchListResponse do
  @moduledoc "Response from listing batches."

  @typedoc "Response from listing batches."
  @type t :: %__MODULE__{
          object: String.t() | nil,
          data: [LiterLlm.BatchObject.t()],
          has_more: boolean() | nil,
          first_id: String.t() | nil,
          last_id: String.t() | nil
        }

  defstruct object: nil,
            data: [],
            has_more: nil,
            first_id: nil,
            last_id: nil

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
