# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:b713cdc932d78474deb27590f90844c3f463beda3e2e590d8bc6c93bf009eea8
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule LiterLlm.BatchListResponse do
  @moduledoc "Response from listing batches."

  @typedoc "Response from listing batches."
  @type t :: %__MODULE__{
          object: String.t() | nil,
          data: [LiterLlm.BatchObject.t()],
          has_more: boolean() | nil,
          first_id: String.t() | nil,
          last_id: String.t() | nil
        }

  defstruct object: nil,
            data: [],
            has_more: nil,
            first_id: nil,
            last_id: nil

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
