# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:938b8ffd93c3e30d74875f875188c728addee9d4b80a97a7ac22716b3154c7c5
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule LiterLlm.BedrockConfig do
  @moduledoc """
  AWS Bedrock configuration.

  All fields are optional; anything left unset falls back to the standard
  AWS environment variables (`AWS_DEFAULT_REGION` / `AWS_REGION`,
  `AWS_ACCESS_KEY_ID`, `AWS_SECRET_ACCESS_KEY`, `AWS_SESSION_TOKEN`,
  `BEDROCK_CROSS_REGION`).
  """

  @typedoc "AWS Bedrock configuration."
  @type t :: %__MODULE__{
          region: String.t() | nil,
          cross_region_prefix: String.t() | nil,
          access_key_id: String.t() | nil,
          secret_access_key: String.t() | nil,
          session_token: String.t() | nil
        }

  defstruct region: nil,
            cross_region_prefix: nil,
            access_key_id: nil,
            secret_access_key: nil,
            session_token: nil

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
