# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:872f238d87e53196bf0612a2399cce53ed37b69e19c0bf1e94b4e196c7fbd128
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule LiterLlm.BudgetConfig do
  @moduledoc "Configuration for budget enforcement."

  @typedoc "Configuration for budget enforcement."
  @type t :: %__MODULE__{
          global_limit: float() | nil,
          model_limits: map(),
          enforcement: String.t() | nil
        }

  defstruct global_limit: nil,
            model_limits: %{},
            enforcement: :hard

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
