# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:d6f21c94c41c048310c4c2b805087760ffc4144fdf5075dc65e01af58b66ceab
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule LiterLlm.BudgetConfig do
  @moduledoc "Configuration for budget enforcement."

  @typedoc "Configuration for budget enforcement."
  @type t :: %__MODULE__{
          global_limit: float() | nil,
          model_limits: map(),
          enforcement: LiterLlm.Enforcement.t()
        }

  defstruct global_limit: nil,
            model_limits: %{},
            enforcement: :hard

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
