# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:9ca6714382d5977ba89edd2f09addf092370c00e33d03fa288491e783ed5cc74
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule LiterLlm.BudgetConfig do
  @moduledoc "Configuration for budget enforcement."

  @typedoc "Configuration for budget enforcement."
  @type t :: %__MODULE__{
          global_limit: float() | nil,
          model_limits: map(),
          enforcement: String.t() | nil
        }

  defstruct global_limit: nil,
            model_limits: %{},
            enforcement: :hard

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
