# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:b713cdc932d78474deb27590f90844c3f463beda3e2e590d8bc6c93bf009eea8
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule LiterLlm.CacheBackend do
  @moduledoc "Storage backend for the response cache."

  @typedoc "Storage backend for the response cache."
  @type t :: term()

  @typedoc "In-memory LRU cache (default). No external dependencies."
  @type memory :: :memory
  @typedoc "OpenDAL-backed storage. Supports 40+ backends (S3, Redis, GCS, local FS, etc.)."
  @type open_dal :: %{type: :open_dal, scheme: String.t(), config: map()}

  def open_dal(scheme, config), do: {:open_dal, %{scheme: scheme, config: config}}
end
