# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:b713cdc932d78474deb27590f90844c3f463beda3e2e590d8bc6c93bf009eea8
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule LiterLlm.CacheConfig do
  @moduledoc "Configuration for the response cache."

  @typedoc "Configuration for the response cache."
  @type t :: %__MODULE__{
          max_entries: non_neg_integer(),
          ttl: non_neg_integer(),
          backend: String.t() | nil
        }

  defstruct max_entries: 256,
            ttl: 300_000,
            backend: :memory

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
