# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:9c479751c0805b45ce76a17491cc7b1b4c87a95d35e5ac93b5d5d0ac4b974284
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule LiterLlm.ChatCompletionResponse do
  @moduledoc "Chat completion response from the API."

  @typedoc "Chat completion response from the API."
  @type t :: %__MODULE__{
          id: String.t() | nil,
          object: String.t() | nil,
          created: non_neg_integer(),
          model: String.t() | nil,
          choices: [LiterLlm.Choice.t()],
          usage: LiterLlm.Usage.t() | nil,
          system_fingerprint: String.t() | nil,
          service_tier: String.t() | nil
        }

  defstruct id: nil,
            object: nil,
            created: 0,
            model: nil,
            choices: [],
            usage: nil,
            system_fingerprint: nil,
            service_tier: nil

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
