# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:1d0439524d2675a5ea3a0012d9fc8e14e4db9b6c055a05501388f59554217aa2
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule LiterLlm.ChatCompletionTool do
  @moduledoc "A tool the model can invoke (currently, all tools are functions)."

  @typedoc "A tool the model can invoke (currently, all tools are functions)."
  @type t :: %__MODULE__{
          tool_type: LiterLlm.ToolType.t(),
          function: LiterLlm.FunctionDefinition.t()
        }

  defstruct tool_type: :function,
            function: nil
end
