# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:c249c70b7640c53f754d8c96cd8e49cec28afa7f81e8f316163a5ff7df9c9773
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule LiterLlm.ChatCompletionRequest do
  @moduledoc false

  defstruct model: "",
            messages: [],
            temperature: 0.0,
            top_p: 0.0,
            n: 0,
            stream: false,
            stop: :single,
            max_tokens: 0,
            presence_penalty: 0.0,
            frequency_penalty: 0.0,
            logit_bias: %{},
            user: "",
            tools: [],
            tool_choice: :mode,
            parallel_tool_calls: false,
            response_format: :text,
            stream_options: nil,
            seed: 0,
            reasoning_effort: :medium,
            extra_body: ""
end
