# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:9c479751c0805b45ce76a17491cc7b1b4c87a95d35e5ac93b5d5d0ac4b974284
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule LiterLlm.Choice do
  @moduledoc "A single completion choice."

  @typedoc "A single completion choice."
  @type t :: %__MODULE__{
          index: non_neg_integer(),
          message: LiterLlm.AssistantMessage.t(),
          finish_reason: String.t() | nil | nil
        }

  defstruct index: 0,
            message: nil,
            finish_reason: nil

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
