# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:2b7aaea70ddc2f2ce430e47ad1251a31a8df5cba7e9c418e308439cbe072bb2b
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule LiterLlm.Choice do
  @moduledoc "A single completion choice."

  @typedoc "A single completion choice."
  @type t :: %__MODULE__{
          index: non_neg_integer(),
          message: LiterLlm.AssistantMessage.t(),
          finish_reason: LiterLlm.FinishReason.t() | nil,
          logprobs: String.t() | nil
        }

  defstruct index: 0,
            message: nil,
            finish_reason: nil,
            logprobs: nil

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
