# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:b3f8ee823d42a91b3dc7a62549d4d04bb171c9d7de692bc4bf985436a9b89556
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule LiterLlm.CircuitState do
  @moduledoc "Observable state of a circuit breaker."

  @typedoc "Observable state of a circuit breaker."
  @type t :: :closed | :open | :half_open

  @closed :closed
  @open :open
  @half_open :half_open

  @doc "Requests flow through normally."
  @spec closed() :: t()
  def closed, do: @closed
  @doc "All requests are rejected; the circuit is waiting for the backoff to elapse."
  @spec open() :: t()
  def open, do: @open
  @doc "One probe request is allowed through to test service health."
  @spec half_open() :: t()
  def half_open, do: @half_open
end
