# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:7cf57e7ce8a55eeaa33ccc72a2be71c87d5f76fd3b52056cd4c35fe6b83ee7f2
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule LiterLlm.CircuitState do
  @moduledoc "Observable state of a circuit breaker."

  @typedoc "Observable state of a circuit breaker."
  @type t :: :closed | :open | :half_open

  @closed :closed
  @open :open
  @half_open :half_open

  @doc "Requests flow through normally."
  @spec closed() :: t()
  def closed, do: @closed
  @doc "All requests are rejected; the circuit is waiting for the backoff to elapse."
  @spec open() :: t()
  def open, do: @open
  @doc "One probe request is allowed through to test service health."
  @spec half_open() :: t()
  def half_open, do: @half_open

  @doc "Returns the serde wire value this variant carries on the JSON boundary (see `wire_variant_value` in alef's naming module) -- distinct from the atom's Elixir spelling."
  @spec wire_value(t()) :: String.t()
  def wire_value(:closed), do: "Closed"
  def wire_value(:open), do: "Open"
  def wire_value(:half_open), do: "HalfOpen"
end
