# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:d37ea66d954ad374b69c65cfd4aa370951e0c0c095fdc72c3a3f39389871d474
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule LiterLlm.ContentPart do
  @moduledoc "A single content part in a user message — text, image, document, or audio."

  @typedoc "A single content part in a user message — text, image, document, or audio."
  @type t :: term()

  @typedoc "Plain text."
  @type text :: %{type: :text, text: String.t()}
  @typedoc "Image identified by URL (with optional detail level)."
  @type image_url :: %{type: :image_url, image_url: LiterLlm.ImageUrl.t()}
  @typedoc "Document file (PDF, CSV, etc.) as base64 or URL."
  @type document :: %{type: :document, document: LiterLlm.DocumentContent.t()}
  @typedoc "Audio input as base64."
  @type input_audio :: %{type: :input_audio, input_audio: LiterLlm.AudioContent.t()}

  def document(document), do: {:document, %{document: document}}
  def input_audio(input_audio), do: {:input_audio, %{input_audio: input_audio}}
end
