# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:59cac5c166131b797b3063f3b19ba8b8f8a0d1a100f0b2a219f1455f5ab63f85
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule LiterLlm.ContentPart do
  @moduledoc "A single content part in a user message — text, image, document, or audio."

  @typedoc "A single content part in a user message — text, image, document, or audio."
  @type t :: term()

  @typedoc "Plain text."
  @type text :: %{type: :text, text: String.t()}
  @typedoc "Image identified by URL (with optional detail level)."
  @type image_url :: %{type: :image_url, image_url: LiterLlm.ImageUrl.t()}
  @typedoc "Document file (PDF, CSV, etc.) as base64 or URL."
  @type document :: %{type: :document, document: LiterLlm.DocumentContent.t()}
  @typedoc "Audio input as base64."
  @type input_audio :: %{type: :input_audio, input_audio: LiterLlm.AudioContent.t()}

  def document(document), do: {:document, %{document: document}}
  def input_audio(input_audio), do: {:input_audio, %{input_audio: input_audio}}
end
