# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:72e003a654147251513d09f8ee5455bdf7432c3a8ba811f3c14854a524ef4957
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule LiterLlm.CreateTranscriptionRequest do
  @moduledoc "Request to transcribe audio into text."

  @typedoc "Request to transcribe audio into text."
  @type t :: %__MODULE__{
          model: String.t() | nil,
          file: String.t() | nil,
          language: String.t() | nil,
          prompt: String.t() | nil,
          response_format: String.t() | nil,
          temperature: float() | nil
        }

  defstruct model: nil,
            file: nil,
            language: nil,
            prompt: nil,
            response_format: nil,
            temperature: nil

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
