# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:9c479751c0805b45ce76a17491cc7b1b4c87a95d35e5ac93b5d5d0ac4b974284
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule LiterLlm.CreateBatchRequest do
  @moduledoc "Request to create a batch job."

  @typedoc "Request to create a batch job."
  @type t :: %__MODULE__{
          input_file_id: String.t() | nil,
          endpoint: String.t() | nil,
          completion_window: String.t() | nil,
          metadata: String.t() | nil
        }

  defstruct input_file_id: nil,
            endpoint: nil,
            completion_window: nil,
            metadata: nil

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
