# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:938b8ffd93c3e30d74875f875188c728addee9d4b80a97a7ac22716b3154c7c5
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule LiterLlm.CreateImageRequest do
  @moduledoc "Request to create images from a text prompt."

  @typedoc "Request to create images from a text prompt."
  @type t :: %__MODULE__{
          prompt: String.t() | nil,
          model: String.t() | nil,
          n: non_neg_integer() | nil,
          size: String.t() | nil,
          quality: String.t() | nil,
          style: String.t() | nil,
          response_format: String.t() | nil,
          user: String.t() | nil
        }

  defstruct prompt: nil,
            model: nil,
            n: nil,
            size: nil,
            quality: nil,
            style: nil,
            response_format: nil,
            user: nil

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
