# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:af7468ada2cd9571058cc95cc9883fc5ba83e0daaefa883551b310ba55f8dd2b
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule LiterLlm.CreateFileRequest do
  @moduledoc "Request to upload a file."

  @typedoc "Request to upload a file."
  @type t :: %__MODULE__{
          file: String.t() | nil,
          purpose: String.t() | nil,
          filename: String.t() | nil
        }

  defstruct file: nil,
            purpose: :assistants,
            filename: nil

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
