# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:036daf5f927fced19e79c62932efa3a2f5ed2071e25bbacf6da18078a6603c26
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule LiterLlm.CustomProviderConfig do
  @moduledoc "Configuration for registering a custom LLM provider at runtime."

  @typedoc "Configuration for registering a custom LLM provider at runtime."
  @type t :: %__MODULE__{
          name: String.t() | nil,
          base_url: String.t() | nil,
          auth_header: LiterLlm.AuthHeaderFormat.t(),
          model_prefixes: [String.t()]
        }

  defstruct name: nil,
            base_url: nil,
            auth_header: :bearer,
            model_prefixes: []
end
