# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:9faacf573433ad68258f213546de43c008dcb630e0e7b262f0225c93173c6424
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule LiterLlm.CustomProviderConfig do
  @moduledoc "Configuration for registering a custom LLM provider at runtime."

  @typedoc "Configuration for registering a custom LLM provider at runtime."
  @type t :: %__MODULE__{
          name: String.t() | nil,
          base_url: String.t() | nil,
          auth_header: LiterLlm.AuthHeaderFormat.t(),
          model_prefixes: [String.t()]
        }

  defstruct name: nil,
            base_url: nil,
            auth_header: :bearer,
            model_prefixes: []
end
