# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:b713cdc932d78474deb27590f90844c3f463beda3e2e590d8bc6c93bf009eea8
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule LiterLlm.CustomProviderConfig do
  @moduledoc "Configuration for registering a custom LLM provider at runtime."

  @typedoc "Configuration for registering a custom LLM provider at runtime."
  @type t :: %__MODULE__{
          name: String.t() | nil,
          base_url: String.t() | nil,
          auth_header: String.t() | nil,
          model_prefixes: [String.t()]
        }

  defstruct name: nil,
            base_url: nil,
            auth_header: :bearer,
            model_prefixes: []
end
