# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:645d8ff0f3a0ef7684f9b9ea4ce1ae251a78a2a3481ecdeabf7643c53d644bb0
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule LiterLlm.DecodedDataUrl do
  @moduledoc """
  Result of decoding a `data:` URL — MIME type and the decoded byte payload.

  Named struct (rather than a tuple) so polyglot bindings can extract
  `decode_data_url` with a typed return rather than a sanitized scalar.
  """

  @typedoc "Result of decoding a `data:` URL — MIME type and the decoded byte payload."
  @type t :: %__MODULE__{
          mime: String.t() | nil,
          data: binary()
        }

  defstruct mime: nil,
            data: <<>>

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
