# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:cceb23c4bb863b08798e49546f408b6a55da90faad31566e34275955f1da6d4d
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule LiterLlm.DeleteResponse do
  @moduledoc "Response from a delete operation."

  @typedoc "Response from a delete operation."
  @type t :: %__MODULE__{
          id: String.t() | nil,
          object: String.t() | nil,
          deleted: boolean()
        }

  defstruct id: nil,
            object: nil,
            deleted: false

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
