# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:7499d97bdecec9ba068f9bf13fdaad6528c82e061c3755d3ae2763715948c3dd
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule LiterLlm.DeleteResponse do
  @moduledoc "Response from a delete operation."

  @typedoc "Response from a delete operation."
  @type t :: %__MODULE__{
          id: String.t() | nil,
          object: String.t() | nil,
          deleted: boolean()
        }

  defstruct id: nil,
            object: nil,
            deleted: false

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
