# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:7499d97bdecec9ba068f9bf13fdaad6528c82e061c3755d3ae2763715948c3dd
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule LiterLlm.DeveloperMessage do
  @moduledoc "Developer message (system-like message for Claude models)."

  @typedoc "Developer message (system-like message for Claude models)."
  @type t :: %__MODULE__{
          content: String.t() | nil,
          name: String.t() | nil
        }

  defstruct content: nil,
            name: nil

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
