# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:9165e93835c879eb96366cf27357e9668eaba7d6fc2e761c5e0258daa7acfce9
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule LiterLlm.EmbeddingInput do
  @moduledoc "Text or texts to embed."

  @typedoc "Text or texts to embed."
  @type t :: term()

  @typedoc "Single text string."
  @type single :: %{type: :single, value: String.t()}
  @typedoc "Multiple text strings (batch embedding)."
  @type multiple :: %{type: :multiple, value: [String.t()]}
end
