# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:7bacb53ba62128cddbad2af9594a8f7a0d67daee3cb1a21a2569382109274fca
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule LiterLlm.EmbeddingRequest do
  @moduledoc "Embedding request."

  @typedoc "Embedding request."
  @type t :: %__MODULE__{
          model: String.t() | nil,
          input: String.t() | nil,
          encoding_format: String.t() | nil | nil,
          dimensions: non_neg_integer() | nil,
          user: String.t() | nil
        }

  defstruct model: nil,
            input: :single,
            encoding_format: nil,
            dimensions: nil,
            user: nil

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
