# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:f6eb4daaa072220fcaf76520827e2a6e71e5b3a046453c1f49395970cb4bf60d
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule LiterLlm.EmbeddingObject do
  @moduledoc "A single embedding vector."

  @typedoc "A single embedding vector."
  @type t :: %__MODULE__{
          object: String.t() | nil,
          embedding: [float()],
          index: non_neg_integer()
        }

  defstruct object: nil,
            embedding: [],
            index: 0
end
