# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:af7468ada2cd9571058cc95cc9883fc5ba83e0daaefa883551b310ba55f8dd2b
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule LiterLlm.EmbeddingObject do
  @moduledoc "A single embedding vector."

  @typedoc "A single embedding vector."
  @type t :: %__MODULE__{
          object: String.t() | nil,
          embedding: [float()],
          index: non_neg_integer()
        }

  defstruct object: nil,
            embedding: [],
            index: 0
end
