# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:9ca6714382d5977ba89edd2f09addf092370c00e33d03fa288491e783ed5cc74
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule LiterLlm.EmbeddingFormat do
  @moduledoc "The format in which the embedding vectors are returned."

  @typedoc "The format in which the embedding vectors are returned."
  @type t :: :float | :base64

  @float :float
  @base64 :base64

  @doc "32-bit floating-point numbers (default)."
  @spec float() :: t()
  def float, do: @float
  @doc "Base64-encoded string representation of the floats."
  @spec base64() :: t()
  def base64, do: @base64
end
