# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:73516780160260b48f0f858446476f02c4d37d19c77500de1a053109f5d49a60
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule LiterLlm.EmbeddingResponse do
  @moduledoc "Embedding response."

  @typedoc "Embedding response."
  @type t :: %__MODULE__{
          object: String.t() | nil,
          data: [LiterLlm.EmbeddingObject.t()],
          model: String.t() | nil,
          usage: LiterLlm.Usage.t() | nil
        }

  defstruct object: nil,
            data: [],
            model: nil,
            usage: nil
end
