# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:bd2b3dacd8f1366a80dbac220df02b6b50eadde3e00406a1dc50853ccfa69858
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule LiterLlm.EmbeddingResponse do
  @moduledoc "Embedding response."

  @typedoc "Embedding response."
  @type t :: %__MODULE__{
          object: String.t() | nil,
          data: [LiterLlm.EmbeddingObject.t()],
          model: String.t() | nil,
          usage: LiterLlm.Usage.t() | nil
        }

  defstruct object: nil,
            data: [],
            model: nil,
            usage: nil
end
