# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:b713cdc932d78474deb27590f90844c3f463beda3e2e590d8bc6c93bf009eea8
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule LiterLlm.EmbeddingObject do
  @moduledoc "A single embedding vector."

  @typedoc "A single embedding vector."
  @type t :: %__MODULE__{
          object: String.t() | nil,
          embedding: [float()],
          index: non_neg_integer()
        }

  defstruct object: nil,
            embedding: [],
            index: 0
end
