# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:cf12a91b71f7e7e78174f6741902a20de61b1e89a6a7b79a92a43f7c017e8379
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule LiterLlm.EmbeddingResponse do
  @moduledoc "Embedding response."

  @typedoc "Embedding response."
  @type t :: %__MODULE__{
          object: String.t() | nil,
          data: [LiterLlm.EmbeddingObject.t()],
          model: String.t() | nil,
          usage: LiterLlm.Usage.t() | nil
        }

  defstruct object: nil,
            data: [],
            model: nil,
            usage: nil
end
