# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:c249c70b7640c53f754d8c96cd8e49cec28afa7f81e8f316163a5ff7df9c9773
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule LiterLlm.EmbeddingFormat do
  @moduledoc "The format in which the embedding vectors are returned."

  @type t :: :float | :base64

  @float :float
  @base64 :base64

  @spec float() :: t()
  def float, do: @float
  @spec base64() :: t()
  def base64, do: @base64
end
