# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:6758b9194d544d696359c33760fe40965b16043d7a06cd384437b186a32e09a9
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule LiterLlm.EmbeddingRequest do
  @moduledoc "Embedding request."

  @typedoc "Embedding request."
  @type t :: %__MODULE__{
          model: String.t() | nil,
          input: LiterLlm.EmbeddingInput.t(),
          encoding_format: LiterLlm.EmbeddingFormat.t() | nil,
          dimensions: non_neg_integer() | nil,
          user: String.t() | nil
        }

  defstruct model: nil,
            input: :single,
            encoding_format: nil,
            dimensions: nil,
            user: nil

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
