# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:872f238d87e53196bf0612a2399cce53ed37b69e19c0bf1e94b4e196c7fbd128
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule LiterLlm.Enforcement do
  @moduledoc "How budget limits are enforced."

  @typedoc "How budget limits are enforced."
  @type t :: :hard | :soft

  @hard :hard
  @soft :soft

  @doc "Reject requests that would exceed the budget with [`LiterLlmError::BudgetExceeded`]."
  @spec hard() :: t()
  def hard, do: @hard
  @doc "Allow requests through but emit a `tracing::warn!` when the budget is exceeded."
  @spec soft() :: t()
  def soft, do: @soft
end
