# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:cf12a91b71f7e7e78174f6741902a20de61b1e89a6a7b79a92a43f7c017e8379
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule LiterLlm.Enforcement do
  @moduledoc "How budget limits are enforced."

  @typedoc "How budget limits are enforced."
  @type t :: :hard | :soft

  @hard :hard
  @soft :soft

  @doc "Reject requests that would exceed the budget with [`LiterLlmError::BudgetExceeded`]."
  @spec hard() :: t()
  def hard, do: @hard
  @doc "Allow requests through but emit a `tracing::warn!` when the budget is exceeded."
  @spec soft() :: t()
  def soft, do: @soft
end
