# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:08c1bb2c4f0eaa6c849932bec18c1ec027657560454d5a52b75a93d8416c7e0b
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule LiterLlm.FileListResponse do
  @moduledoc "Response from listing files."

  @typedoc "Response from listing files."
  @type t :: %__MODULE__{
          object: String.t() | nil,
          data: [LiterLlm.FileObject.t()],
          has_more: boolean() | nil
        }

  defstruct object: nil,
            data: [],
            has_more: nil

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
