# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:6b599540f61343f1a704b9a1de642f8c88bf179e7ecd45b1d65ecafe7cf52aaa
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule LiterLlm.FileObject do
  @moduledoc "An uploaded file object."

  @typedoc "An uploaded file object."
  @type t :: %__MODULE__{
          id: String.t() | nil,
          object: String.t() | nil,
          bytes: non_neg_integer(),
          created_at: non_neg_integer(),
          filename: String.t() | nil,
          purpose: String.t() | nil,
          status: String.t() | nil
        }

  defstruct id: nil,
            object: nil,
            bytes: 0,
            created_at: 0,
            filename: nil,
            purpose: nil,
            status: nil

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
