# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:9165e93835c879eb96366cf27357e9668eaba7d6fc2e761c5e0258daa7acfce9
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule LiterLlm.FunctionCall do
  @moduledoc "Function call details."

  @typedoc "Function call details."
  @type t :: %__MODULE__{
          name: String.t() | nil,
          arguments: String.t() | nil
        }

  defstruct name: nil,
            arguments: nil
end
