# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:cf12a91b71f7e7e78174f6741902a20de61b1e89a6a7b79a92a43f7c017e8379
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule LiterLlm.FunctionCall do
  @moduledoc "Function call details."

  @typedoc "Function call details."
  @type t :: %__MODULE__{
          name: String.t() | nil,
          arguments: String.t() | nil
        }

  defstruct name: nil,
            arguments: nil
end
