# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:ce26b449cd9aa87ae1be78e99dfc29ba9ad58c01f6fb0a125dfe6e381e526b0e
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule LiterLlm.FunctionMessage do
  @moduledoc "Deprecated legacy function-role message body."

  @typedoc "Deprecated legacy function-role message body."
  @type t :: %__MODULE__{
          content: String.t() | nil,
          name: String.t() | nil
        }

  defstruct content: nil,
            name: nil

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
