# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:93ea9cde21caefce519fb51b31b74f1ff8f80b3e0a0a13ceae3416d9ab414c02
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule LiterLlm.FunctionDefinition do
  @moduledoc false

  defstruct name: "",
            description: nil,
            parameters: nil,
            strict: nil
end
