# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:9165e93835c879eb96366cf27357e9668eaba7d6fc2e761c5e0258daa7acfce9
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule LiterLlm.FunctionDefinition do
  @moduledoc "Function definition exposed to the model."

  @typedoc "Function definition exposed to the model."
  @type t :: %__MODULE__{
          name: String.t() | nil,
          description: String.t() | nil,
          parameters: String.t() | nil,
          strict: boolean() | nil
        }

  defstruct name: nil,
            description: nil,
            parameters: nil,
            strict: nil
end
