# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:3347eb513dffebe6f73ec656acda7c684c0454add49a90cee6f47303389d1d03
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule LiterLlm.FunctionDefinition do
  @moduledoc "Function definition exposed to the model."

  @typedoc "Function definition exposed to the model."
  @type t :: %__MODULE__{
          name: String.t() | nil,
          description: String.t() | nil,
          parameters: String.t() | nil,
          strict: boolean() | nil
        }

  defstruct name: nil,
            description: nil,
            parameters: nil,
            strict: nil
end
