# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:9165e93835c879eb96366cf27357e9668eaba7d6fc2e761c5e0258daa7acfce9
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule LiterLlm.HealthStatus do
  @moduledoc "The result of a single health probe."

  @typedoc "The result of a single health probe."
  @type t :: :healthy | :unhealthy

  @healthy :healthy
  @unhealthy :unhealthy

  @doc "The probe succeeded; the upstream is reachable."
  @spec healthy() :: t()
  def healthy, do: @healthy
  @doc "The probe failed; the upstream may be down."
  @spec unhealthy() :: t()
  def unhealthy, do: @unhealthy
end
