# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:7bacb53ba62128cddbad2af9594a8f7a0d67daee3cb1a21a2569382109274fca
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule LiterLlm.HealthStatus do
  @moduledoc "The result of a single health probe."

  @typedoc "The result of a single health probe."
  @type t :: :healthy | :unhealthy

  @healthy :healthy
  @unhealthy :unhealthy

  @doc "The probe succeeded; the upstream is reachable."
  @spec healthy() :: t()
  def healthy, do: @healthy
  @doc "The probe failed; the upstream may be down."
  @spec unhealthy() :: t()
  def unhealthy, do: @unhealthy
end
