# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:7499d97bdecec9ba068f9bf13fdaad6528c82e061c3755d3ae2763715948c3dd
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule LiterLlm.Image do
  @moduledoc "A single generated image, returned as either a URL or base64 data."

  @typedoc "A single generated image, returned as either a URL or base64 data."
  @type t :: %__MODULE__{
          url: String.t() | nil,
          b64_json: String.t() | nil,
          revised_prompt: String.t() | nil
        }

  defstruct url: nil,
            b64_json: nil,
            revised_prompt: nil

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
