# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:b713cdc932d78474deb27590f90844c3f463beda3e2e590d8bc6c93bf009eea8
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule LiterLlm.ImageUrl do
  @moduledoc "An image URL reference with optional detail level for processing."

  @typedoc "An image URL reference with optional detail level for processing."
  @type t :: %__MODULE__{
          url: String.t() | nil,
          detail: String.t() | nil | nil
        }

  defstruct url: nil,
            detail: nil

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
