# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:69a04416c71eb4cade67cf25625c5b91e094cb973691ba0df380129ecdcd65a5
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule LiterLlm.Image do
  @moduledoc "A single generated image, returned as either a URL or base64 data."

  @typedoc "A single generated image, returned as either a URL or base64 data."
  @type t :: %__MODULE__{
          url: String.t() | nil,
          b64_json: String.t() | nil,
          revised_prompt: String.t() | nil
        }

  defstruct url: nil,
            b64_json: nil,
            revised_prompt: nil

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
