# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:c249c70b7640c53f754d8c96cd8e49cec28afa7f81e8f316163a5ff7df9c9773
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule LiterLlm.ImagesResponse do
  @moduledoc "Response containing generated images."

  defstruct created: 0,
            data: []
end
