# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:df5eeae57a0d423dff9704fba23abed5d99ed92046755632ad83e28a1a99eba7
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule LiterLlm.ImageDetail do
  @moduledoc "Image detail level controlling token cost and processing."

  @typedoc "Image detail level controlling token cost and processing."
  @type t :: :low | :high | :auto

  @low :low
  @high :high
  @auto :auto

  @doc "Low detail: scales image to 512x512, uses fewer tokens."
  @spec low() :: t()
  def low, do: @low
  @doc "High detail: processes up to 2x2 grid of tiles, higher token cost."
  @spec high() :: t()
  def high, do: @high
  @doc "Auto: model chooses low or high based on image dimensions."
  @spec auto() :: t()
  def auto, do: @auto

  @doc "Returns the serde wire value this variant carries on the JSON boundary (see `wire_variant_value` in alef's naming module) -- distinct from the atom's Elixir spelling."
  @spec wire_value(t()) :: String.t()
  def wire_value(:low), do: "low"
  def wire_value(:high), do: "high"
  def wire_value(:auto), do: "auto"
end
