# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:08c41f5c62ca562289e71f634aceb51e35245585ce7b878b7bc1fe3a75443f48
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule LiterLlm.ImagesResponse do
  @moduledoc "Response containing generated images."

  @typedoc "Response containing generated images."
  @type t :: %__MODULE__{
          created: non_neg_integer(),
          data: [LiterLlm.Image.t()]
        }

  defstruct created: 0,
            data: []

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
