# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:37e3834995f420ec9090be4603859dbb1e7f38fb01b19c2dcc030d4ceb48c21a
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule LiterLlm.ImageUrl do
  @moduledoc false

  defstruct url: "",
            detail: :low
end
