# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:a0680047d1cb82a7665c3b530c63b831d8f1cc7780b2a09338cd7f966f2b2d05
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule LiterLlm.ImagesResponse do
  @moduledoc "Response containing generated images."

  @typedoc "Response containing generated images."
  @type t :: %__MODULE__{
          created: non_neg_integer(),
          data: [LiterLlm.Image.t()]
        }

  defstruct created: 0,
            data: []

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
