# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:cf12a91b71f7e7e78174f6741902a20de61b1e89a6a7b79a92a43f7c017e8379
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule LiterLlm.IntentPrototype do
  @moduledoc "An intent prototype: `(intent_name, prototype_embedding, target_model_id)`."

  @typedoc "An intent prototype: `(intent_name, prototype_embedding, target_model_id)`."
  @type t :: %__MODULE__{
          name: String.t() | nil,
          embedding: [float()],
          model: String.t() | nil
        }

  defstruct name: nil,
            embedding: [],
            model: nil
end
