# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:c4a2685828fd8e43fc34b1056bf54b5bcbb69f4336ad3e322acda2512554bb63
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule LiterLlm.IntentPrototype do
  @moduledoc "An intent prototype: `(intent_name, prototype_embedding, target_model_id)`."

  @typedoc "An intent prototype: `(intent_name, prototype_embedding, target_model_id)`."
  @type t :: %__MODULE__{
          name: String.t() | nil,
          embedding: [float()],
          model: String.t() | nil
        }

  defstruct name: nil,
            embedding: [],
            model: nil
end
