# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:59cac5c166131b797b3063f3b19ba8b8f8a0d1a100f0b2a219f1455f5ab63f85
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule LiterLlm.IntentPrototype do
  @moduledoc "An intent prototype: `(intent_name, prototype_embedding, target_model_id)`."

  @typedoc "An intent prototype: `(intent_name, prototype_embedding, target_model_id)`."
  @type t :: %__MODULE__{
          name: String.t() | nil,
          embedding: [float()],
          model: String.t() | nil
        }

  defstruct name: nil,
            embedding: [],
            model: nil
end
