# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:2eca3c11d9a022a40e87e5dc8ab2fb67dceaaffe3934a796584a2df4dde65f9a
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule LiterLlm.JsonSchemaFormat do
  @moduledoc "JSON Schema specification for constrained output."

  @typedoc "JSON Schema specification for constrained output."
  @type t :: %__MODULE__{
          name: String.t() | nil,
          description: String.t() | nil,
          schema: String.t() | nil,
          strict: boolean() | nil
        }

  defstruct name: nil,
            description: nil,
            schema: nil,
            strict: nil

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
