# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:2a68e08263f0365b9974295f22362275ecf1af45ece7b6447d83598be10111bc
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule LiterLlm.JsonSchemaFormat do
  @moduledoc "JSON Schema specification for constrained output."

  @typedoc "JSON Schema specification for constrained output."
  @type t :: %__MODULE__{
          name: String.t() | nil,
          description: String.t() | nil,
          schema: String.t() | nil,
          strict: boolean() | nil
        }

  defstruct name: nil,
            description: nil,
            schema: nil,
            strict: nil

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
