# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:7bd81e55f9837bfc194994b3cb3d4a5393be4d5a8192725b8d42d7b537b28562
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule LiterLlm.LlmProviderConfig do
  @moduledoc "A custom provider configuration entry."

  @typedoc "A custom provider configuration entry."
  @type t :: %__MODULE__{
          name: String.t() | nil,
          base_url: String.t() | nil,
          auth_header: String.t() | nil,
          model_prefixes: [String.t()]
        }

  defstruct name: nil,
            base_url: nil,
            auth_header: nil,
            model_prefixes: []

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
