# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:f296f8c2e6b3ca5a29028344cfd129ba47a0393711d3650534e13f04ed55bf56
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule LiterLlm.LlmInFlightLimitConfig do
  @moduledoc "Global per-client in-flight provider request limit."

  @typedoc "Global per-client in-flight provider request limit."
  @type t :: %__MODULE__{
          max_in_flight: non_neg_integer() | nil
        }

  defstruct max_in_flight: nil

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
