# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:4812387bbbdf51183842f96315ac52a7efcd1e2c9c46ffb560eb25dc13e8dd49
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule LiterLlm.LlmProviderConfig do
  @moduledoc "A custom provider configuration entry."

  @typedoc "A custom provider configuration entry."
  @type t :: %__MODULE__{
          name: String.t() | nil,
          base_url: String.t() | nil,
          auth_header: String.t() | nil,
          model_prefixes: [String.t()]
        }

  defstruct name: nil,
            base_url: nil,
            auth_header: nil,
            model_prefixes: []

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
