# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:7499d97bdecec9ba068f9bf13fdaad6528c82e061c3755d3ae2763715948c3dd
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule LiterLlm.LlmCacheConfig do
  @moduledoc "Response cache configuration."

  @typedoc "Response cache configuration."
  @type t :: %__MODULE__{
          max_entries: non_neg_integer() | nil,
          ttl_seconds: non_neg_integer() | nil,
          backend: String.t() | nil,
          backend_config: map() | nil
        }

  defstruct max_entries: nil,
            ttl_seconds: nil,
            backend: nil,
            backend_config: nil

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
