# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:af7468ada2cd9571058cc95cc9883fc5ba83e0daaefa883551b310ba55f8dd2b
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule LiterLlm.LlmConfig do
  @moduledoc """
  Canonical configuration for an LLM client.

  All fields except `model` are optional so that partially-specified
  configs (e.g. from environment-driven defaults) round-trip cleanly.
  Convert to a runtime client configuration via
  [`LlmConfig::into_client_builder`].

  `temperature` and `max_tokens` are request-time parameters rather than
  client-level settings; they are carried on this struct for callers to
  read when building individual requests, and are intentionally **not**
  mapped by [`LlmConfig::into_client_builder`].
  """

  @typedoc "Canonical configuration for an LLM client."
  @type t :: %__MODULE__{
          model: String.t() | nil,
          api_key: String.t() | nil,
          base_url: String.t() | nil,
          timeout_secs: non_neg_integer() | nil,
          max_retries: non_neg_integer() | nil,
          temperature: float() | nil,
          max_tokens: non_neg_integer() | nil,
          load_env: boolean() | nil,
          headers: map() | nil,
          providers: [LiterLlm.LlmProviderConfig.t()] | nil,
          cache: LiterLlm.LlmCacheConfig.t() | nil,
          budget: LiterLlm.LlmBudgetConfig.t() | nil,
          rate_limit: LiterLlm.LlmRateLimitConfig.t() | nil,
          cost_tracking: boolean() | nil,
          tracing: boolean() | nil,
          cooldown_secs: non_neg_integer() | nil,
          health_check_secs: non_neg_integer() | nil,
          bedrock: LiterLlm.BedrockConfig.t() | nil
        }

  defstruct model: nil,
            api_key: nil,
            base_url: nil,
            timeout_secs: nil,
            max_retries: nil,
            temperature: nil,
            max_tokens: nil,
            load_env: nil,
            headers: nil,
            providers: nil,
            cache: nil,
            budget: nil,
            rate_limit: nil,
            cost_tracking: nil,
            tracing: nil,
            cooldown_secs: nil,
            health_check_secs: nil,
            bedrock: nil

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
