# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:872f238d87e53196bf0612a2399cce53ed37b69e19c0bf1e94b4e196c7fbd128
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule LiterLlm.LlmProviderConfig do
  @moduledoc "A custom provider configuration entry."

  @typedoc "A custom provider configuration entry."
  @type t :: %__MODULE__{
          name: String.t() | nil,
          base_url: String.t() | nil,
          auth_header: String.t() | nil,
          model_prefixes: [String.t()]
        }

  defstruct name: nil,
            base_url: nil,
            auth_header: nil,
            model_prefixes: []

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
