# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:872f238d87e53196bf0612a2399cce53ed37b69e19c0bf1e94b4e196c7fbd128
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule LiterLlm.Message do
  @moduledoc "A chat message in a conversation."

  @typedoc "A chat message in a conversation."
  @type t :: term()

  @type system :: %{type: :system, message: LiterLlm.SystemMessage.t()}
  @type user :: %{type: :user, message: LiterLlm.UserMessage.t()}
  @type assistant :: %{type: :assistant, message: LiterLlm.AssistantMessage.t()}
  @type tool :: %{type: :tool, message: LiterLlm.ToolMessage.t()}
  @type developer :: %{type: :developer, message: LiterLlm.DeveloperMessage.t()}
  @typedoc "Deprecated legacy function-role message; retained for API compatibility."
  @type function_variant :: %{type: :function, message: LiterLlm.FunctionMessage.t()}
end
