# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:59cac5c166131b797b3063f3b19ba8b8f8a0d1a100f0b2a219f1455f5ab63f85
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule LiterLlm.Message do
  @moduledoc "A chat message in a conversation."

  @typedoc "A chat message in a conversation."
  @type t :: term()

  @type system :: %{type: :system, message: LiterLlm.SystemMessage.t()}
  @type user :: %{type: :user, message: LiterLlm.UserMessage.t()}
  @type assistant :: %{type: :assistant, message: LiterLlm.AssistantMessage.t()}
  @type tool :: %{type: :tool, message: LiterLlm.ToolMessage.t()}
  @type developer :: %{type: :developer, message: LiterLlm.DeveloperMessage.t()}
  @typedoc "Deprecated legacy function-role message; retained for API compatibility."
  @type function_variant :: %{type: :function, message: LiterLlm.FunctionMessage.t()}
end
