# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:9ca6714382d5977ba89edd2f09addf092370c00e33d03fa288491e783ed5cc74
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule LiterLlm.Message do
  @moduledoc "A chat message in a conversation."

  @typedoc "A chat message in a conversation."
  @type t :: term()

  @type system :: %{type: :system, message: LiterLlm.SystemMessage.t()}
  @type user :: %{type: :user, message: LiterLlm.UserMessage.t()}
  @type assistant :: %{type: :assistant, message: LiterLlm.AssistantMessage.t()}
  @type tool :: %{type: :tool, message: LiterLlm.ToolMessage.t()}
  @type developer :: %{type: :developer, message: LiterLlm.DeveloperMessage.t()}
  @typedoc "Deprecated legacy function-role message; retained for API compatibility."
  @type function_variant :: %{type: :function, message: LiterLlm.FunctionMessage.t()}
end
