# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:59cac5c166131b797b3063f3b19ba8b8f8a0d1a100f0b2a219f1455f5ab63f85
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule LiterLlm.Modality do
  @moduledoc """
  Output modality requested from the model.

  Passed as `modalities: ["text", "audio"]` (OpenAI) or translated to
  `generationConfig.responseModalities` (Gemini / Vertex AI).

  # Example

  ```
  use liter_llm::types::{ChatCompletionRequest, Modality};

  let req = ChatCompletionRequest {
      model: "gpt-4o-audio-preview".into(),
      modalities: Some(vec![Modality::Text, Modality::Audio]),
      ..Default::default()
  };
  ```
  """

  @typedoc "Output modality requested from the model."
  @type t :: :text | :audio | :image

  @text :text
  @audio :audio
  @image :image

  @doc "Text output (the default for all providers)."
  @spec text() :: t()
  def text, do: @text
  @doc "Audio / speech output."
  @spec audio() :: t()
  def audio, do: @audio
  @doc "Image output (Gemini Imagen, gpt-image-1)."
  @spec image() :: t()
  def image, do: @image
end
