# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:73516780160260b48f0f858446476f02c4d37d19c77500de1a053109f5d49a60
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule LiterLlm.ModerationInput do
  @moduledoc "Input to the moderation endpoint — a single string or multiple strings."

  @typedoc "Input to the moderation endpoint — a single string or multiple strings."
  @type t :: term()

  @typedoc "Single text string."
  @type single :: %{type: :single, value: String.t()}
  @typedoc "Multiple text strings (batch moderation)."
  @type multiple :: %{type: :multiple, value: [String.t()]}
end
