# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:9c479751c0805b45ce76a17491cc7b1b4c87a95d35e5ac93b5d5d0ac4b974284
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule LiterLlm.ModelsListResponse do
  @moduledoc "Response listing available models."

  @typedoc "Response listing available models."
  @type t :: %__MODULE__{
          object: String.t() | nil,
          data: [LiterLlm.ModelObject.t()]
        }

  defstruct object: nil,
            data: []

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
