# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:803455fd6bc8b0694f4c8eb8646112509af65bb6d2754f77a385a757ab96f4ac
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule LiterLlm.ModelsListResponse do
  @moduledoc "Response listing available models."

  @typedoc "Response listing available models."
  @type t :: %__MODULE__{
          object: String.t() | nil,
          data: [LiterLlm.ModelObject.t()]
        }

  defstruct object: nil,
            data: []

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
