# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:645d8ff0f3a0ef7684f9b9ea4ce1ae251a78a2a3481ecdeabf7643c53d644bb0
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule LiterLlm.ModerationRequest do
  @moduledoc "Request to classify content for policy violations."

  @typedoc "Request to classify content for policy violations."
  @type t :: %__MODULE__{
          input: String.t() | nil,
          model: String.t() | nil
        }

  defstruct input: :single,
            model: nil

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
