# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:fa36da31183acca252f44a9e64718efb2a8abc9d828eece851bb7b505e825015
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule LiterLlm.ModelTier do
  @moduledoc """
  Public, FFI-friendly snapshot of a single context-window pricing tier,
  projected from [`PricingTier`].
  """

  @typedoc "Public, FFI-friendly snapshot of a single context-window pricing tier, projected from [`PricingTier`]."
  @type t :: %__MODULE__{
          min_context_tokens: non_neg_integer(),
          input_cost_per_token: float(),
          output_cost_per_token: float(),
          cache_read_input_token_cost: float() | nil,
          cache_creation_input_token_cost: float() | nil,
          input_cost_per_audio_token: float() | nil,
          output_cost_per_audio_token: float() | nil,
          output_cost_per_reasoning_token: float() | nil
        }

  defstruct min_context_tokens: 0,
            input_cost_per_token: 0.0,
            output_cost_per_token: 0.0,
            cache_read_input_token_cost: nil,
            cache_creation_input_token_cost: nil,
            input_cost_per_audio_token: nil,
            output_cost_per_audio_token: nil,
            output_cost_per_reasoning_token: nil

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
