# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:cf12a91b71f7e7e78174f6741902a20de61b1e89a6a7b79a92a43f7c017e8379
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule LiterLlm.ModerationRequest do
  @moduledoc "Request to classify content for policy violations."

  @typedoc "Request to classify content for policy violations."
  @type t :: %__MODULE__{
          input: String.t() | nil,
          model: String.t() | nil
        }

  defstruct input: :single,
            model: nil

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
