# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:938b8ffd93c3e30d74875f875188c728addee9d4b80a97a7ac22716b3154c7c5
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule LiterLlm.ModelObject do
  @moduledoc "A model available from the API."

  @typedoc "A model available from the API."
  @type t :: %__MODULE__{
          id: String.t() | nil,
          object: String.t() | nil,
          created: non_neg_integer(),
          owned_by: String.t() | nil
        }

  defstruct id: nil,
            object: nil,
            created: 0,
            owned_by: nil

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
