# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:e92ba9467b7adf2b516f316db3fb5ab2ad377174f7db07d6b2f36a63a5771784
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule LiterLlm.ModelsListResponse do
  @moduledoc false

  defstruct object: "",
            data: []
end
