# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:e7d976d536149c26a43a6beec6c76b8731b4bd6b2c9ea8979a6d82c1ea09c5fe
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule LiterLlm.ModerationInput do
  @moduledoc "Input to the moderation endpoint — a single string or multiple strings."

  @typedoc "Input to the moderation endpoint — a single string or multiple strings."
  @type t :: term()

  @typedoc "Single text string."
  @type single :: %{type: :single, single: String.t()}
  @typedoc "Multiple text strings (batch moderation)."
  @type multiple :: %{type: :multiple, multiple: [String.t()]}

  @doc "Returns the serde wire value this variant carries on the JSON boundary (see `wire_variant_value` in alef's naming module) -- distinct from the atom's Elixir spelling."
  @spec wire_value(t()) :: String.t()
  def wire_value(:single), do: "Single"
  def wire_value(:multiple), do: "Multiple"
  def wire_value(value) when is_tuple(value), do: wire_value(elem(value, 0))
  def wire_value(value) when is_map(value), do: Map.fetch!(value, :type)

  defimpl String.Chars, for: LiterLlm.ModerationInput do
    @doc false
    def to_string(value), do: LiterLlm.ModerationInput.wire_value(value)
  end
end
