# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:872f238d87e53196bf0612a2399cce53ed37b69e19c0bf1e94b4e196c7fbd128
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule LiterLlm.ModerationResponse do
  @moduledoc "Response from the moderation endpoint."

  @typedoc "Response from the moderation endpoint."
  @type t :: %__MODULE__{
          id: String.t() | nil,
          model: String.t() | nil,
          results: [LiterLlm.ModerationResult.t()]
        }

  defstruct id: nil,
            model: nil,
            results: []
end
