# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:e182700797eb234b84246356dd1e9fbf1e9b32474e74f2baae944fa2be67bc9c
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule LiterLlm.ModerationCategories do
  @moduledoc "Boolean flags for each moderation category."

  defstruct sexual: false,
            hate: false,
            harassment: false,
            self_harm: false,
            sexual_minors: false,
            hate_threatening: false,
            violence_graphic: false,
            self_harm_intent: false,
            self_harm_instructions: false,
            harassment_threatening: false,
            violence: false
end
