# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:9c479751c0805b45ce76a17491cc7b1b4c87a95d35e5ac93b5d5d0ac4b974284
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule LiterLlm.ModerationInput do
  @moduledoc "Input to the moderation endpoint — a single string or multiple strings."

  @typedoc "Input to the moderation endpoint — a single string or multiple strings."
  @type t :: term()

  @typedoc "Single text string."
  @type single :: %{type: :single, value: String.t()}
  @typedoc "Multiple text strings (batch moderation)."
  @type multiple :: %{type: :multiple, value: [String.t()]}
end
