# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:938b8ffd93c3e30d74875f875188c728addee9d4b80a97a7ac22716b3154c7c5
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule LiterLlm.OcrDocument do
  @moduledoc "Document input for OCR — either a URL or inline base64 data."

  @typedoc "Document input for OCR — either a URL or inline base64 data."
  @type t :: term()

  @typedoc "A publicly accessible document URL."
  @type url :: %{type: :url, url: String.t()}
  @typedoc "Inline base64-encoded document data."
  @type base64 :: %{type: :base64, data: String.t(), media_type: String.t()}

  def url(url), do: {:url, %{url: url}}
  def base64(data, media_type), do: {:base64, %{data: data, media_type: media_type}}
end
