# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:938b8ffd93c3e30d74875f875188c728addee9d4b80a97a7ac22716b3154c7c5
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule LiterLlm.OcrRequest do
  @moduledoc "An OCR request."

  @typedoc "An OCR request."
  @type t :: %__MODULE__{
          model: String.t() | nil,
          document: String.t() | nil,
          pages: [non_neg_integer()] | nil,
          include_image_base64: boolean() | nil
        }

  defstruct model: nil,
            document: :url,
            pages: nil,
            include_image_base64: nil

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
