# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:8e4372454992868192ab2432ec70fb5a31b226528b5cfcff70c9dd7ebd757d82
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule LiterLlm.OcrPage do
  @moduledoc "A single page of OCR output."

  @typedoc "A single page of OCR output."
  @type t :: %__MODULE__{
          index: non_neg_integer(),
          markdown: String.t() | nil,
          images: [LiterLlm.OcrImage.t()] | nil,
          dimensions: LiterLlm.PageDimensions.t() | nil
        }

  defstruct index: 0,
            markdown: nil,
            images: nil,
            dimensions: nil
end
