# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:d37ea66d954ad374b69c65cfd4aa370951e0c0c095fdc72c3a3f39389871d474
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule LiterLlm.OcrImage do
  @moduledoc "An image extracted from an OCR page."

  @typedoc "An image extracted from an OCR page."
  @type t :: %__MODULE__{
          id: String.t() | nil,
          image_base64: String.t() | nil
        }

  defstruct id: nil,
            image_base64: nil
end
