# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:7499d97bdecec9ba068f9bf13fdaad6528c82e061c3755d3ae2763715948c3dd
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule LiterLlm.OcrPage do
  @moduledoc "A single page of OCR output."

  @typedoc "A single page of OCR output."
  @type t :: %__MODULE__{
          index: non_neg_integer(),
          markdown: String.t() | nil,
          images: [LiterLlm.OcrImage.t()] | nil,
          dimensions: LiterLlm.PageDimensions.t() | nil
        }

  defstruct index: 0,
            markdown: nil,
            images: nil,
            dimensions: nil
end
