# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:34865dca3cd6792150a4ca6e86eeb54c4549c6dc83cd9a6028f9614f50c0f06f
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule LiterLlm.OcrResponse do
  @moduledoc "An OCR response."

  @typedoc "An OCR response."
  @type t :: %__MODULE__{
          pages: [LiterLlm.OcrPage.t()],
          model: String.t() | nil,
          usage: LiterLlm.Usage.t() | nil
        }

  defstruct pages: [],
            model: nil,
            usage: nil
end
