# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:c50f97ca46dc88eb74c481305678c4dcf5c8d53d347c592b12fe86010f8f5b33
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule LiterLlm.OcrResponse do
  @moduledoc "An OCR response."

  @typedoc "An OCR response."
  @type t :: %__MODULE__{
          pages: [LiterLlm.OcrPage.t()],
          model: String.t() | nil,
          usage: LiterLlm.Usage.t() | nil
        }

  defstruct pages: [],
            model: nil,
            usage: nil
end
