# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:7bacb53ba62128cddbad2af9594a8f7a0d67daee3cb1a21a2569382109274fca
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule LiterLlm.OcrImage do
  @moduledoc "An image extracted from an OCR page."

  @typedoc "An image extracted from an OCR page."
  @type t :: %__MODULE__{
          id: String.t() | nil,
          image_base64: String.t() | nil
        }

  defstruct id: nil,
            image_base64: nil
end
