# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:bf3c4e433fad1a74ae8d40b12cc76c9f3e538dd7ad6d265178dbfcc18d8bfaf9
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule LiterLlm.OcrImage do
  @moduledoc "An image extracted from an OCR page."

  @typedoc "An image extracted from an OCR page."
  @type t :: %__MODULE__{
          id: String.t() | nil,
          image_base64: String.t() | nil
        }

  defstruct id: nil,
            image_base64: nil
end
