# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:9ca6714382d5977ba89edd2f09addf092370c00e33d03fa288491e783ed5cc74
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule LiterLlm.PageDimensions do
  @moduledoc "Page dimensions in pixels."

  @typedoc "Page dimensions in pixels."
  @type t :: %__MODULE__{
          width: non_neg_integer(),
          height: non_neg_integer()
        }

  defstruct width: 0,
            height: 0
end
