# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:7499d97bdecec9ba068f9bf13fdaad6528c82e061c3755d3ae2763715948c3dd
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule LiterLlm.RateLimitConfig do
  @moduledoc "Configuration for per-model rate limits."

  @typedoc "Configuration for per-model rate limits."
  @type t :: %__MODULE__{
          rpm: non_neg_integer() | nil,
          tpm: non_neg_integer() | nil,
          window: non_neg_integer()
        }

  defstruct rpm: nil,
            tpm: nil,
            window: 60_000

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
