# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:9c479751c0805b45ce76a17491cc7b1b4c87a95d35e5ac93b5d5d0ac4b974284
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule LiterLlm.RateLimitConfig do
  @moduledoc "Configuration for per-model rate limits."

  @typedoc "Configuration for per-model rate limits."
  @type t :: %__MODULE__{
          rpm: non_neg_integer() | nil,
          tpm: non_neg_integer() | nil,
          window: non_neg_integer()
        }

  defstruct rpm: nil,
            tpm: nil,
            window: 60_000

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
