# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:cf12a91b71f7e7e78174f6741902a20de61b1e89a6a7b79a92a43f7c017e8379
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule LiterLlm.ReasoningEffort do
  @moduledoc "Controls how much reasoning effort the model should use."

  @typedoc "Controls how much reasoning effort the model should use."
  @type t :: :low | :medium | :high

  @low :low
  @medium :medium
  @high :high

  @spec low() :: t()
  def low, do: @low
  @spec medium() :: t()
  def medium, do: @medium
  @spec high() :: t()
  def high, do: @high
end
