# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:8b5ee46e404fa78f674657b5f45f48187cb9f8562009cc5ce61700fb1d2745e9
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule LiterLlm.ReasoningEffort do
  @moduledoc "Controls how much reasoning effort the model should use."

  @typedoc "Controls how much reasoning effort the model should use."
  @type t :: :low | :medium | :high | :minimal | :max

  @low :low
  @medium :medium
  @high :high
  @minimal :minimal
  @max :max

  @spec low() :: t()
  def low, do: @low
  @spec medium() :: t()
  def medium, do: @medium
  @spec high() :: t()
  def high, do: @high
  @spec minimal() :: t()
  def minimal, do: @minimal
  @spec max() :: t()
  def max, do: @max

  @doc "Returns the serde wire value this variant carries on the JSON boundary (see `wire_variant_value` in alef's naming module) -- distinct from the atom's Elixir spelling."
  @spec wire_value(t()) :: String.t()
  def wire_value(:low), do: "low"
  def wire_value(:medium), do: "medium"
  def wire_value(:high), do: "high"
  def wire_value(:minimal), do: "minimal"
  def wire_value(:max), do: "max"
end
