# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:645d8ff0f3a0ef7684f9b9ea4ce1ae251a78a2a3481ecdeabf7643c53d644bb0
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule LiterLlm.ReasoningEffort do
  @moduledoc "Controls how much reasoning effort the model should use."

  @typedoc "Controls how much reasoning effort the model should use."
  @type t :: :low | :medium | :high

  @low :low
  @medium :medium
  @high :high

  @spec low() :: t()
  def low, do: @low
  @spec medium() :: t()
  def medium, do: @medium
  @spec high() :: t()
  def high, do: @high
end
