# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:9165e93835c879eb96366cf27357e9668eaba7d6fc2e761c5e0258daa7acfce9
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule LiterLlm.RefreshOutcome do
  @moduledoc "Result of a [`refresh_catalog`] call."

  @typedoc "Result of a [`refresh_catalog`] call."
  @type t :: :disabled | :from_cache | :fetched

  @disabled :disabled
  @from_cache :from_cache
  @fetched :fetched

  @doc "`config.enabled` was `false`; no network, filesystem, or overlay activity occurred."
  @spec disabled() :: t()
  def disabled, do: @disabled
  @doc "The on-disk cache was fresh (age < `ttl_seconds`); the overlay was installed from the cached file without a network request."
  @spec from_cache() :: t()
  def from_cache, do: @from_cache

  @doc "The catalog was fetched over the network, the cache file was (best-effort) refreshed, and the overlay was installed from the fetched catalog."
  @spec fetched() :: t()
  def fetched, do: @fetched
end
