# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:2b1507ab374c09ad92da13875386552ada01daebc2924e40f0c58d9c089803b1
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule LiterLlm.RefreshOutcome do
  @moduledoc "Result of a [`refresh_catalog`] call."

  @typedoc "Result of a [`refresh_catalog`] call."
  @type t :: :disabled | :from_cache | :fetched

  @disabled :disabled
  @from_cache :from_cache
  @fetched :fetched

  @doc "`config.enabled` was `false`; no network, filesystem, or overlay activity occurred."
  @spec disabled() :: t()
  def disabled, do: @disabled
  @doc "The on-disk cache was fresh (age < `ttl_seconds`); the overlay was installed from the cached file without a network request."
  @spec from_cache() :: t()
  def from_cache, do: @from_cache

  @doc "The catalog was fetched over the network, the cache file was (best-effort) refreshed, and the overlay was installed from the fetched catalog."
  @spec fetched() :: t()
  def fetched, do: @fetched
end
