# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:938b8ffd93c3e30d74875f875188c728addee9d4b80a97a7ac22716b3154c7c5
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule LiterLlm.RerankDocument do
  @moduledoc "A document to be reranked — either a plain string or an object with a text field."

  @typedoc "A document to be reranked — either a plain string or an object with a text field."
  @type t :: term()

  @typedoc "Plain text document content."
  @type text :: %{type: :text, value: String.t()}
  @typedoc "Document with explicit text field (may include metadata)."
  @type object :: %{type: :object, text: String.t()}

  def object(text), do: {:object, %{text: text}}
end
