# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:998936be827a7a2a928853692102405a428793e675e0fbd7b85cbda6a38a452b
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule LiterLlm.RerankResponse do
  @moduledoc "Response from the rerank endpoint."

  defstruct id: nil,
            results: [],
            meta: nil
end
