# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:645d8ff0f3a0ef7684f9b9ea4ce1ae251a78a2a3481ecdeabf7643c53d644bb0
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule LiterLlm.RerankRequest do
  @moduledoc "Request to rerank documents by relevance to a query."

  @typedoc "Request to rerank documents by relevance to a query."
  @type t :: %__MODULE__{
          model: String.t() | nil,
          query: String.t() | nil,
          documents: [String.t() | nil],
          top_n: non_neg_integer() | nil,
          return_documents: boolean() | nil
        }

  defstruct model: nil,
            query: nil,
            documents: [],
            top_n: nil,
            return_documents: nil

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
