# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:1a48c89f7e283a3bfdb8280092b1653915e4fdba612f2a4c3a90c5164e5e8d26
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule LiterLlm.RerankResponse do
  @moduledoc "Response from the rerank endpoint."

  @typedoc "Response from the rerank endpoint."
  @type t :: %__MODULE__{
          id: String.t() | nil,
          results: [LiterLlm.RerankResult.t()],
          meta: String.t() | nil
        }

  defstruct id: nil,
            results: [],
            meta: nil
end
