# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:645d8ff0f3a0ef7684f9b9ea4ce1ae251a78a2a3481ecdeabf7643c53d644bb0
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule LiterLlm.RerankResponse do
  @moduledoc "Response from the rerank endpoint."

  @typedoc "Response from the rerank endpoint."
  @type t :: %__MODULE__{
          id: String.t() | nil,
          results: [LiterLlm.RerankResult.t()],
          meta: String.t() | nil
        }

  defstruct id: nil,
            results: [],
            meta: nil
end
