# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:b713cdc932d78474deb27590f90844c3f463beda3e2e590d8bc6c93bf009eea8
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule LiterLlm.ResponseTool do
  @moduledoc "A tool available for the response request."

  @typedoc "A tool available for the response request."
  @type t :: %__MODULE__{
          tool_type: String.t() | nil,
          config: String.t() | nil
        }

  defstruct tool_type: nil,
            config: nil

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
