# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:b53504dc5947db565877bda290b9e5630ad969913aabbd9d83a020b028702ef7
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule LiterLlm.ResponseUsage do
  @moduledoc "Token usage for a response."

  @typedoc "Token usage for a response."
  @type t :: %__MODULE__{
          input_tokens: non_neg_integer(),
          output_tokens: non_neg_integer(),
          total_tokens: non_neg_integer()
        }

  defstruct input_tokens: 0,
            output_tokens: 0,
            total_tokens: 0

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
