# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:d37ea66d954ad374b69c65cfd4aa370951e0c0c095fdc72c3a3f39389871d474
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule LiterLlm.ResponseObject do
  @moduledoc "Response from a structured response request."

  @typedoc "Response from a structured response request."
  @type t :: %__MODULE__{
          id: String.t() | nil,
          object: String.t() | nil,
          created_at: non_neg_integer(),
          model: String.t() | nil,
          status: String.t() | nil,
          output: [LiterLlm.ResponseOutputItem.t()],
          usage: LiterLlm.ResponseUsage.t() | nil,
          error: String.t() | nil
        }

  defstruct id: nil,
            object: nil,
            created_at: 0,
            model: nil,
            status: nil,
            output: [],
            usage: nil,
            error: nil

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
