# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:59cac5c166131b797b3063f3b19ba8b8f8a0d1a100f0b2a219f1455f5ab63f85
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule LiterLlm.ResponseOutputItem do
  @moduledoc "A single output item from the response."

  @typedoc "A single output item from the response."
  @type t :: %__MODULE__{
          item_type: String.t() | nil,
          content: String.t() | nil
        }

  defstruct item_type: nil,
            content: nil

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
