# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:7bacb53ba62128cddbad2af9594a8f7a0d67daee3cb1a21a2569382109274fca
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule LiterLlm.ResponseOutputItem do
  @moduledoc "A single output item from the response."

  @typedoc "A single output item from the response."
  @type t :: %__MODULE__{
          item_type: String.t() | nil,
          content: String.t() | nil
        }

  defstruct item_type: nil,
            content: nil

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
