# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:b713cdc932d78474deb27590f90844c3f463beda3e2e590d8bc6c93bf009eea8
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule LiterLlm.SearchResponse do
  @moduledoc "A search response."

  @typedoc "A search response."
  @type t :: %__MODULE__{
          results: [LiterLlm.SearchResult.t()],
          model: String.t() | nil
        }

  defstruct results: [],
            model: nil
end
