# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:d37ea66d954ad374b69c65cfd4aa370951e0c0c095fdc72c3a3f39389871d474
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule LiterLlm.SearchResponse do
  @moduledoc "A search response."

  @typedoc "A search response."
  @type t :: %__MODULE__{
          results: [LiterLlm.SearchResult.t()],
          model: String.t() | nil
        }

  defstruct results: [],
            model: nil
end
