# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:938b8ffd93c3e30d74875f875188c728addee9d4b80a97a7ac22716b3154c7c5
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule LiterLlm.SearchRequest do
  @moduledoc "A search request."

  @typedoc "A search request."
  @type t :: %__MODULE__{
          model: String.t() | nil,
          query: String.t() | nil,
          max_results: non_neg_integer() | nil,
          search_domain_filter: [String.t()] | nil,
          country: String.t() | nil
        }

  defstruct model: nil,
            query: nil,
            max_results: nil,
            search_domain_filter: nil,
            country: nil

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
