# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:cf12a91b71f7e7e78174f6741902a20de61b1e89a6a7b79a92a43f7c017e8379
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule LiterLlm.SearchResponse do
  @moduledoc "A search response."

  @typedoc "A search response."
  @type t :: %__MODULE__{
          results: [LiterLlm.SearchResult.t()],
          model: String.t() | nil
        }

  defstruct results: [],
            model: nil
end
