# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:d404da44f0c4cff3ed44b137b508f28c6347ba3cb04c8a67d7096d5d7c8017c8
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule LiterLlm.SpecificFunction do
  @moduledoc "Name of the specific function to invoke."

  @typedoc "Name of the specific function to invoke."
  @type t :: %__MODULE__{
          name: String.t() | nil
        }

  defstruct name: nil

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
