# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:ca320e9a8aa37e2beeeeb1c64d34e964ddbe3d2f7b9400a6680d5130a8fb50fe
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule LiterLlm.SpecificFunction do
  @moduledoc false

  defstruct name: ""
end
