# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:73516780160260b48f0f858446476f02c4d37d19c77500de1a053109f5d49a60
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule LiterLlm.SpecificToolChoice do
  @moduledoc "Directive to call a specific tool."

  @typedoc "Directive to call a specific tool."
  @type t :: %__MODULE__{
          choice_type: String.t() | nil,
          function: LiterLlm.SpecificFunction.t()
        }

  defstruct choice_type: :function,
            function: nil

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
