# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:7672c80d2af49d698dead3e88c0e79b9ee078ba13be765445c404d5d71339cc8
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule LiterLlm.StopSequence do
  @moduledoc "Stop sequence(s) that cause the model to stop generating."

  @typedoc "Stop sequence(s) that cause the model to stop generating."
  @type t :: term()

  @typedoc "Single stop sequence."
  @type single :: %{type: :single, single: String.t()}
  @typedoc "Multiple stop sequences."
  @type multiple :: %{type: :multiple, multiple: [String.t()]}

  @doc "Returns the serde wire value this variant carries on the JSON boundary (see `wire_variant_value` in alef's naming module) -- distinct from the atom's Elixir spelling."
  @spec wire_value(t()) :: String.t()
  def wire_value(:single), do: "Single"
  def wire_value(:multiple), do: "Multiple"
  def wire_value(value) when is_tuple(value), do: wire_value(elem(value, 0))
  def wire_value(value) when is_map(value), do: Map.fetch!(value, :type)

  defimpl String.Chars, for: LiterLlm.StopSequence do
    @doc false
    def to_string(value), do: LiterLlm.StopSequence.wire_value(value)
  end
end
