# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:d37ea66d954ad374b69c65cfd4aa370951e0c0c095fdc72c3a3f39389871d474
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule LiterLlm.StopSequence do
  @moduledoc "Stop sequence(s) that cause the model to stop generating."

  @typedoc "Stop sequence(s) that cause the model to stop generating."
  @type t :: term()

  @typedoc "Single stop sequence."
  @type single :: %{type: :single, value: String.t()}
  @typedoc "Multiple stop sequences."
  @type multiple :: %{type: :multiple, value: [String.t()]}
end
