# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:9ca6714382d5977ba89edd2f09addf092370c00e33d03fa288491e783ed5cc74
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule LiterLlm.StopSequence do
  @moduledoc "Stop sequence(s) that cause the model to stop generating."

  @typedoc "Stop sequence(s) that cause the model to stop generating."
  @type t :: term()

  @typedoc "Single stop sequence."
  @type single :: %{type: :single, value: String.t()}
  @typedoc "Multiple stop sequences."
  @type multiple :: %{type: :multiple, value: [String.t()]}
end
