# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:135e0945bdbc08d65a3e384f8a91a3d6f98b969b7ef9ea9def361b6d2bd8be72
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule LiterLlm.StreamFormat do
  @moduledoc """
  The streaming wire format a provider uses for its response stream.

  Most providers use standard Server-Sent Events (SSE).  AWS Bedrock uses
  a proprietary binary EventStream framing.

  Deserialized from the `streaming_format` JSON field via [`serde`].
  """

  @typedoc "The streaming wire format a provider uses for its response stream."
  @type t :: :sse | :aws_event_stream

  @sse :sse
  @aws_event_stream :aws_event_stream

  @doc "Standard Server-Sent Events (text/event-stream)."
  @spec sse() :: t()
  def sse, do: @sse
  @doc "AWS EventStream binary framing (application/vnd.amazon.eventstream)."
  @spec aws_event_stream() :: t()
  def aws_event_stream, do: @aws_event_stream

  @doc "Returns the serde wire value this variant carries on the JSON boundary (see `wire_variant_value` in alef's naming module) -- distinct from the atom's Elixir spelling."
  @spec wire_value(t()) :: String.t()
  def wire_value(:sse), do: "sse"
  def wire_value(:aws_event_stream), do: "aws_event_stream"
end
