# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:af7468ada2cd9571058cc95cc9883fc5ba83e0daaefa883551b310ba55f8dd2b
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule LiterLlm.StreamFunctionCall do
  @moduledoc "Partial function call details in a stream."

  @typedoc "Partial function call details in a stream."
  @type t :: %__MODULE__{
          name: String.t() | nil,
          arguments: String.t() | nil
        }

  defstruct name: nil,
            arguments: nil

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
