# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:73516780160260b48f0f858446476f02c4d37d19c77500de1a053109f5d49a60
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule LiterLlm.StreamChoice do
  @moduledoc "A streaming choice with incremental delta."

  @typedoc "A streaming choice with incremental delta."
  @type t :: %__MODULE__{
          index: non_neg_integer(),
          delta: LiterLlm.StreamDelta.t(),
          finish_reason: String.t() | nil | nil
        }

  defstruct index: 0,
            delta: nil,
            finish_reason: nil

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
