# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:9c479751c0805b45ce76a17491cc7b1b4c87a95d35e5ac93b5d5d0ac4b974284
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule LiterLlm.StreamFormat do
  @moduledoc """
  The streaming wire format a provider uses for its response stream.

  Most providers use standard Server-Sent Events (SSE).  AWS Bedrock uses
  a proprietary binary EventStream framing.

  Deserialized from the `streaming_format` JSON field via [`serde`].
  """

  @typedoc "The streaming wire format a provider uses for its response stream."
  @type t :: :sse | :aws_event_stream

  @sse :sse
  @aws_event_stream :aws_event_stream

  @doc "Standard Server-Sent Events (text/event-stream)."
  @spec sse() :: t()
  def sse, do: @sse
  @doc "AWS EventStream binary framing (application/vnd.amazon.eventstream)."
  @spec aws_event_stream() :: t()
  def aws_event_stream, do: @aws_event_stream
end
