# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:99daeeaedf2dd1799ee3a8f96291e3564af1f33d05160b8a6388b88b37d386b9
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule LiterLlm.StreamFunctionCall do
  @moduledoc "Partial function call details in a stream."

  @typedoc "Partial function call details in a stream."
  @type t :: %__MODULE__{
          name: String.t() | nil,
          arguments: String.t() | nil
        }

  defstruct name: nil,
            arguments: nil

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
