# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:938b8ffd93c3e30d74875f875188c728addee9d4b80a97a7ac22716b3154c7c5
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule LiterLlm.StreamToolCall do
  @moduledoc "A streaming tool call being built incrementally."

  @typedoc "A streaming tool call being built incrementally."
  @type t :: %__MODULE__{
          index: non_neg_integer(),
          id: String.t() | nil,
          call_type: String.t() | nil | nil,
          function: LiterLlm.StreamFunctionCall.t() | nil
        }

  defstruct index: 0,
            id: nil,
            call_type: nil,
            function: nil

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
