# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:050e1a91cafca5c497990a10ce4befa88b2400fd25d0e8afb8b841a165d0f2e8
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule LiterLlm.StreamDelta do
  @moduledoc false

  defstruct role: "",
            content: "",
            tool_calls: [],
            function_call: nil,
            refusal: ""
end
