# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:7bacb53ba62128cddbad2af9594a8f7a0d67daee3cb1a21a2569382109274fca
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule LiterLlm.SystemMessage do
  @moduledoc "System message guiding model behavior for the entire conversation."

  @typedoc "System message guiding model behavior for the entire conversation."
  @type t :: %__MODULE__{
          content: String.t() | nil,
          name: String.t() | nil
        }

  defstruct content: :text,
            name: nil

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
