# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:b78894850eb4fcc215dc554941c101bc8b76a09f21ad40c1e4366e99a9f794ef
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule LiterLlm.SystemMessage do
  @moduledoc "System message guiding model behavior for the entire conversation."

  @typedoc "System message guiding model behavior for the entire conversation."
  @type t :: %__MODULE__{
          content: LiterLlm.UserContent.t(),
          name: String.t() | nil
        }

  defstruct content: :text,
            name: nil

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
