# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:36557f24e3e15903248ddc2599408b6a6998365982bef8a222da98935237f9c0
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule LiterLlm.ToolChoice do
  @moduledoc "Tool usage mode or a specific tool to call."

  @typedoc "Tool usage mode or a specific tool to call."
  @type t :: term()

  @typedoc "Predefined mode: auto, required, or none."
  @type mode :: %{type: :mode, value: map()}
  @typedoc "Force a specific tool to be called."
  @type specific :: %{type: :specific, tool_choice: LiterLlm.SpecificToolChoice.t()}
end
