# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:9ca6714382d5977ba89edd2f09addf092370c00e33d03fa288491e783ed5cc74
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule LiterLlm.ToolCall do
  @moduledoc "A tool call the model wants to execute."

  @typedoc "A tool call the model wants to execute."
  @type t :: %__MODULE__{
          id: String.t() | nil,
          call_type: String.t() | nil,
          function: LiterLlm.FunctionCall.t()
        }

  defstruct id: nil,
            call_type: :function,
            function: nil
end
