# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:5aa1384c5f1baab70c074884d1af53cbc9055b235b200c9ac67f45071cacd30b
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule LiterLlm.ToolMessage do
  @moduledoc "Tool execution result returned to the model."

  @typedoc "Tool execution result returned to the model."
  @type t :: %__MODULE__{
          content: LiterLlm.UserContent.t(),
          tool_call_id: String.t() | nil,
          name: String.t() | nil
        }

  defstruct content: :text,
            tool_call_id: nil,
            name: nil

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
