# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:a4c9f25991a9f9a1aa5e128f70a69c2cc77e7c1eab7f8339a88aab64454303e3
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule LiterLlm.ToolChoice do
  @moduledoc "Tool usage mode or a specific tool to call."

  @typedoc "Tool usage mode or a specific tool to call."
  @type t :: term()

  @typedoc "Predefined mode: auto, required, or none."
  @type mode :: %{type: :mode, value: map()}
  @typedoc "Force a specific tool to be called."
  @type specific :: %{type: :specific, tool_choice: LiterLlm.SpecificToolChoice.t()}
end
