# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:9165e93835c879eb96366cf27357e9668eaba7d6fc2e761c5e0258daa7acfce9
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule LiterLlm.ToolMessage do
  @moduledoc "Tool execution result returned to the model."

  @typedoc "Tool execution result returned to the model."
  @type t :: %__MODULE__{
          content: String.t() | nil,
          tool_call_id: String.t() | nil,
          name: String.t() | nil
        }

  defstruct content: :text,
            tool_call_id: nil,
            name: nil

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
