# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:cf12a91b71f7e7e78174f6741902a20de61b1e89a6a7b79a92a43f7c017e8379
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule LiterLlm.ToolChoiceMode do
  @moduledoc "Tool choice mode."

  @typedoc "Tool choice mode."
  @type t :: :auto | :required | :none

  @auto :auto
  @required :required
  @none :none

  @doc "Model may or may not call tools; default behavior."
  @spec auto() :: t()
  def auto, do: @auto
  @doc "Model must call at least one tool."
  @spec required() :: t()
  def required, do: @required
  @doc "Model must not call any tools."
  @spec none() :: t()
  def none, do: @none
end
