# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:90eeebefa7d5181f3b93fd28b220443f5552a03cf6bb90b21219eaae791aa366
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule LiterLlm.ToolChoiceMode do
  @moduledoc "Tool choice mode."

  @typedoc "Tool choice mode."
  @type t :: :auto | :required | :none

  @auto :auto
  @required :required
  @none :none

  @doc "Model may or may not call tools; default behavior."
  @spec auto() :: t()
  def auto, do: @auto
  @doc "Model must call at least one tool."
  @spec required() :: t()
  def required, do: @required
  @doc "Model must not call any tools."
  @spec none() :: t()
  def none, do: @none

  @doc "Returns the serde wire value this variant carries on the JSON boundary (see `wire_variant_value` in alef's naming module) -- distinct from the atom's Elixir spelling."
  @spec wire_value(t()) :: String.t()
  def wire_value(:auto), do: "auto"
  def wire_value(:required), do: "required"
  def wire_value(:none), do: "none"
end
