# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:01fe2918b77999989a48ba5a3728056aa32eaf3458e4cac5c8e6a32b97d0af77
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule LiterLlm.ToolType do
  @moduledoc """
  The type discriminator for tool/tool-call objects.

  Per the OpenAI spec this is always `"function"`. Using an enum enforces
  that constraint at the type level and rejects any other value on
  deserialization.
  """

  @typedoc "The type discriminator for tool/tool-call objects."
  @type t :: :function

  @function :function

  @spec function() :: t()
  def function, do: @function
end
