# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:a1f7460b967c33a745848bdad4c62e02e2e6e345aac9988053fe08a3de9afc46
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule LiterLlm.ToolType do
  @moduledoc """
  The type discriminator for tool/tool-call objects.

  Per the OpenAI spec this is always `"function"`. Using an enum enforces
  that constraint at the type level and rejects any other value on
  deserialization.
  """

  @typedoc "The type discriminator for tool/tool-call objects."
  @type t :: :function

  @function :function

  @spec function() :: t()
  def function, do: @function

  @doc "Returns the serde wire value this variant carries on the JSON boundary (see `wire_variant_value` in alef's naming module) -- distinct from the atom's Elixir spelling."
  @spec wire_value(t()) :: String.t()
  def wire_value(:function), do: "function"
end
