# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:cf12a91b71f7e7e78174f6741902a20de61b1e89a6a7b79a92a43f7c017e8379
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule LiterLlm.ToolCall do
  @moduledoc "A tool call the model wants to execute."

  @typedoc "A tool call the model wants to execute."
  @type t :: %__MODULE__{
          id: String.t() | nil,
          call_type: String.t() | nil,
          function: LiterLlm.FunctionCall.t()
        }

  defstruct id: nil,
            call_type: :function,
            function: nil
end
