# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:73516780160260b48f0f858446476f02c4d37d19c77500de1a053109f5d49a60
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule LiterLlm.ToolCall do
  @moduledoc "A tool call the model wants to execute."

  @typedoc "A tool call the model wants to execute."
  @type t :: %__MODULE__{
          id: String.t() | nil,
          call_type: String.t() | nil,
          function: LiterLlm.FunctionCall.t()
        }

  defstruct id: nil,
            call_type: :function,
            function: nil
end
