# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:a16f80f4ac8ed854b1a460c5bf6dd93933dd108891a712f18158c4f26c4ea656
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule LiterLlm.ToolChoiceMode do
  @moduledoc "Tool choice mode."

  @typedoc "Tool choice mode."
  @type t :: :auto | :required | :none

  @auto :auto
  @required :required
  @none :none

  @doc "Model may or may not call tools; default behavior."
  @spec auto() :: t()
  def auto, do: @auto
  @doc "Model must call at least one tool."
  @spec required() :: t()
  def required, do: @required
  @doc "Model must not call any tools."
  @spec none() :: t()
  def none, do: @none
end
