# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:72f6f3f9cc785a2e9e9e540fd463f0b52a16cb0947b8519370b16e4d2a35a849
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule LiterLlm.TranscriptionResponse do
  @moduledoc "Response from a transcription request."

  @typedoc "Response from a transcription request."
  @type t :: %__MODULE__{
          text: String.t() | nil,
          language: String.t() | nil,
          duration: float() | nil,
          segments: [LiterLlm.TranscriptionSegment.t()] | nil
        }

  defstruct text: nil,
            language: nil,
            duration: nil,
            segments: nil

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
