# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:226306216721e5767c1cab98fb0bd1afe04379ea390db30c538ae162ffbc7b9c
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule LiterLlm.TranscriptionSegment do
  @moduledoc "A segment of transcribed audio with timing information."

  defstruct id: 0,
            start: 0.0,
            end: 0.0,
            text: ""
end
