# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:44cd2027abea6a2740a9f2cac5c62055fc4843875b097b52408818427639fd20
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule LiterLlm.UserContent do
  @moduledoc false

  @type t :: term()

  @type text :: %{type: :text, value_0: term()}
  @type parts :: %{type: :parts, value_0: term()}
end
