# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:7bacb53ba62128cddbad2af9594a8f7a0d67daee3cb1a21a2569382109274fca
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule LiterLlm.UserContent do
  @moduledoc "User message content as either plain text or a list of multimodal parts."

  @typedoc "User message content as either plain text or a list of multimodal parts."
  @type t :: term()

  @typedoc "Plain text content."
  @type text :: %{type: :text, value: String.t()}
  @typedoc "Array of content parts (text, images, documents, audio)."
  @type parts :: %{type: :parts, value: [map()]}
end
