# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:645d8ff0f3a0ef7684f9b9ea4ce1ae251a78a2a3481ecdeabf7643c53d644bb0
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule LiterLlm.UserContent do
  @moduledoc "User message content as either plain text or a list of multimodal parts."

  @typedoc "User message content as either plain text or a list of multimodal parts."
  @type t :: term()

  @typedoc "Plain text content."
  @type text :: %{type: :text, value: String.t()}
  @typedoc "Array of content parts (text, images, documents, audio)."
  @type parts :: %{type: :parts, value: [map()]}
end
