# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:30fe8e78f574c3dc46153ad20807ffc871741a79865bf486c3b87977bc581739
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule LiterLlm.UserMessage do
  @moduledoc "User message in the conversation."

  @typedoc "User message in the conversation."
  @type t :: %__MODULE__{
          content: LiterLlm.UserContent.t(),
          name: String.t() | nil
        }

  defstruct content: :text,
            name: nil

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
