# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:b8ef75410ff5f472b8a3712d54b6ccfe96e4742f307f89f01d9c7b089992a95f
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule LiterLlm.UserMessage do
  @moduledoc "User message in the conversation."

  @typedoc "User message in the conversation."
  @type t :: %__MODULE__{
          content: LiterLlm.UserContent.t(),
          name: String.t() | nil
        }

  defstruct content: :text,
            name: nil

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
