# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:8030c2e69c2eb3b5473cb7b1e744e5a66b192510f9e372a9bc17ffd618d6c432
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule LiterLlm.UserMessage do
  @moduledoc false

  defstruct content: :text,
            name: ""
end
