# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:7499d97bdecec9ba068f9bf13fdaad6528c82e061c3755d3ae2763715948c3dd
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# frozen_string_literal: true

require_relative "liter_llm/version"
require_relative "liter_llm/native"

# Top-level namespace for the LiterLlm Ruby binding.
#
# All type and function symbols are re-exported from the native extension
# loaded via `require_relative "liter_llm/native"`. See
# {file:README.md} for usage examples and the upstream documentation
# for the full API reference.
module LiterLlm
  # Re-export all types and functions from native extension
end

# Keep generated types under LiterLlm. Publishing generated constants
# into Object makes generic names collide with unrelated Ruby libraries.
