// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:47fdc0539731c0553c79a3c0609a4884040bbf525813784dbf95109ddeda2ddd
// To regenerate: alef generate
// To verify freshness: alef verify
import { defineConfig } from "vitest/config";

export default defineConfig({
	test: {
		include: ["tests/**/*.test.ts"],
		testTimeout: 30000,
		hookTimeout: 120000,
		teardownTimeout: 30000,
		globalSetup: "./globalSetup.ts",
		setupFiles: ["./setup.ts"],
	},
});
