// Generated by alef. Do not edit by hand.
// alef:hash:d3f9b88aa678cc084b1542c1c9047657cfde5d9084d86078859fc7667bdd069b

// Traits module (empty in Dart as Dart does not have trait systems like Rust).
// This file is kept for API surface consistency across language bindings.
