# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:32010c83476bc7475559a6a9493de79b9bb6101c8890a4c1163b7ded120f69fd
# To regenerate: alef e2e generate
# To verify freshness: alef verify

"""E2e tests for category: parity."""

import os

import pytest
from liter_llm import create_client
from liter_llm._internal_bindings import ChatCompletionRequest


@pytest.mark.asyncio

async def test_api_surface_parity() -> None:
    """Canonical API surface definition for cross-binding parity verification."""
    client = create_client(api_key="test-key", base_url=os.environ["MOCK_SERVER_URL"] + "/fixtures/api_surface_parity")
    req = ChatCompletionRequest.from_json("{\"messages\":[{\"content\":\"Hello\",\"role\":\"user\"}],\"model\":\"gpt-4o\"}")

    result = await client.chat(req)
    assert result is not None
