<?php

// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:4a95c4ab0da36e99b176f90c7a84f5de063d1b9b0893785cd1818a28e236b485
// To regenerate: alef generate
// To verify freshness: alef verify
declare(strict_types=1);

namespace Liter\Llm;

/**
 * The value broadcast from a singleflight leader to all followers.
 *
 * The error value is shared so every follower receives the same upstream
 * failure without cloning the underlying error.
 */
final class SingleflightResult
{
}
