<?php

// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:0c8b7f2510910f3f77b6965e697837d21f030d901b3f79c1e38060f1880f9513
// To regenerate: alef generate
// To verify freshness: alef verify
declare(strict_types=1);

namespace Liter\Llm;

/**
 * The value broadcast from a singleflight leader to all followers.
 *
 * The error value is shared so every follower receives the same upstream
 * failure without cloning the underlying error.
 */
final class SingleflightResult
{
}
