// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:c249c70b7640c53f754d8c96cd8e49cec28afa7f81e8f316163a5ff7df9c9773
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg.literllm;

import java.util.List;
import java.util.Optional;
import com.fasterxml.jackson.annotation.JsonProperty;

public record ChatCompletionChunk(
    String id,
    /** Always {@code "chat.completion.chunk"} from OpenAI-compatible APIs.  Stored */
    String object,
    long created,
    String model,
    List<StreamChoice> choices,
    Optional<Usage> usage,
    @JsonProperty("system_fingerprint") Optional<String> systemFingerprint,
    @JsonProperty("service_tier") Optional<String> serviceTier
) {
    public static ChatCompletionChunkBuilder builder() {
        return new ChatCompletionChunkBuilder();
    }
}
