// DO NOT EDIT - auto-generated by alef
// alef:hash:c249c70b7640c53f754d8c96cd8e49cec28afa7f81e8f316163a5ff7df9c9773
package dev.kreuzberg.literllm;

public class ContextWindowExceededException extends LiterLlmErrorException {
    /** Creates a new ContextWindowExceededException with the given message. */
    public ContextWindowExceededException(final String message) {
        super(message);
    }

    /** Creates a new ContextWindowExceededException with the given message and cause. */
    public ContextWindowExceededException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
