// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:5655aa3f4f7d3b6f87927f5ae9e0fb04f3f271ace58f437f407deae1951366b6
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg.literllm;

import com.fasterxml.jackson.annotation.JsonProperty;

public record DocumentContent(String data, @JsonProperty("media_type") String mediaType) {
    public static DocumentContentBuilder builder() {
        return new DocumentContentBuilder();
    }
}
