// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:4c9adc9d6f29c9ecf656e39a2da402632690a6c7bbe21db21321bb5ee31cf298
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg.literllm;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public enum EmbeddingInput {
    Single("single"),
    Multiple("multiple");

    /** The string value. */
    private final String value;

    EmbeddingInput(final String value) {
        this.value = value;
    }

    /** Returns the string value. */
    @JsonValue
    public String getValue() {
        return value;
    }

    /** Creates an instance from a string value. */
    @JsonCreator
    public static EmbeddingInput fromValue(final String value) {
        for (EmbeddingInput e : values()) {
            if (e.value.equalsIgnoreCase(value)) {
                return e;
            }
        }
        throw new IllegalArgumentException("Unknown value: " + value);
    }
}
