// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:c249c70b7640c53f754d8c96cd8e49cec28afa7f81e8f316163a5ff7df9c9773
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg.literllm;

import java.util.List;
import java.util.Optional;

public record EmbeddingResponse(
    /** Always {@code "list"} from OpenAI-compatible APIs.  Stored as a plain */
    String object,
    List<EmbeddingObject> data,
    String model,
    Optional<Usage> usage
) {
}
