// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:c249c70b7640c53f754d8c96cd8e49cec28afa7f81e8f316163a5ff7df9c9773
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg.literllm;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Why a choice stopped generating tokens.
 */
public enum FinishReason {
    Stop("stop"),
    Length("length"),
    ToolCalls("tool_calls"),
    ContentFilter("content_filter"),
    /** Deprecated legacy finish reason; retained for API compatibility. */
    FunctionCall("function_call"),
    /**
     * Catch-all for unknown finish reasons returned by non-OpenAI providers.
     */
    Other("other");

    /** The string value. */
    private final String value;

    FinishReason(final String value) {
        this.value = value;
    }

    /** Returns the string value. */
    @JsonValue
    public String getValue() {
        return value;
    }

    /** Creates an instance from a string value. */
    @JsonCreator
    public static FinishReason fromValue(final String value) {
        for (FinishReason e : values()) {
            if (e.value.equalsIgnoreCase(value)) {
                return e;
            }
        }
        throw new IllegalArgumentException("Unknown value: " + value);
    }
}
