// DO NOT EDIT - auto-generated by alef
// alef:hash:ea102706007310263e9e6a1893eb5c8dfeb12198683123bb1e27398388c06137
package dev.kreuzberg.literllm;

public class HookRejectedException extends LiterLlmErrorException {
    /** Creates a new HookRejectedException with the given message. */
    public HookRejectedException(final String message) {
        super(message);
    }

    /** Creates a new HookRejectedException with the given message and cause. */
    public HookRejectedException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
