// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:c249c70b7640c53f754d8c96cd8e49cec28afa7f81e8f316163a5ff7df9c9773
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg.literllm;

/** Exception thrown by LiterLlmRs. */
public class LiterLlmRsException extends Exception {
    /** The error code. */
    private final int code;

    /** Creates a new LiterLlmRsException. */
    public LiterLlmRsException(final int code, final String message) {
        super(message);
        this.code = code;
    }

    /** Creates a new LiterLlmRsException with a cause. */
    public LiterLlmRsException(final String message, final Throwable cause) {
        super(message, cause);
        this.code = -1;
    }

    /** Returns the error code. */
    public int getCode() {
        return code;
    }
}
