// DO NOT EDIT - auto-generated by alef
// alef:hash:b2410413f1fde9835ef65506ca2b5928aa183611d631ac3ce6439c3cbe8c80a4
package dev.kreuzberg.literllm;

/** All errors that can occur when using `liter-llm`. */
public class LiterLlmErrorException extends Exception {
    /** Creates a new LiterLlmErrorException with the given message. */
    public LiterLlmErrorException(final String message) {
        super(message);
    }

    /** Creates a new LiterLlmErrorException with the given message and cause. */
    public LiterLlmErrorException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
