// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:136ba8cde4998c21317f95271e0ccac311ba0ca62853ed94294295db2a3028c2
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg.literllm;

import java.util.Optional;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * An image extracted from an OCR page.
 */
public record OcrImage(String id, @JsonProperty("image_base64") Optional<String> imageBase64) {
}
