// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:99dc45040e83e6f52532bb094d476801bbac0f8733d95cdc4a6a7f8b4002f8ca
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg.literllm;

import java.util.Optional;

public class StreamOptionsBuilder {

    private Optional<Boolean> includeUsage = Optional.empty();

    /** Sets the includeUsage field. */
    public StreamOptionsBuilder withIncludeUsage(final Optional<Boolean> value) {
        this.includeUsage = value;
        return this;
    }

    /** Builds the StreamOptions instance. */
    public StreamOptions build() {
        return new StreamOptions(
            includeUsage
        );
    }
}
