// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:621ccf8b6e0d2172e7f42f395ad1813dd3761234129753f9b460aed5b79a7d19
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg.literllm;

import java.util.List;
import java.util.Optional;

public class StreamDeltaBuilder {

    private Optional<String> role = Optional.empty();
    private Optional<String> content = Optional.empty();
    private Optional<List<StreamToolCall>> toolCalls = Optional.empty();
    private Optional<StreamFunctionCall> functionCall = Optional.empty();
    private Optional<String> refusal = Optional.empty();

    /** Sets the role field. */
    public StreamDeltaBuilder withRole(final Optional<String> value) {
        this.role = value;
        return this;
    }

    /** Sets the content field. */
    public StreamDeltaBuilder withContent(final Optional<String> value) {
        this.content = value;
        return this;
    }

    /** Sets the toolCalls field. */
    public StreamDeltaBuilder withToolCalls(final Optional<List<StreamToolCall>> value) {
        this.toolCalls = value;
        return this;
    }

    /** Sets the functionCall field. */
    public StreamDeltaBuilder withFunctionCall(final Optional<StreamFunctionCall> value) {
        this.functionCall = value;
        return this;
    }

    /** Sets the refusal field. */
    public StreamDeltaBuilder withRefusal(final Optional<String> value) {
        this.refusal = value;
        return this;
    }

    /** Builds the StreamDelta instance. */
    public StreamDelta build() {
        return new StreamDelta(
            role,
            content,
            toolCalls,
            functionCall,
            refusal
        );
    }
}
