// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:b13d4fe4d71fdf010264dcc52edf4df21176cf0aff29960388ecfdd46d663af0
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg.literllm;

import java.util.Optional;

public class StreamOptionsBuilder {

    private Optional<Boolean> includeUsage = Optional.empty();

    /** Sets the includeUsage field. */
    public StreamOptionsBuilder withIncludeUsage(final Optional<Boolean> value) {
        this.includeUsage = value;
        return this;
    }

    /** Builds the StreamOptions instance. */
    public StreamOptions build() {
        return new StreamOptions(
            includeUsage
        );
    }
}
