// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:c249c70b7640c53f754d8c96cd8e49cec28afa7f81e8f316163a5ff7df9c9773
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg.literllm;

import java.util.Optional;

public class StreamChoiceBuilder {

    private int index = 0;
    private StreamDelta delta = null;
    private Optional<FinishReason> finishReason = Optional.empty();

    /** Sets the index field. */
    public StreamChoiceBuilder withIndex(final int value) {
        this.index = value;
        return this;
    }

    /** Sets the delta field. */
    public StreamChoiceBuilder withDelta(final StreamDelta value) {
        this.delta = value;
        return this;
    }

    /** Sets the finishReason field. */
    public StreamChoiceBuilder withFinishReason(final Optional<FinishReason> value) {
        this.finishReason = value;
        return this;
    }

    /** Builds the StreamChoice instance. */
    public StreamChoice build() {
        return new StreamChoice(
            index,
            delta,
            finishReason
        );
    }
}
