// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:0ea7c841215b33e2155ee6bd581e2e155e0c038dc03869efc27b22d62f61171d
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg.literllm;

import java.util.Optional;

public class SystemMessageBuilder {

    private String content = "";
    private Optional<String> name = Optional.empty();

    /** Sets the content field. */
    public SystemMessageBuilder withContent(final String value) {
        this.content = value;
        return this;
    }

    /** Sets the name field. */
    public SystemMessageBuilder withName(final Optional<String> value) {
        this.name = value;
        return this;
    }

    /** Builds the SystemMessage instance. */
    public SystemMessage build() {
        return new SystemMessage(
            content,
            name
        );
    }
}
