// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:79243f04978b8ffa793376d5a0f76dc0fd1e3a020ec7e17c4a26c8924608b0d6
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg.literllm;

import java.util.Optional;
import com.fasterxml.jackson.annotation.JsonProperty;

public record ToolMessage(
    String content,
    @JsonProperty("tool_call_id") String toolCallId,
    Optional<String> name
) {
    public static ToolMessageBuilder builder() {
        return new ToolMessageBuilder();
    }
}
