// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:ad439a5f942b7adb32120ce60f14abdae4732437c901abf032a5a9a136f12a15
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg.literllm;

import java.util.List;
import java.util.Optional;

/**
 * Response from a transcription request.
 */
public record TranscriptionResponse(
    String text,
    Optional<String> language,
    Optional<Double> duration,
    Optional<List<TranscriptionSegment>> segments
) {
    public static TranscriptionResponseBuilder builder() {
        return new TranscriptionResponseBuilder();
    }
}
