// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:f23bb65ba89e38946a74e5c5e52391d9bf0ff76066d21fb5f819c6f9c444dd71
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg.literllm;


public class UsageBuilder {

    private long promptTokens = 0;
    private long completionTokens = 0;
    private long totalTokens = 0;

    /** Sets the promptTokens field. */
    public UsageBuilder withPromptTokens(final long value) {
        this.promptTokens = value;
        return this;
    }

    /** Sets the completionTokens field. */
    public UsageBuilder withCompletionTokens(final long value) {
        this.completionTokens = value;
        return this;
    }

    /** Sets the totalTokens field. */
    public UsageBuilder withTotalTokens(final long value) {
        this.totalTokens = value;
        return this;
    }

    /** Builds the Usage instance. */
    public Usage build() {
        return new Usage(
            promptTokens,
            completionTokens,
            totalTokens
        );
    }
}
