// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:c249c70b7640c53f754d8c96cd8e49cec28afa7f81e8f316163a5ff7df9c9773
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg.literllm;

import com.fasterxml.jackson.annotation.JsonProperty;

public record Usage(
    /** Prompt tokens used. Defaults to 0 when absent (some providers omit this). */
    @JsonProperty("prompt_tokens") long promptTokens,
    /** Completion tokens used. Defaults to 0 when absent (e.g. embedding responses). */
    @JsonProperty("completion_tokens") long completionTokens,
    /** Total tokens used. Defaults to 0 when absent (some providers omit this). */
    @JsonProperty("total_tokens") long totalTokens
) {
    public static UsageBuilder builder() {
        return new UsageBuilder();
    }
}
