# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:73516780160260b48f0f858446476f02c4d37d19c77500de1a053109f5d49a60
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# E2e tests for category: custom_provider
defmodule E2e.CustomProviderTest do
  use ExUnit.Case, async: false

  describe "provider_auth" do
    test "provider_auth" do
      {:ok, client} = LiterLlm.create_client("test-key", base_url: (System.get_env("MOCK_SERVER_URL") || "") <> "/fixtures/provider_auth")
      {:ok, result} = LiterLlm.defaultclient_chat_async(client, "{\"messages\":[{\"content\":\"Hello\",\"role\":\"user\"}],\"model\":\"my-auth-model-v1\"}")
    end
  end

  describe "register_provider" do
    test "register_provider" do
      {:ok, client} = LiterLlm.create_client("test-key", base_url: (System.get_env("MOCK_SERVER_URL") || "") <> "/fixtures/register_provider")
      {:ok, result} = LiterLlm.defaultclient_chat_async(client, "{\"messages\":[{\"content\":\"Hello\",\"role\":\"user\"}],\"model\":\"my-model-v1\"}")
    end
  end
end
