// This file is auto-generated by alef. DO NOT EDIT.
import { describe, it, expect } from 'vitest';
import { createClient, WasmChatCompletionRequest } from 'liter_llm';

describe('ocr', () => {
  it('ocr_url_document: OCR request with a document URL input', async () => {
    const client = await createClient('test-key', process.env.MOCK_SERVER_URL);
    const options = new WasmChatCompletionRequest();
    options.document = { type: "document_url", url: "https://example.com/doc.pdf" };
    options.model = "mistral/mistral-ocr-latest";
    const result = await client.chat(options);
  });
});
