# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:d70ac3e79f2b86f5ed75344059bef25e6d84b483d84122b0df3d2338bea73f06
# To regenerate: alef generate
# To verify freshness: alef verify
# frozen_string_literal: true

require 'spec_helper'
require 'liter_llm'
require 'json'

RSpec.describe 'custom_provider' do

  it 'provider_auth: Tests custom provider with custom auth header' do
    client = LiterLlm.create_client('test-key', ENV.fetch('MOCK_SERVER_URL') + '/fixtures/provider_auth')
    result = client.chat_async(LiterLlm::ChatCompletionRequest.new(messages: [{ 'content' => 'Hello', 'role' => 'user' }], model: 'my-auth-model-v1'))

    expect(result).not_to be_nil
  end


  it 'register_provider: Tests that a custom provider can be registered and routes requests' do
    client = LiterLlm.create_client('test-key', ENV.fetch('MOCK_SERVER_URL') + '/fixtures/register_provider')
    result = client.chat_async(LiterLlm::ChatCompletionRequest.new(messages: [{ 'content' => 'Hello', 'role' => 'user' }], model: 'my-model-v1'))

    expect(result).not_to be_nil
  end

end
