# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:5af1505f9e4a0243f66d74f287c39524ccda12cf1b4fb0cd39f1135993b417d3
# To regenerate: alef e2e generate
# To verify freshness: alef verify
# frozen_string_literal: true

require 'spec_helper'
require 'liter_llm'
require 'json'

RSpec.describe 'search' do

  it 'search_basic: Basic web search request with a simple query' do
    client = LiterLlm.create_client('test-key', ENV.fetch('MOCK_SERVER_URL') + '/fixtures/search_basic')
    result = client.search_async(LiterLlm::SearchRequest.new(model: 'brave/web-search', query: 'What is Rust programming language?'))

    expect(result).not_to be_nil
  end


  it 'search_empty_results: Web search with a query that returns no results' do
    client = LiterLlm.create_client('test-key', ENV.fetch('MOCK_SERVER_URL') + '/fixtures/search_empty_results')
    result = client.search_async(LiterLlm::SearchRequest.new(model: 'brave/web-search', query: 'xyznonexistent12345xyz'))

    expect(result).not_to be_nil
  end


  it 'search_error_400: 400 Bad Request error when search query is empty' do
    client = LiterLlm.create_client('test-key', ENV.fetch('MOCK_SERVER_URL') + '/fixtures/search_error_400')
    expect {
      client.search_async(LiterLlm::SearchRequest.new(model: 'brave/web-search', query: ''))
    }.to raise_error(RuntimeError) # skipped: declared error variant 'BadRequest' not yet preserved as a distinct identity by this backend's generator
  end
  # skipped: assertion type 'equals' has no accessor for error field error.status_code in this backend


  it 'search_error_401: 401 Unauthorized error on web search due to invalid API credentials' do
    client = LiterLlm.create_client('test-key', ENV.fetch('MOCK_SERVER_URL') + '/fixtures/search_error_401')
    expect {
      client.search_async(LiterLlm::SearchRequest.new(model: 'brave/web-search', query: 'test'))
    }.to raise_error(RuntimeError) # skipped: declared error variant 'Authentication' not yet preserved as a distinct identity by this backend's generator
  end
  # skipped: assertion type 'equals' has no accessor for error field error.status_code in this backend


  it 'search_with_max_results: Search request with max_results parameter limiting response count' do
    client = LiterLlm.create_client('test-key', ENV.fetch('MOCK_SERVER_URL') + '/fixtures/search_with_max_results')
    result = client.search_async(LiterLlm::SearchRequest.new(max_results: 2, model: 'brave/web-search', query: 'Rust programming'))
    expect(result.results.length).to eq(2)

  end

end
