// DO NOT EDIT - auto-generated by alef
// alef:hash:645d8ff0f3a0ef7684f9b9ea4ce1ae251a78a2a3481ecdeabf7643c53d644bb0
package io.xberg.literllm;

/**
 * `status` preserves the exact HTTP status code received (401 or 403).
 */
public class AuthenticationException extends LiterLlmErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new AuthenticationException with the given message. */
  public AuthenticationException(final String message) {
    super(message);
  }

  /** Creates a new AuthenticationException with the given message and cause. */
  public AuthenticationException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
