// DO NOT EDIT - auto-generated by alef
// alef:hash:b5eef8f245c576ce71051d2686a7d2dfcb00b9ff70f7cf6261ae0d0d7f7be5f2
package io.xberg.literllm;

/**
 * `status` preserves the exact HTTP status code received (400, 405, 413, 422, …).
 */
public class BadRequestException extends LiterLlmErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new BadRequestException with the given message. */
  public BadRequestException(final String message) {
    super(message);
  }

  /** Creates a new BadRequestException with the given message and cause. */
  public BadRequestException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
