// DO NOT EDIT - auto-generated by alef
// alef:hash:645d8ff0f3a0ef7684f9b9ea4ce1ae251a78a2a3481ecdeabf7643c53d644bb0
package io.xberg.literllm;

/**
 * `status` preserves the exact HTTP status code received (400, 405, 413, 422, …).
 */
public class BadRequestException extends LiterLlmErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new BadRequestException with the given message. */
  public BadRequestException(final String message) {
    super(message);
  }

  /** Creates a new BadRequestException with the given message and cause. */
  public BadRequestException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
