// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:59cac5c166131b797b3063f3b19ba8b8f8a0d1a100f0b2a219f1455f5ab63f85
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
package io.xberg.literllm;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonPOJOBuilder;

/**
 * Request processing counts for a batch.
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = BatchRequestCounts.Builder.class)
public record BatchRequestCounts(
    @JsonProperty("total") long total,
    @JsonProperty("completed") long completed,
    @JsonProperty("failed") long failed
) {
    /** Creates a new Builder for constructing instances of this record. */
    public static Builder builder() {
        return new Builder();
    }

    // CPD-OFF
    /** Jackson builder for BatchRequestCounts deserialization. */
    @com.fasterxml.jackson.annotation.JsonIgnoreProperties(ignoreUnknown = true)
    @JsonPOJOBuilder(withPrefix = "with", buildMethodName = "build")
    public static final class Builder {

        private long total;
        private long completed;
        private long failed;

        /** Sets the total field. */
        @JsonProperty("total")
        public Builder withTotal(final long value) {
            this.total = value;
            return this;
        }

        /** Sets the completed field. */
        @JsonProperty("completed")
        public Builder withCompleted(final long value) {
            this.completed = value;
            return this;
        }

        /** Sets the failed field. */
        @JsonProperty("failed")
        public Builder withFailed(final long value) {
            this.failed = value;
            return this;
        }

        /** Constructs a BatchRequestCounts instance from the builder's current state. */
        public BatchRequestCounts build() {
            return new BatchRequestCounts(
                total,
                completed,
                failed
            );
        }
    }
    // CPD-ON
}
