// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:9c479751c0805b45ce76a17491cc7b1b4c87a95d35e5ac93b5d5d0ac4b974284
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
package io.xberg.literllm;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonPOJOBuilder;
import org.jspecify.annotations.Nullable;

/**
 * Query parameters for listing batches.
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = BatchListQuery.Builder.class)
public record BatchListQuery(
    @Nullable @JsonProperty("limit") Integer limit,
    @Nullable @JsonProperty("after") String after
) {
    /** Creates a new Builder for constructing instances of this record. */
    public static Builder builder() {
        return new Builder();
    }

    // CPD-OFF
    /** Jackson builder for BatchListQuery deserialization. */
    @com.fasterxml.jackson.annotation.JsonIgnoreProperties(ignoreUnknown = true)
    @JsonPOJOBuilder(withPrefix = "with", buildMethodName = "build")
    public static final class Builder {

        @Nullable private Integer limit;
        @Nullable private String after;

        /** Sets the limit field. */
        @JsonProperty("limit")
        public Builder withLimit(final @Nullable Integer value) {
            this.limit = value;
            return this;
        }

        /** Sets the after field. */
        @JsonProperty("after")
        public Builder withAfter(final @Nullable String value) {
            this.after = value;
            return this;
        }

        /** Constructs a BatchListQuery instance from the builder's current state. */
        public BatchListQuery build() {
            return new BatchListQuery(
                limit,
                after
            );
        }
    }
    // CPD-ON
}
