// DO NOT EDIT - auto-generated by alef
// alef:hash:05d5dee22898f84797388227800435a6483450041f72eb54a154940b848ce981
package io.xberg.literllm;

/** Exception for BudgetExceededException. */
public class BudgetExceededException extends LiterLlmErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new BudgetExceededException with the given message. */
  public BudgetExceededException(final String message) {
    super(message);
  }

  /** Creates a new BudgetExceededException with the given message and cause. */
  public BudgetExceededException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
