// DO NOT EDIT - auto-generated by alef
// alef:hash:ace6306184a16bf4e5ebcc3008be58ad51780d8b498c86991e5b2de8e6b0e3c5
package io.xberg.literllm;

/** Exception for BudgetExceededException. */
public class BudgetExceededException extends LiterLlmErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new BudgetExceededException with the given message. */
  public BudgetExceededException(final String message) {
    super(message);
  }

  /** Creates a new BudgetExceededException with the given message and cause. */
  public BudgetExceededException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
