// DO NOT EDIT - auto-generated by alef
// alef:hash:872f238d87e53196bf0612a2399cce53ed37b69e19c0bf1e94b4e196c7fbd128
package io.xberg.literllm;

/** Exception for BudgetExceededException. */
public class BudgetExceededException extends LiterLlmErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new BudgetExceededException with the given message. */
  public BudgetExceededException(final String message) {
    super(message);
  }

  /** Creates a new BudgetExceededException with the given message and cause. */
  public BudgetExceededException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
