// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:9c479751c0805b45ce76a17491cc7b1b4c87a95d35e5ac93b5d5d0ac4b974284
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
package io.xberg.literllm;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import java.util.Map;

/**
 * Storage backend for the response cache.
 */
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, property = "type", visible = false)
@JsonSubTypes({
    @JsonSubTypes.Type(value = CacheBackend.Memory.class, name = "memory"),
    @JsonSubTypes.Type(value = CacheBackend.OpenDal.class, name = "open_dal")
})
@com.fasterxml.jackson.annotation.JsonIgnoreProperties(ignoreUnknown = true)
public sealed interface CacheBackend {

    /**
     * In-memory LRU cache (default). No external dependencies.
     */
    record Memory() implements CacheBackend {
    }

    /**
     * OpenDAL-backed storage. Supports 40+ backends (S3, Redis, GCS, local FS, etc.).
     */
    record OpenDal(
        @JsonProperty("scheme") String scheme,
        @JsonProperty("config") Map<String, String> config
    ) implements CacheBackend {
    }
}
