// DO NOT EDIT - auto-generated by alef
// alef:hash:d37ea66d954ad374b69c65cfd4aa370951e0c0c095fdc72c3a3f39389871d474
package io.xberg.literllm;

/**
 * A cache file **read** failed on an otherwise-fresh cache file. Cache
 * **write** failures are best-effort and never surface as this error
 * (see [`refresh_catalog`]).
 */
public class CacheException extends CatalogRefreshErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new CacheException with the given message. */
  public CacheException(final String message) {
    super(message);
  }

  /** Creates a new CacheException with the given message and cause. */
  public CacheException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
