// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:37162a1e399b62a1fc6b92939cd166358b0accfaeef9d55c10c5eb22c6f7bbea
// To regenerate: alef generate
// To verify freshness: alef verify
package io.xberg.literllm;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import java.util.Map;

/**
 * Storage backend for the response cache.
 */
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, property = "type", visible = false)
@JsonSubTypes({
    @JsonSubTypes.Type(value = CacheBackend.Memory.class, name = "memory"),
    @JsonSubTypes.Type(value = CacheBackend.OpenDal.class, name = "open_dal")
})
@com.fasterxml.jackson.annotation.JsonIgnoreProperties(ignoreUnknown = true)
public sealed interface CacheBackend {

    /**
     * In-memory LRU cache (default). No external dependencies.
     */
    record Memory() implements CacheBackend {
    }

    /**
     * OpenDAL-backed storage. Supports 40+ backends (S3, Redis, GCS, local FS, etc.).
     */
    record OpenDal(
        @JsonProperty("scheme") String scheme,
        @JsonProperty("config") Map<String, String> config
    ) implements CacheBackend {
    }
}
