// DO NOT EDIT - auto-generated by alef
// alef:hash:417c6ff012628ceab4a8af46a892dfaaca21d4f491b0f32ae64b1a9a922e4389
package io.xberg.literllm;

/**
 * A cache file **read** failed on an otherwise-fresh cache file. Cache
 * **write** failures are best-effort and never surface as this error
 * (see [`refresh_catalog`]).
 */
public class CacheException extends CatalogRefreshErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new CacheException with the given message. */
  public CacheException(final String message) {
    super(message);
  }

  /** Creates a new CacheException with the given message and cause. */
  public CacheException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
