// DO NOT EDIT - auto-generated by alef
// alef:hash:d37ea66d954ad374b69c65cfd4aa370951e0c0c095fdc72c3a3f39389871d474
package io.xberg.literllm;

/**
 * Errors from [`refresh_catalog`] and [`install_catalog_overlay_from_str`].
 *
 * On every variant, the overlay registry is left untouched: a previously
 * installed overlay (or the embedded catalog, if none was ever installed)
 * remains active. This is the air-gap-safety contract — a failed refresh
 * never degrades pricing/model-info availability.
 */
public class CatalogRefreshErrorException extends Exception {
  private static final long serialVersionUID = 1L;
  /** Creates a new CatalogRefreshErrorException with the given message. */
  public CatalogRefreshErrorException(final String message) {
    super(message);
  }

  /** Creates a new CatalogRefreshErrorException with the given message and cause. */
  public CatalogRefreshErrorException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
