// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:ce2fe1f69f36a5987e1e263a3f1b3a4e812f42fafa8ab3d88fdf55c862386619
// To regenerate: alef generate
// To verify freshness: alef verify
package io.xberg.literllm;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Observable state of a circuit breaker.
 */
@SuppressWarnings("PMD")
public enum CircuitState {
    /**
     * Requests flow through normally.
     */
    Closed("Closed"),
    /**
     * All requests are rejected; the circuit is waiting for the backoff to elapse.
     */
    Open("Open"),
    /**
     * One probe request is allowed through to test service health.
     */
    HalfOpen("HalfOpen");


    /** The string value. */
    private final String value;

    CircuitState(final String value) {
        this.value = value;
    }

    /** Returns the string value. */
    @JsonValue
    public String getValue() {
        return value;
    }

    /** Creates an instance from a string value. */
    @JsonCreator
    public static CircuitState fromValue(final String value) {
        for (CircuitState e : values()) {
            if (e.value.equalsIgnoreCase(value)) {
                return e;
            }
        }
        throw new IllegalArgumentException("Unknown CircuitState value: " + value);
    }

    /** Returns the wire-format string value (matches JSON serialization). */
    @Override
    public String toString() {
        return value;
    }
}
