// DO NOT EDIT - auto-generated by alef
// alef:hash:cf12a91b71f7e7e78174f6741902a20de61b1e89a6a7b79a92a43f7c017e8379
package io.xberg.literllm;

/** Exception for ContentPolicyException. */
public class ContentPolicyException extends LiterLlmErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new ContentPolicyException with the given message. */
  public ContentPolicyException(final String message) {
    super(message);
  }

  /** Creates a new ContentPolicyException with the given message and cause. */
  public ContentPolicyException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
