// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:2a4b9af0cb4ce14e77278e2908e51e3f1e4a2d6f1ade4f0c21f5b2295857f6e3
// To regenerate: alef generate
// To verify freshness: alef verify
package io.xberg.literllm;

/** Exception thrown when an FFI value conversion fails. */
@SuppressWarnings({"checkstyle:LineLength", "PMD"})
public class ConversionErrorException extends LiterLlmRsException {
  private static final long serialVersionUID = 1L;

  /** Creates a new ConversionErrorException. */
  public ConversionErrorException(final String message) {
    super(1, message);
  }

  /** Creates a new ConversionErrorException with a cause. */
  public ConversionErrorException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
