// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:34ed32b57eca9e605c699f6b067ca2cc71949a16c379e8649b19c7f51c3a39cd
// To regenerate: alef generate
// To verify freshness: alef verify
package io.xberg.literllm;

/** Exception thrown when an FFI value conversion fails. */
@SuppressWarnings({"checkstyle:LineLength", "PMD"})
public class ConversionErrorException extends LiterLlmRsException {
  private static final long serialVersionUID = 1L;

  /** Creates a new ConversionErrorException. */
  public ConversionErrorException(final String message) {
    super(1, message);
  }

  /** Creates a new ConversionErrorException with a cause. */
  public ConversionErrorException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
