// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:9c479751c0805b45ce76a17491cc7b1b4c87a95d35e5ac93b5d5d0ac4b974284
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
package io.xberg.literllm;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonPOJOBuilder;

/**
 * Response from a delete operation.
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = DeleteResponse.Builder.class)
public record DeleteResponse(
    @JsonProperty("id") String id,
    @JsonProperty("object") String object,
    @JsonProperty("deleted") boolean deleted
) {
    /** Creates a new Builder for constructing instances of this record. */
    public static Builder builder() {
        return new Builder();
    }

    // CPD-OFF
    /** Jackson builder for DeleteResponse deserialization. */
    @com.fasterxml.jackson.annotation.JsonIgnoreProperties(ignoreUnknown = true)
    @JsonPOJOBuilder(withPrefix = "with", buildMethodName = "build")
    public static final class Builder {

        private String id;
        private String object;
        private boolean deleted;

        /** Sets the id field. */
        @JsonProperty("id")
        public Builder withId(final String value) {
            this.id = value;
            return this;
        }

        /** Sets the object field. */
        @JsonProperty("object")
        public Builder withObject(final String value) {
            this.object = value;
            return this;
        }

        /** Sets the deleted field. */
        @JsonProperty("deleted")
        public Builder withDeleted(final boolean value) {
            this.deleted = value;
            return this;
        }

        /** Constructs a DeleteResponse instance from the builder's current state. */
        public DeleteResponse build() {
            return new DeleteResponse(
                id,
                object,
                deleted
            );
        }
    }
    // CPD-ON
}
