// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:fd49b3e80e96c9729aa3c7a9cd3142c577fb7a6f42fb347c2a65bcbc1a5653c5
// To regenerate: alef generate
// To verify freshness: alef verify
package io.xberg.literllm;

import com.fasterxml.jackson.core.JsonGenerator;
import com.fasterxml.jackson.databind.SerializerProvider;
import com.fasterxml.jackson.databind.JsonSerializer;

/**
 * Serialises a millisecond count as the JSON shape Rust's serde derives for
 * {@code std::time::Duration} ({@code {"secs": <u64>, "nanos": <u32>}}).
 *
 * <p>Jackson's default serialisation of a {@code Long} field is a bare number, but the
 * Rust FFI layer deserializes struct JSON directly into the real {@code Duration}-typed
 * core struct, which requires this object shape. Annotate any {@code Long} field that
 * represents a Rust {@code Duration} with
 * {@code @JsonSerialize(using = DurationMillisSerializer.class)}.
 */
@SuppressWarnings("PMD")
public class DurationMillisSerializer extends JsonSerializer<Long> {

    @Override
    public void serialize(final Long value, final JsonGenerator gen,
            final SerializerProvider provider) throws java.io.IOException {
        gen.writeStartObject();
        gen.writeNumberField("secs", value / 1000L);
        gen.writeNumberField("nanos", (int) ((value % 1000L) * 1_000_000L));
        gen.writeEndObject();
    }
}
