// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:9dbd12f7b7ae994661e9637e325f1f9318abd6b5017fc49e8a24cf68a6a088bc
// To regenerate: alef generate
// To verify freshness: alef verify
package io.xberg.literllm;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * The format in which the embedding vectors are returned.
 */
@SuppressWarnings("PMD")
public enum EmbeddingFormat {
    /**
     * 32-bit floating-point numbers (default).
     */
    Float("float"),
    /**
     * Base64-encoded string representation of the floats.
     */
    Base64("base64");


    /** The string value. */
    private final String value;

    EmbeddingFormat(final String value) {
        this.value = value;
    }

    /** Returns the string value. */
    @JsonValue
    public String getValue() {
        return value;
    }

    /** Creates an instance from a string value. */
    @JsonCreator
    public static EmbeddingFormat fromValue(final String value) {
        for (EmbeddingFormat e : values()) {
            if (e.value.equalsIgnoreCase(value)) {
                return e;
            }
        }
        throw new IllegalArgumentException("Unknown EmbeddingFormat value: " + value);
    }

    /** Returns the wire-format string value (matches JSON serialization). */
    @Override
    public String toString() {
        return value;
    }
}
