// DO NOT EDIT - auto-generated by alef
// alef:hash:bd68bfcff04332d2026cec9c203c0a6ffa443f3fd9e65e03351e435582a29366
package io.xberg.literllm;

/** Exception for EndpointNotSupportedException. */
public class EndpointNotSupportedException extends LiterLlmErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new EndpointNotSupportedException with the given message. */
  public EndpointNotSupportedException(final String message) {
    super(message);
  }

  /** Creates a new EndpointNotSupportedException with the given message and cause. */
  public EndpointNotSupportedException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
