// DO NOT EDIT - auto-generated by alef
// alef:hash:73516780160260b48f0f858446476f02c4d37d19c77500de1a053109f5d49a60
package io.xberg.literllm;

/** Exception for EndpointNotSupportedException. */
public class EndpointNotSupportedException extends LiterLlmErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new EndpointNotSupportedException with the given message. */
  public EndpointNotSupportedException(final String message) {
    super(message);
  }

  /** Creates a new EndpointNotSupportedException with the given message and cause. */
  public EndpointNotSupportedException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
