// DO NOT EDIT - auto-generated by alef
// alef:hash:ac09079b02fcfe2a02a89307492f37b88464adae879d571d348a90fb95ca10ba
package io.xberg.literllm;

/** Exception for EndpointNotSupportedException. */
public class EndpointNotSupportedException extends LiterLlmErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new EndpointNotSupportedException with the given message. */
  public EndpointNotSupportedException(final String message) {
    super(message);
  }

  /** Creates a new EndpointNotSupportedException with the given message and cause. */
  public EndpointNotSupportedException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
