// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:a989ff879d18ece266f302e9332254dc8de36e0e17b2212910ba5285969f653c
// To regenerate: alef generate
// To verify freshness: alef verify
package io.xberg.literllm;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * How budget limits are enforced.
 */
@SuppressWarnings("PMD")
public enum Enforcement {
    /**
     * Reject requests that would exceed the budget with
     * LiterLlmError.BudgetExceeded.
     */
    HARD("Hard"),
    /**
     * Allow requests through but emit a {@code tracing.warn!} when the budget is
     * exceeded.
     */
    SOFT("Soft");


    /** The string value. */
    private final String value;

    Enforcement(final String value) {
        this.value = value;
    }

    /** Returns the string value. */
    @JsonValue
    public String getValue() {
        return value;
    }

    /** Creates an instance from a string value. */
    @JsonCreator
    public static Enforcement fromValue(final String value) {
        for (Enforcement e : values()) {
            if (e.value.equalsIgnoreCase(value)) {
                return e;
            }
        }
        throw new IllegalArgumentException("Unknown Enforcement value: " + value);
    }

    /** Returns the wire-format string value (matches JSON serialization). */
    @Override
    public String toString() {
        return value;
    }
}
