// DO NOT EDIT - auto-generated by alef
// alef:hash:4675811c601ba825b2213f6e6c2eca5f7023bc3761bb2e85ea00123853fdca2a
package io.xberg.literllm;

/**
 * The network fetch failed, timed out, or returned a non-success
 * status.
 */
public class FetchException extends CatalogRefreshErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new FetchException with the given message. */
  public FetchException(final String message) {
    super(message);
  }

  /** Creates a new FetchException with the given message and cause. */
  public FetchException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
