// DO NOT EDIT - auto-generated by alef
// alef:hash:7bacb53ba62128cddbad2af9594a8f7a0d67daee3cb1a21a2569382109274fca
package io.xberg.literllm;

/**
 * The network fetch failed, timed out, or returned a non-success
 * status.
 */
public class FetchException extends CatalogRefreshErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new FetchException with the given message. */
  public FetchException(final String message) {
    super(message);
  }

  /** Creates a new FetchException with the given message and cause. */
  public FetchException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
