// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:f64cc287701278e417a4101f5063c8f8a86aa548bc711d6a672a8e5b05fdc079
// To regenerate: alef generate
// To verify freshness: alef verify
package io.xberg.literllm;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Purpose of an uploaded file.
 */
@SuppressWarnings("PMD")
public enum FilePurpose {
    /**
     * File for use with Assistants API.
     */
    Assistants("assistants"),
    /**
     * File for batch processing.
     */
    Batch("batch"),
    /**
     * File for fine-tuning.
     */
    FineTune("fine-tune"),
    /**
     * File for vision/image tasks.
     */
    Vision("vision");


    /** The string value. */
    private final String value;

    FilePurpose(final String value) {
        this.value = value;
    }

    /** Returns the string value. */
    @JsonValue
    public String getValue() {
        return value;
    }

    /** Creates an instance from a string value. */
    @JsonCreator
    public static FilePurpose fromValue(final String value) {
        for (FilePurpose e : values()) {
            if (e.value.equalsIgnoreCase(value)) {
                return e;
            }
        }
        throw new IllegalArgumentException("Unknown FilePurpose value: " + value);
    }

    /** Returns the wire-format string value (matches JSON serialization). */
    @Override
    public String toString() {
        return value;
    }
}
