// DO NOT EDIT - auto-generated by alef
// alef:hash:7bacb53ba62128cddbad2af9594a8f7a0d67daee3cb1a21a2569382109274fca
package io.xberg.literllm;

/** Exception for HookRejectedException. */
public class HookRejectedException extends LiterLlmErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new HookRejectedException with the given message. */
  public HookRejectedException(final String message) {
    super(message);
  }

  /** Creates a new HookRejectedException with the given message and cause. */
  public HookRejectedException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
