// DO NOT EDIT - auto-generated by alef
// alef:hash:872f238d87e53196bf0612a2399cce53ed37b69e19c0bf1e94b4e196c7fbd128
package io.xberg.literllm;

/**
 * A different request body was submitted for an existing `Idempotency-Key`.
 *
 * Per the OpenAI `Idempotency-Key` convention, once a key is used with a
 * particular request body, subsequent requests using the same key must carry
 * an identical body.  A body mismatch is a hard error (not retryable).
 *
 * HTTP equivalent: 409 Conflict.
 */
public class IdempotencyConflictException extends LiterLlmErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new IdempotencyConflictException with the given message. */
  public IdempotencyConflictException(final String message) {
    super(message);
  }

  /** Creates a new IdempotencyConflictException with the given message and cause. */
  public IdempotencyConflictException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
