// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:b713cdc932d78474deb27590f90844c3f463beda3e2e590d8bc6c93bf009eea8
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
package io.xberg.literllm;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonPOJOBuilder;
import org.jspecify.annotations.Nullable;

/**
 * An image URL reference with optional detail level for processing.
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = ImageUrl.Builder.class)
public record ImageUrl(
    @JsonProperty("url") String url,
    @Nullable @JsonProperty("detail") ImageDetail detail
) {
    /** Creates a new Builder for constructing instances of this record. */
    public static Builder builder() {
        return new Builder();
    }

    // CPD-OFF
    /** Jackson builder for ImageUrl deserialization. */
    @com.fasterxml.jackson.annotation.JsonIgnoreProperties(ignoreUnknown = true)
    @JsonPOJOBuilder(withPrefix = "with", buildMethodName = "build")
    public static final class Builder {

        private String url;
        @Nullable private ImageDetail detail;

        /** Sets the url field. */
        @JsonProperty("url")
        public Builder withUrl(final String value) {
            this.url = value;
            return this;
        }

        /** Sets the detail field. */
        @JsonProperty("detail")
        public Builder withDetail(final @Nullable ImageDetail value) {
            this.detail = value;
            return this;
        }

        /** Constructs a ImageUrl instance from the builder's current state. */
        public ImageUrl build() {
            return new ImageUrl(
                url,
                detail
            );
        }
    }
    // CPD-ON
}
