// DO NOT EDIT - auto-generated by alef
// alef:hash:3b83b2f4d9a4b91f94a2c1e2d8286dcf870f3087dd91f21d7990fae25c87d8b3
package io.xberg.literllm;

/**
 * `source_url` did not use the `https` scheme, or failed to parse as a
 * URL at all. There is no host allowlist: the URL is user-configurable
 * for self-hosted catalog mirrors, so only the scheme is enforced.
 */
public class InsecureUrlException extends CatalogRefreshErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new InsecureUrlException with the given message. */
  public InsecureUrlException(final String message) {
    super(message);
  }

  /** Creates a new InsecureUrlException with the given message and cause. */
  public InsecureUrlException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
