// DO NOT EDIT - auto-generated by alef
// alef:hash:065cf078e2c1c97919b64c4852393744fcf464075dcec6d2569f6cb84207f213
package io.xberg.literllm;

/**
 * An internal logic error (e.g. unexpected Tower response variant).
 *
 * This should never surface in normal operation — if it does, it
 * indicates a bug in the library.
 */
public class InternalErrorException extends LiterLlmErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new InternalErrorException with the given message. */
  public InternalErrorException(final String message) {
    super(message);
  }

  /** Creates a new InternalErrorException with the given message and cause. */
  public InternalErrorException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
