// DO NOT EDIT - auto-generated by alef
// alef:hash:e21674fd9a7be5e3f375c3a5fa2f13725af0a67228635968f6520aca8d7d7bdb
package io.xberg.literllm;

/**
 * An internal logic error (e.g. unexpected Tower response variant).
 *
 * This should never surface in normal operation — if it does, it
 * indicates a bug in the library.
 */
public class InternalErrorException extends LiterLlmErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new InternalErrorException with the given message. */
  public InternalErrorException(final String message) {
    super(message);
  }

  /** Creates a new InternalErrorException with the given message and cause. */
  public InternalErrorException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
