// DO NOT EDIT - auto-generated by alef
// alef:hash:9c479751c0805b45ce76a17491cc7b1b4c87a95d35e5ac93b5d5d0ac4b974284
package io.xberg.literllm;

/** Exception for InvalidHeaderException. */
public class InvalidHeaderException extends LiterLlmErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new InvalidHeaderException with the given message. */
  public InvalidHeaderException(final String message) {
    super(message);
  }

  /** Creates a new InvalidHeaderException with the given message and cause. */
  public InvalidHeaderException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
