// DO NOT EDIT - auto-generated by alef
// alef:hash:17649ba25f6c9ece73af7f06ed46873713f523731dc29aed32ec297f6316a08e
package io.xberg.literllm;

/** Exception for InvalidHeaderException. */
public class InvalidHeaderException extends LiterLlmErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new InvalidHeaderException with the given message. */
  public InvalidHeaderException(final String message) {
    super(message);
  }

  /** Creates a new InvalidHeaderException with the given message and cause. */
  public InvalidHeaderException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
