// DO NOT EDIT - auto-generated by alef
// alef:hash:938b8ffd93c3e30d74875f875188c728addee9d4b80a97a7ac22716b3154c7c5
package io.xberg.literllm;

/** Exception for InvalidHeaderException. */
public class InvalidHeaderException extends LiterLlmErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new InvalidHeaderException with the given message. */
  public InvalidHeaderException(final String message) {
    super(message);
  }

  /** Creates a new InvalidHeaderException with the given message and cause. */
  public InvalidHeaderException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
