// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:3ded76de593774182ede950ca87d17588cef3558ece4b22930c8218d2274f0bc
// To regenerate: alef generate
// To verify freshness: alef verify
package io.xberg.literllm;

/** Exception thrown by LiterLlmRs. */
public class LiterLlmRsException extends Exception {
  private static final long serialVersionUID = 1L;
  /** The error code. */
  private final int code;

  /** Creates a new LiterLlmRsException. */
  public LiterLlmRsException(final int code, final String message) {
    super(message);
    this.code = code;
  }

  /** Creates a new LiterLlmRsException with a cause. */
  public LiterLlmRsException(final String message, final Throwable cause) {
    super(message, cause);
    this.code = -1;
  }

  /** Returns the error code. */
  public int getCode() {
    return code;
  }
}
