// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:f078cdb3b83a907fff8c0db373c4caed892b85c27142e6833ac1f131f2cc454b
// To regenerate: alef generate
// To verify freshness: alef verify
package io.xberg.literllm;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonPOJOBuilder;
import org.jspecify.annotations.Nullable;

/**
 * Request to classify content for policy violations.
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = ModerationRequest.Builder.class)
public record ModerationRequest(
    @JsonProperty("input") ModerationInput input,
    @Nullable @JsonProperty("model") String model
) {
    /** Creates a new Builder for constructing instances of this record. */
    public static Builder builder() {
        return new Builder();
    }

    // CPD-OFF
    /** Jackson builder for ModerationRequest deserialization. */
    @com.fasterxml.jackson.annotation.JsonIgnoreProperties(ignoreUnknown = true)
    @JsonPOJOBuilder(withPrefix = "with", buildMethodName = "build")
    public static final class Builder {

        private ModerationInput input;
        @Nullable private String model;

        /** Sets the input field. */
        @JsonProperty("input")
        public Builder withInput(final ModerationInput value) {
            this.input = value;
            return this;
        }

        /** Sets the model field. */
        @JsonProperty("model")
        public Builder withModel(final @Nullable String value) {
            this.model = value;
            return this;
        }

        /** Constructs a ModerationRequest instance from the builder's current state. */
        public ModerationRequest build() {
            return new ModerationRequest(
                input,
                model
            );
        }
    }
    // CPD-ON
}
