// DO NOT EDIT - auto-generated by alef
// alef:hash:9ca6714382d5977ba89edd2f09addf092370c00e33d03fa288491e783ed5cc74
package io.xberg.literllm;

/** Exception for NotFoundException. */
public class NotFoundException extends LiterLlmErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new NotFoundException with the given message. */
  public NotFoundException(final String message) {
    super(message);
  }

  /** Creates a new NotFoundException with the given message and cause. */
  public NotFoundException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
