// DO NOT EDIT - auto-generated by alef
// alef:hash:9165e93835c879eb96366cf27357e9668eaba7d6fc2e761c5e0258daa7acfce9
package io.xberg.literllm;

/** Exception for NotFoundException. */
public class NotFoundException extends LiterLlmErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new NotFoundException with the given message. */
  public NotFoundException(final String message) {
    super(message);
  }

  /** Creates a new NotFoundException with the given message and cause. */
  public NotFoundException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
