// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:b44e826e7ad0d05e4a0c5a912752745ad61c6250013936ad734a0db7f5c0e604
// To regenerate: alef generate
// To verify freshness: alef verify
package io.xberg.literllm;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonTypeInfo;

/**
 * Document input for OCR — either a URL or inline base64 data.
 */
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, property = "type", visible = false)
@JsonSubTypes({
    @JsonSubTypes.Type(value = OcrDocument.Url.class, name = "document_url"),
    @JsonSubTypes.Type(value = OcrDocument.Base64.class, name = "base64")
})
@com.fasterxml.jackson.annotation.JsonIgnoreProperties(ignoreUnknown = true)
public sealed interface OcrDocument {

    /**
     * A publicly accessible document URL.
     */
    record Url(@JsonProperty("url") String url) implements OcrDocument { }

    /**
     * Inline base64-encoded document data.
     */
    record Base64(
        @JsonProperty("data") String data,
        @JsonProperty("media_type") String mediaType
    ) implements OcrDocument {
    }
}
