// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:d06ed9e618a006a9a34af94761822a3e56d1943567a4006ed74c8db1a27c8b53
// To regenerate: alef generate
// To verify freshness: alef verify

/**
 * Universal LLM API client with Rust-powered polyglot bindings.
 */
package io.xberg.literllm;
