// DO NOT EDIT - auto-generated by alef
// alef:hash:4ddc9abdb288a19eec2f6de7caa698a810494582fbf0e04ce033dd366878c466
package io.xberg.literllm;

/**
 * The fetched or cached catalog JSON failed to parse.
 */
public class ParseException extends CatalogRefreshErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new ParseException with the given message. */
  public ParseException(final String message) {
    super(message);
  }

  /** Creates a new ParseException with the given message and cause. */
  public ParseException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
