// DO NOT EDIT - auto-generated by alef
// alef:hash:3499f3566d9797a26997a8433c89bfae067dac77fae195835cd1892cbe877add
package io.xberg.literllm;

/**
 * The fetched or cached catalog JSON failed to parse.
 */
public class ParseException extends CatalogRefreshErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new ParseException with the given message. */
  public ParseException(final String message) {
    super(message);
  }

  /** Creates a new ParseException with the given message and cause. */
  public ParseException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
