// DO NOT EDIT - auto-generated by alef
// alef:hash:08c41f5c62ca562289e71f634aceb51e35245585ce7b878b7bc1fe3a75443f48
package io.xberg.literllm;

/**
 * The fetched or cached catalog JSON failed to parse.
 */
public class ParseException extends CatalogRefreshErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new ParseException with the given message. */
  public ParseException(final String message) {
    super(message);
  }

  /** Creates a new ParseException with the given message and cause. */
  public ParseException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
