// DO NOT EDIT - auto-generated by alef
// alef:hash:a1989c3dfb77377970d88272370ba76653a7c87963705fabadca288653ab7055
package io.xberg.literllm;

/** Exception for RateLimitedException. */
public class RateLimitedException extends LiterLlmErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new RateLimitedException with the given message. */
  public RateLimitedException(final String message) {
    super(message);
  }

  /** Creates a new RateLimitedException with the given message and cause. */
  public RateLimitedException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
