// DO NOT EDIT - auto-generated by alef
// alef:hash:b713cdc932d78474deb27590f90844c3f463beda3e2e590d8bc6c93bf009eea8
package io.xberg.literllm;

/** Exception for SerializationException. */
public class SerializationException extends LiterLlmErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new SerializationException with the given message. */
  public SerializationException(final String message) {
    super(message);
  }

  /** Creates a new SerializationException with the given message and cause. */
  public SerializationException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
