// DO NOT EDIT - auto-generated by alef
// alef:hash:9bf66b5f11c0ff5c392cd3953a6c5c6a8b0f59c56c9e9c0fff3079b3a7ffb764
package io.xberg.literllm;

/**
 * `status` preserves the exact HTTP status code received (502, 503, or 504).
 */
public class ServiceUnavailableException extends LiterLlmErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new ServiceUnavailableException with the given message. */
  public ServiceUnavailableException(final String message) {
    super(message);
  }

  /** Creates a new ServiceUnavailableException with the given message and cause. */
  public ServiceUnavailableException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
