// DO NOT EDIT - auto-generated by alef
// alef:hash:80e383d619b289d0f366c0268442356f6d1f4c8234fbe32338b3a236c5e903c9
package io.xberg.literllm;

/**
 * `status` preserves the exact HTTP status code received (500, or other 5xx not covered
 * by `ServiceUnavailable`).
 */
public class ServerErrorException extends LiterLlmErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new ServerErrorException with the given message. */
  public ServerErrorException(final String message) {
    super(message);
  }

  /** Creates a new ServerErrorException with the given message and cause. */
  public ServerErrorException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
