// DO NOT EDIT - auto-generated by alef
// alef:hash:af7468ada2cd9571058cc95cc9883fc5ba83e0daaefa883551b310ba55f8dd2b
package io.xberg.literllm;

/**
 * `status` preserves the exact HTTP status code received (500, or other 5xx not covered
 * by `ServiceUnavailable`).
 */
public class ServerErrorException extends LiterLlmErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new ServerErrorException with the given message. */
  public ServerErrorException(final String message) {
    super(message);
  }

  /** Creates a new ServerErrorException with the given message and cause. */
  public ServerErrorException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
