// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:86e2ff67d558e4a0b74835099b0480204407785fb6217a6009dd6e2f2019ffc8
// To regenerate: alef generate
// To verify freshness: alef verify
package io.xberg.literllm;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonPOJOBuilder;

/**
 * Directive to call a specific tool.
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = SpecificToolChoice.Builder.class)
public record SpecificToolChoice(
    @JsonProperty("type") ToolType choiceType,
    @JsonProperty("function") SpecificFunction function
) {
    /** Creates a new Builder for constructing instances of this record. */
    public static Builder builder() {
        return new Builder();
    }

    // CPD-OFF
    /** Jackson builder for SpecificToolChoice deserialization. */
    @com.fasterxml.jackson.annotation.JsonIgnoreProperties(ignoreUnknown = true)
    @JsonPOJOBuilder(withPrefix = "with", buildMethodName = "build")
    public static final class Builder {

        @JsonProperty("type")
        private ToolType choiceType;
        private SpecificFunction function;

        /** Sets the choiceType field. */
        @JsonProperty("type")
        public Builder withChoiceType(final ToolType value) {
            this.choiceType = value;
            return this;
        }

        /** Sets the function field. */
        @JsonProperty("function")
        public Builder withFunction(final SpecificFunction value) {
            this.function = value;
            return this;
        }

        /** Constructs a SpecificToolChoice instance from the builder's current state. */
        public SpecificToolChoice build() {
            return new SpecificToolChoice(
                choiceType,
                function
            );
        }
    }
    // CPD-ON
}
