// DO NOT EDIT - auto-generated by alef
// alef:hash:4e4de847c4df813e7e8f3d6109b59fb3ebe3395efda3e20944dc618535dbbbe7
package io.xberg.literllm;

/** Exception for TimeoutException. */
public class TimeoutException extends LiterLlmErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new TimeoutException with the given message. */
  public TimeoutException(final String message) {
    super(message);
  }

  /** Creates a new TimeoutException with the given message and cause. */
  public TimeoutException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
