// DO NOT EDIT - auto-generated by alef
// alef:hash:b0f083c93e10a0089707abece35dd59bb84e9513cdee7c09514e94487d9caf41
package io.xberg.literllm;

/** Exception for TimeoutException. */
public class TimeoutException extends LiterLlmErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new TimeoutException with the given message. */
  public TimeoutException(final String message) {
    super(message);
  }

  /** Creates a new TimeoutException with the given message and cause. */
  public TimeoutException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
