// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:1a80353b21926a92bf09a7426861ed9a14140986767a0b7aadca5053085a983f
// To regenerate: alef generate
// To verify freshness: alef verify

package io.xberg.literllm.e2e;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import io.xberg.literllm.LiterLlm;
import io.xberg.literllm.ChatCompletionRequest;
import java.util.Optional;
import io.xberg.literllm.JsonUtil;

/** E2e tests for category: parity. */
public class ParityTest {

    @Test
    void testApiSurfaceParity() throws Exception {
        // Canonical API surface definition for cross-binding parity verification
        var request = JsonUtil.fromJson("{\"messages\":[{\"content\":\"Hello\",\"role\":\"user\"}],\"model\":\"gpt-4o\"}", ChatCompletionRequest.class);

        String mockServerUrl = System.getProperty("mockServerUrl"); if (mockServerUrl == null) { mockServerUrl = System.getenv("MOCK_SERVER_URL"); } String mockUrl = (mockServerUrl != null ? mockServerUrl : "http://localhost:8000") + "/fixtures/api_surface_parity";
        var client = LiterLlm.createClient("test-key", mockUrl, null, null, null);
        var result = client.chat(request);
        assertNotNull(result, "expected non-null response");


    }

}
