// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:69485226e1e63ad68cc0737d431844ac264a7b3c8e8cc0d8eec2aac659f1baf3
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code

package io.xberg.literllm.e2e;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import io.xberg.literllm.LiterLlm;
import io.xberg.literllm.ChatCompletionRequest;
import java.util.Optional;
import io.xberg.literllm.JsonUtil;

/** E2e tests for category: custom_provider. */
public class CustomProviderTest {

    @Test
    void testProviderAuth() throws Exception {
        // Tests custom provider with custom auth header
        var request = JsonUtil.fromJson("{\"messages\":[{\"content\":\"Hello\",\"role\":\"user\"}],\"model\":\"my-auth-model-v1\"}", ChatCompletionRequest.class);

        String mockServerUrl = System.getProperty("mockServerUrl"); if (mockServerUrl == null) { mockServerUrl = System.getenv("MOCK_SERVER_URL"); } String mockUrl = (mockServerUrl != null ? mockServerUrl : "http://localhost:8000") + "/fixtures/provider_auth";
        var client = LiterLlm.createClient("test-key", mockUrl, null, null, null);
        var result = client.chat(request);


    }


    @Test
    void testRegisterProvider() throws Exception {
        // Tests that a custom provider can be registered and routes requests
        var request = JsonUtil.fromJson("{\"messages\":[{\"content\":\"Hello\",\"role\":\"user\"}],\"model\":\"my-model-v1\"}", ChatCompletionRequest.class);

        String mockServerUrl = System.getProperty("mockServerUrl"); if (mockServerUrl == null) { mockServerUrl = System.getenv("MOCK_SERVER_URL"); } String mockUrl = (mockServerUrl != null ? mockServerUrl : "http://localhost:8000") + "/fixtures/register_provider";
        var client = LiterLlm.createClient("test-key", mockUrl, null, null, null);
        var result = client.chat(request);


    }

}
