// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:9c479751c0805b45ce76a17491cc7b1b4c87a95d35e5ac93b5d5d0ac4b974284
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code

package io.xberg.literllm.e2e;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import io.xberg.literllm.LiterLlm;
import io.xberg.literllm.ChatCompletionRequest;
import java.util.Optional;
import io.xberg.literllm.JsonUtil;

/** E2e tests for category: custom_provider. */
public class CustomProviderTest {

    @Test
    void testProviderAuth() throws Exception {
        // Tests custom provider with custom auth header
        var request = JsonUtil.fromJson("{\"messages\":[{\"content\":\"Hello\",\"role\":\"user\"}],\"model\":\"my-auth-model-v1\"}", ChatCompletionRequest.class);

        String mockServerUrl = System.getProperty("mockServerUrl"); if (mockServerUrl == null) { mockServerUrl = System.getenv("MOCK_SERVER_URL"); } String mockUrl = (mockServerUrl != null ? mockServerUrl : "http://localhost:8000") + "/fixtures/provider_auth";
        var client = LiterLlm.createClient("test-key", mockUrl, null, null, null);
        var result = client.chat(request);


    }


    @Test
    void testRegisterProvider() throws Exception {
        // Tests that a custom provider can be registered and routes requests
        var request = JsonUtil.fromJson("{\"messages\":[{\"content\":\"Hello\",\"role\":\"user\"}],\"model\":\"my-model-v1\"}", ChatCompletionRequest.class);

        String mockServerUrl = System.getProperty("mockServerUrl"); if (mockServerUrl == null) { mockServerUrl = System.getenv("MOCK_SERVER_URL"); } String mockUrl = (mockServerUrl != null ? mockServerUrl : "http://localhost:8000") + "/fixtures/register_provider";
        var client = LiterLlm.createClient("test-key", mockUrl, null, null, null);
        var result = client.chat(request);


    }

}
