// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:4bf49fab41463e9ec019f6e1186e304b4b1247d0b2e68799c12c1a0afacca536
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
import 'package:test/test.dart';
import 'package:liter_llm/liter_llm.dart';

// E2e tests for category: list-models
void main() {
  test('List models response returns an empty data array when no models are available', () async {
    final result = await listModels();
    expect(result.data.length, greaterThanOrEqualTo(0));
    expect(result.data.length, equals(0));
  });

  test('401 Unauthorized error on list models request when API key is invalid', () async {
    await expectLater(listModels(), throwsA(isA<Exception>()));
  });

  test('500 Internal Server Error when listing models due to server failure', () async {
    await expectLater(listModels(), throwsA(isA<Exception>()));
  });

  test('List models response with multiple model objects', () async {
    final result = await listModels();
    expect(result.data.length, greaterThanOrEqualTo(5));
    expect(result.data.get("0").object.trim(), equals('model'));
  });

}
