// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:45fa09be0cd2edd75c4d9a5325acb359b90ca52f0a87e430ec6e3ba442cf3b7d
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
import 'package:test/test.dart';
import 'package:liter_llm/liter_llm.dart';

// E2e tests for category: moderate
void main() {
  test('Moderation response with multiple categories flagged', () async {
    final result = await moderate('Extremely harmful content targeting multiple categories');
    expect(result.results.length, equals(1));
    expect(result.results.get("0").flagged, equals(true));
  });

  test('Moderation with empty string input', () async {
    final result = await moderate('');
    expect(result.results.length, equals(1));
    expect(result.results.get("0").flagged, equals(false));
  });

  test('401 Unauthorized for moderation with invalid API key', () async {
    await expectLater(moderate('Hello'), throwsA(isA<Exception>()));
  });

  test('400 Bad Request for moderation with invalid model', () async {
    await expectLater(moderate('Hello'), throwsA(isA<Exception>()));
  });

  test('Moderate multiple inputs in a single request', () async {
    final result = await moderate(['Hello world', 'Nice weather today']);
    expect(result.results.length, equals(2));
    expect(result.results.get("0").flagged, equals(false));
  });

  test('Moderation detects flagged content', () async {
    final result = await moderate('I want to hurt someone very badly');
    expect(result.results.length, equals(1));
    expect(result.results.get("0").flagged, equals(true));
  });

  test('Moderate a single non-flagged input', () async {
    final result = await moderate('The weather is nice today.');
    expect(result.results.length, equals(1));
    expect(result.results.get("0").flagged, equals(false));
  });

}
