// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:6753441630427815929fd5f846cc5b7a8480b07b7917e62bc464d3297bcb7d9f
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
import 'package:test/test.dart';
import 'package:liter_llm/liter_llm.dart';

// E2e tests for category: speech
void main() {
  test('Text-to-speech with specific voice selection', () async {
    final result = await speech('Hello world');
    expect(result.audio, isNotEmpty);
  });

  test('Speech generation with a very long input text', () async {
    final result = await speech('This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. End of input.');
    expect(result.audio, isNotEmpty);
  });

  test('401 Unauthorized for speech generation with invalid API key', () async {
    await expectLater(speech('Hello'), throwsA(isA<Exception>()));
  });

  test('400 Bad Request for speech with unsupported model', () async {
    await expectLater(speech('Hello'), throwsA(isA<Exception>()));
  });

  test('Basic text-to-speech generation', () async {
    final result = await speech('Hello, world!');
    expect(result.audio, isNotEmpty);
  });

  test('Text-to-speech with explicit MP3 response format', () async {
    final result = await speech('The quick brown fox jumps over the lazy dog.');
    expect(result.audio, isNotEmpty);
  });

}
